### ISSUE TITLE
Cmd-click on URLs or local files in the terminal

### ISSUE THREAD

**Issue by exalted** [zed-industries/community#10]
I’d like to be able to Cmd-click on URLs in the editor

Bonus: Maybe links could be highlighted as "clickable" only while `Cmd` key is pressed 🤷.

**Comment by exalted** [comment]
Curious enough links in a terminal are click-able 😉

**Comment by mikayla-maki** [comment]
Opening URLs on click is already implemented, but it needs to be hidden behind holding `cmd` and needs to be generalized to support files and /file:line:column.

**Comment by aexvir** [comment]
@mikayla-maki there is an issue opened specifically for the file paths, should we close this one in favor of https://github.com/zed-industries/community/issues/560 which is more specific?

**Comment by SomeoneToIgnore** [comment]
This comes with the 0.96.0 version.
