### ISSUE TITLE
Transform to Uppercase/Lowercase text

### ISSUE THREAD

**Issue by pftbest** [zed-industries/community#1011]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be nice to have this basic text editor feature.

**Comment by rkusa** [comment]
I'd second that, and would add camelCase, snake_case, PascalCase, etc. to the list of case transforms. The case conversion in general might already be covered by #57.

**Comment by pftbest** [comment]
Sorry for the duplicate, I failed to find the #57

**Comment by exalted** [comment]
GPT does a pretty decent job at stuff like this:

<img width="860" alt="CleanShot 2023-04-06 at 10 42 15@2x" src="https://user-images.githubusercontent.com/314398/230323624-d1850612-4e44-45f8-82cb-481eacf0741a.png">

**Comment by JosephTLyons** [comment]
`convert to upper case` and `convert to lower case` should go out with v0.99.
