### ISSUE TITLE
vim suggest/action select

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/community#1016]
### Check for existing issues

- [X] Completed

### Describe the feature

vim use h/j/k/l to the left/down/up/right , I want use <c-h/j/k/l> select lsp suggest/action

**Comment by ConradIrwin** [comment]
As of Zed v0.103 the keybindings for the menus are now configurable in your user keyboard settings (`cmd-k cmd-s` to open them).

```
[
  {
    "context": "Editor && (showing_code_actions || showing_completions)",
    "bindings": {
      "ctrl-j": "editor::ContextMenuNext", // c-j for up
      "ctrl-k": "editor::ContextMenuPrev", // c-k for down
    }
  }
]
```

There are a couple of other ContextMenu related actions you can bind to, see https://zed.dev/ref/default.json for the defaults.

Please let me know if you need any help getting this to work.
