### ISSUE TITLE
Broken link on Zed website

### ISSUE THREAD

**Issue by Mattsi-Jansky** [zed-industries/community#1028]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Click the "[Download](https://zed.dev/download)" link in the footer of https://zed.dev

### Environment

https://zed.dev

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by petros** [comment]
Thank you for opening this issue @Mattsi-Jansky. You can only access that page if you are logged in for the time being. But if you are logged in and it doesn't work, please let me know what you see.

**Comment by Sethback** [comment]
If you are logged in you still get forwarded first to the page with link not found(404) and then redirected to the download page. If you are logged out, you only get the 404 page. This only happens with the link in the footer, not via the download button right top in the page.

**Comment by JosephTLyons** [comment]
I'm going to go ahead and close this issue out.  We will be allowing everyone to download Zed here shortly and so fairly soon, this button will no longer do any permissions checking in this future, and this 404 thing should just go away.
