### ISSUE TITLE
Feature Req: Warp.dev integration with the dock

### ISSUE THREAD

**Issue by uzaxirr** [zed-industries/community#1044]
### Check for existing issues

- [X] Completed

### Describe the feature

Ability to replace the existing integrated terminal with [warp.dev ](https://www.warp.dev/)
Warp is a modern terminal built with rust and the developer community loves it. People have found a few hacky ways to integrate it with VS Code, PyCharm etc etc but no robust and built in solution. Would love if any IDE have a built in integration for it.

**Comment by iamnbutler** [comment]
I think this is unlikely to happen due to Zed already shipping an Allacrity terminal. 

Warp also uses a long diverged copy of gpui.

Finally, Zed will likely ship its own native collaborative terminal at some point.
