### ISSUE TITLE
Warning persists in the editor even after fixing syntax errors

### ISSUE THREAD

**Issue by mspanc** [zed-industries/community#1073]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I had a type mismatch in my code. Warning showed up. Even if I fixed the code, the warning persisted. I had to close and reopen the tab.

### Environment

Zed: v0.75.2 (stable)
OS: macOS 13.2.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="778" alt="Zrzut ekranu 2023-03-13 o 15 57 58" src="https://user-images.githubusercontent.com/389651/224741299-38ff3437-b6af-490a-be32-880d435363e4.png">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/10958678/Zed.log)

**Comment by mspanc** [comment]
Oh that's surprising ;)

I expected them to disappear once error was fixed

**Comment by mikayla-maki** [comment]
Yeah, we need to make some UI for these 😤
