### ISSUE TITLE
Jump to start of function via navigation bar (aka breadcrumbs)

### ISSUE THREAD

**Issue by jansol** [zed-industries/community#1085]
### Check for existing issues

- [X] Completed

### Describe the feature

The navigation bar at the top of each buffer conveniently shows the name of the function/class that the cursor is currently in. When working with very long functions it would be nice to be able to click the name of the function in the navigation bar to jump to the start of that function. (and why not with classes/modules/whatnot other scopes shown there too)

**Comment by jansol** [comment]
Ah, so this *is* a duplicate after all: #380

**Comment by wzxu** [comment]
Think this may be a duplicate of #380. Go give a 👍 there!
