### ISSUE TITLE
function hover tooltips have unreadable parameter listings

### ISSUE THREAD

**Issue by jansol** [zed-industries/community#1104]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If a function has doxygen/javadoc-style documentation comments, the hover popup for that function becomes... messy.

```c
/**
* \brief An example function that does nothing
* \param bar dummy argument whose description is broken
*/
void foo(int bar) { }
```

<img width="408" alt="image" src="https://user-images.githubusercontent.com/2588851/225277161-377d9f92-85b3-4ba9-9b86-183490355da8.png">

### Environment

Zed: v0.77.3 (stable)
OS: macOS 12.6.3
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

This is probably a limitation of the language server that's being used: clangd/clangd#529

**Comment by jansol** [comment]
Looks like the only alternative I know of, ccls, [also has problems with this](https://github.com/MaskRay/ccls/issues/779)

**Comment by jansol** [comment]
Looks like it also happens without doxygen comments:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/2588851/225287962-65c00875-37fa-4783-82d7-0855fe45857d.png">

**Comment by jansol** [comment]
A lot better as of version 102.0:
<img width="324" alt="image" src="https://github.com/zed-industries/community/assets/2588851/6baa6b47-f044-4124-9c28-21632179fa35">

Still no "proper" doxygen support, but this is an improvement as well:
<img width="414" alt="image" src="https://github.com/zed-industries/community/assets/2588851/55dff2da-cf2a-479a-9b4c-f10420b1f5fe">

Feel free to close this or repurpose as a tracking issue for doxygen support.

**Comment by JosephTLyons** [comment]
Let's close this out and start a fresh issue for doxygen support.
