### ISSUE TITLE
Code comletitions don't show when I press `^ + Space`.

### ISSUE THREAD

**Issue by walkingdevel** [zed-industries/community#1120]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

It works from the command palette but doesn't by shortcut. I think because macOS uses this shortcut for changing language.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mikayla-maki** [comment]
No reproduction, thanks for the issue :)

**Comment by diogolucasz** [comment]
Im having the same issue because I have two keyboard input sources. 

Is there a fix?

**Comment by JosephTLyons** [comment]
This is something that has been driving me up the wall.  I'll bring it up with the team.
