### ISSUE TITLE
Make Restart to update Zed a button

### ISSUE THREAD

**Issue by stephanerangaya** [zed-industries/community#1129]
### Check for existing issues

- [X] Completed

### Describe the feature

When a new version of Zed is available and downloaded, there's a message in the status bar of the application asking to _Restart to update Zed_. I think this would be more useful as a button, similar to the button on the right to _Give Feedback_.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="367" alt="image" src="https://user-images.githubusercontent.com/723109/225480395-94de7052-13af-4a79-8707-1a9cc8d9f144.png">

**Comment by JosephTLyons** [comment]
Hey @stephanerangaya - that text *is* a clickable button that will restart Zed - maybe we should probably switch that to something that actually looks like a button - is that what you are requesting?

**Comment by stephanerangaya** [comment]
Hey @JosephTLyons, sorry! I didn't know. I didn't see any changes on mouseover and I assumed it was just text.

**Comment by petros** [comment]
I am discussing the quickest possible win here through maybe changing the text to something like:

> Click to restart and update Zed

**Comment by mmnathan** [comment]
I would prefer to not have it clickable at all, or make it a dropdown to affirm the restart action. The text prompt is enough to know what to do and it prevents accidents when it is non-interactive.

**Comment by frenchbread** [comment]
Maybe a button with update icon could be added, next to existing ones, that would `restart & update` instead of text-button.
