### ISSUE TITLE
vim-mode: 's' key does not replace character

### ISSUE THREAD

**Issue by kirakirakiriko** [zed-industries/community#1147]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim, pressing 's' in normal mode deletes the character under the caret and enters insert mode, effectively achieving a 'replace current character' action. This function is missing in the vim mode in Zed.

**Comment by ThreeFx** [comment]
Similarly, `S` does not replace the current line (it has the same semantics as `cc`).

**Comment by ConradIrwin** [comment]
@kirakirakiriko Thanks for the report! `s` is now supported in zed 0.96 and above. (Though `S` is still to come! https://github.com/zed-industries/community/issues/1897).
