### ISSUE TITLE
Opening Zed should always create a new window. ⌘N with nothing open should make a new window with a new file. ⌘⌥O should open recent projects with no window open.

### ISSUE THREAD

**Issue by fwrs** [zed-industries/community#1148]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

**Steps to reproduce:**
1. Freshly install Zed
2. Open it for the first time
3. Cmd+Q it without opening any projects
4. Open Zed again (any subsequent relaunch yields this)
5. Observe that there's no Zed window, just the menu bar

**Actual result:**
The application starts (there's a dot under the dock icon) but there isn't a window. You have to manually click `File > New Window` for anything to appear.
<img width="388" alt="Screenshot 2023-03-16 at 4 46 13 PM" src="https://user-images.githubusercontent.com/44343874/225636711-f3b62025-1b00-4144-a993-f1b2fb034444.png">

**Expected result**
A Zed window appears.

Side note: this bug is slightly concealed due to the fact that you currently can't close a project. If you have an open project and click the "Remove from Project" context menu item it'll still pop up with the same project rather than an empty window on next relaunch.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by boringContributor** [comment]
Facing the same issue. You're no longer able to open Zed at all. 

My workaround is to open it through the CLI as this still works.

**Comment by JosephTLyons** [comment]
> Facing the same issue. You're no longer able to open Zed at all. 
> 
> 
> 
> My workaround is to open it through the CLI as this still works.

While in this state, you cannot open a new Zed window at all, not even via `cmd-shift-n`?

**Comment by iamnbutler** [comment]
Hey! I'm going to rename this issue to make it easier to find for others. We are working on this!

**Comment by JosephTLyons** [comment]
Just wanted to mention that `cmd-n`, with no windows open, will now open a window, as of v0.80.5 (in preview currently, should be out next week).

**Comment by GhIlyusha** [comment]
Also, closing all windows and then clicking the dock icon (with a dot under it) should show a new window, the way all other mac apps work.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out because `cmd-n`, `cmd-o` and clicking the dock icon all now work as expected when there are no windows open. It's still the case that the recent project switcher (`cmd-alt-o`) requires a window to be open, but I think that is less of a big deal.
