### ISSUE TITLE
Control-Click does not register as a right click

### ISSUE THREAD

**Issue by Leland** [zed-industries/community#1150]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On macOS, a  <kbd>Ctrl</kbd>-Click registers as a right click everywhere on the operating system.

In Zed, it does not. Instead, they're just interpreted as left click. (This is actually the first time I've had that experience in an app, didn't know it was possible!)

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by brandonweiss** [comment]
I thought Zed just didn’t have context menus for some reason—I didn’t realize it was a bug with right-click 😢 Is this affecting everyone who uses a trackpad? The only people who can right-click are mouse users?

**Comment by brandonweiss** [comment]
Oh, I didn’t know about two-finger click! That helps in the meantime, thanks!

**Comment by iamnbutler** [comment]
<img width="766" alt="CleanShot 2023-07-19 at 15 53 04@2x" src="https://github.com/zed-industries/community/assets/1714999/55ae4eb9-d27f-4e67-8aae-aa13e1eea49f">

Thanks to @ForLoveOfCats jumping on this, you should see this land in the next release or two :) Thank you for the feedback!
