### ISSUE TITLE
vue support

### ISSUE THREAD

**Issue by d1y** [zed-industries/community#1154]
### Check for existing issues

- [X] Completed

### Language

vue

### Tree Sitter parser link

https://github.com/ikatyang/tree-sitter-vue

### Language server link

https://github.com/vuejs/language-tools

### Misc notes

Zed is really fast, hurry up and support vue-lsp 👨‍💻

**Comment by JosephTLyons** [comment]
Hey @d1y, we have an older issue on this with some more upvotes.  Would you mind upvoting that issue?

- https://github.com/zed-industries/community/issues/335#issuecomment-1472177832

**Comment by sdaduanbilei** [comment]
How do you use it?

**Comment by hovsater** [comment]
> How do you use it?

Vue is not yet supported. The issue was closed due to it being a duplicate of an existing issue.

**Comment by francisceril** [comment]
Still not supported? Is there an ETA for this?

**Comment by hovsater** [comment]
Not at this moment. I'll make sure to update the original issue whenever there's news to share. 🙂
