### ISSUE TITLE
Crash on startup on M1 Max MacBook Pro

### ISSUE THREAD

**Issue by alex-kovshovik** [zed-industries/community#1156]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed started up OK the first time, but it immediately crashed after I attempted to open a directory with a few Ruby files in it. And now it crashes on startup every time I start it (probably tries to load the same directory.

### Environment

Model: MacBookPro18,2, BootROM 8419.80.7, proc 10:8:2 processors, 64 GB, SMC
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Display: DELL U3818DW, 3840 x 1600 (Ultra-wide 4K), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Nov 30 2022 02:17:16 version 20.10.965.13.8.7.131 FWID 01-1251c18d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi 2, AirPort, en0

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

2023-03-13T18:42:26 [INFO] ========== starting zed ==========
2023-03-13T18:42:26 [INFO] Opening main db
2023-03-13T18:42:26 [INFO] Opening main db
2023-03-13T18:42:26 [INFO] open paths ["/Users/alexk/decisely/osmos"]
2023-03-13T18:42:26 [INFO] Opening main db
2023-03-13T18:42:27 [ERROR] thread 'background-executor-17' panicked at 'failed to set environment variable `""` to `"n3Fv"`: Invalid argument (os error 22)': library/std/src/env.rs:353   0: backtrace::capture::Backtrace::new
   1: Zed::init_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: std::env::_set_var
   8: gpui::executor::any_future::{{closure}}
   9: async_task::raw::RawTask<F,T,S>::run
  10: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
  11: async_io::driver::block_on
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::unix::thread::Thread::new::thread_start
  15: __pthread_deallocate

2023-03-13T18:42:27 [ERROR] thread 'main' panicked at 'task has failed': /Users/administrator/.cargo/git/checkouts/async-task-939ec7beeb877e57/341b57d/src/task.rs:368   0: backtrace::capture::Backtrace::new
   1: Zed::init_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic_display
   8: core::panicking::panic_str
   9: core::option::expect_failed
  10: futures_lite::future::FutureExt::poll
  11: <gpui::executor::Task<T> as core::future::future::Future>::poll
  12: <futures_util::future::future::shared::Shared<Fut> as core::future::future::Future>::poll
  13: gpui::executor::any_local_future::{{closure}}
  14: async_task::raw::RawTask<F,T,S>::run
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::run
  28: gpui::app::App::run
  29: Zed::main
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: std::rt::lang_start::{{closure}}
  32: std::rt::lang_start_internal
  33: _main

**Comment by mikayla-maki** [comment]
Hi Alex,

Thanks so much for your issue :D. To help us debug, could you run `$SHELL -lic /usr/bin/env` from your terminal to print your environment variables? I think we're parsing that output incorrectly in your case :)

**Comment by alex-kovshovik** [comment]
Sure (some values are redacted):

```
TERM_SESSION_ID=w0t0p0:955B5FB5-DF09-4562-BDAC-9802DA16A178
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.5HCArlHpSt/Listeners
LC_TERMINAL_VERSION=3.4.19
COLORFGBG=15;0
ITERM_PROFILE=Default
XPC_FLAGS=0x0
PWD=/Users/alexk/decisely/juno
SHELL=/opt/homebrew/bin/zsh
__CFBundleIdentifier=com.googlecode.iterm2
TERM_PROGRAM_VERSION=3.4.19
TERM_PROGRAM=iTerm.app
PATH=/Users/alexk/.rvm/gems/ruby-3.0.3/bin:/Users/alexk/.rvm/gems/ruby-3.0.3@global/bin:/Users/alexk/.rvm/rubies/ruby-3.0.3/bin:/Users/alexk/.rvm/bin:/Users/alexk/.nvm/versions/node/v14.18.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/alexk/Library/Application Support/JetBrains/Toolbox/scripts
LC_TERMINAL=iTerm2
COLORTERM=truecolor
COMMAND_MODE=unix2003
TERM=xterm-256color
HOME=/Users/alexk
TMPDIR=/var/folders/h6/dj6w88gd38j25tlqfmm6dr_r0000gn/T/
USER=alexk
XPC_SERVICE_NAME=0
LOGNAME=alexk
ITERM_SESSION_ID=w0t0p0:955B5FB5-DF09-4562-BDAC-9802DA16A178
__CF_USER_TEXT_ENCODING=0x0:0:0
SHLVL=1
OLDPWD=/Users/alexk/decisely/juno
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/Users/alexk/.nvm/versions/node/v14.18.1/share/man:/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
DB_USERNAME=alexk
SECRET_KEY_BASE=redacted
EDITOR=/opt/homebrew/bin/vi
DPC_RAILS_MASTER_KEY=redacted
REDCLOUD_RAILS_MASTER_KEY=redacted
JWT_SECRET=redacted
DD_API_KEY=redacted
GITLAB_USER=alex-kovshovik
GITLAB_TOKEN=redacted
DECISELY_PRIVATE_KEY=-----BEGIN PGP PRIVATE KEY BLOCK-----redacted
PRIVATE KEY BLOCK-----
DECISELY_PUBLIC_KEY=-----BEGIN PGP PUBLIC KEY BLOCK-----
mQENBF+4SEMBCAC67WTOaYPWFtfVR4keyzCkclZeKdPe6oqQkfrsa/Nfa9Mab6rS
G37U0AuwoWAsOqNTeyK1FCfM1yLlH2qw/Fjrn1GehEr8baXp1A1FVBz8tthr8Yy5
inygixzpsb33FGOTN7+c+ggmb2f9iXO6uYeqcQ6Ku8fDf879/ar3GEBIL1a18/sm
PBKMkbvbBMHxcl+zdMULBoguAkOzVBc+Z2flbdl0By04JfvERGfhD52doU6rTxvq
KfC0V3h7cGD8IX0j51RwU38Nl2YlrGeOyDQ1SqId86odd2u72PPM21U6VVJBmewd
FR3W5TmhqFQoHKghHgg64zM3tHwkRg46KkorABEBAAG0H0RlY2lzZWx5IDxzdXBw
b3J0QGRlY2lzZWx5LmNvbT6JAU4EEwEIADgCGw8CHgECF4AWIQSG56Y7PilxwrkV
BFdrhl/2bILiUwUCX7hJHgULCQgHAwUVCgkICwUWAgMBAAAKCRBrhl/2bILiU7Fj
B/0UerzHPFUAJg1Ri8kcLKVU6HbquR3aww5+7UToPOmgXyBc+G/X6YHBWfQq5kJP
0QzZKxvQj5BZYOZOHP35J1WE/Gg2k3ySe8aM1p9CFxljjU6yI1NAYSEb2Z41TEhq
AkqM+k4ZvW2V2Yi3r1TgfT9UzfvLg0dApDgCDmoiN8HXHr/PuaNaLNUSXee7In3m
EMlMa3r4Dc3pSUacpK2YqQSZKvs+8LWrifPChKT++TRMNN72Waz2JucZJciM/p/q
rTc+wZvx0v0GOTx6dGyFHVNsXh6O60hb3SBY6euFhif9W61N3TQqrauewOlTwFfX
RaNbT4K2coFxzYkKjfv/7Ybq
=n3Fv
-----END PGP PUBLIC KEY BLOCK-----
SPACESHIP_VERSION=3.10.0
SPACESHIP_ROOT=/Users/alexk/.zsh/spaceship-prompt-async
NVM_DIR=/Users/alexk/.nvm
NVM_CD_FLAGS=-q
NVM_BIN=/Users/alexk/.nvm/versions/node/v14.18.1/bin
NVM_INC=/Users/alexk/.nvm/versions/node/v14.18.1/include/node
rvm_prefix=/Users/alexk
rvm_path=/Users/alexk/.rvm
rvm_bin_path=/Users/alexk/.rvm/bin
rvm_version=1.29.12 (latest)
GEM_HOME=/Users/alexk/.rvm/gems/ruby-3.0.3
GEM_PATH=/Users/alexk/.rvm/gems/ruby-3.0.3:/Users/alexk/.rvm/gems/ruby-3.0.3@global
MY_RUBY_HOME=/Users/alexk/.rvm/rubies/ruby-3.0.3
IRBRC=/Users/alexk/.rvm/rubies/ruby-3.0.3/.irbrc
RUBY_VERSION=ruby-3.0.3
rvm_alias_expanded=
rvm_bin_flag=
rvm_delete_flag=0
rvm_docs_type=
rvm_file_name=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_pretty_print_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_alias=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_sticky_flag=
rvm_system_flag=
rvm_use_flag=
rvm_user_flag=
rvm_ruby_string=ruby-3.0.3
LANG=en_US.UTF-8
```

Is is the multi-line private and public key in the env variable?

**Comment by mikayla-maki** [comment]
oh yeah, that’s it. Wild. Thanks for the context, we’ll update the parser for this :D

**Comment by mikayla-maki** [comment]
This should be fixed :)

**Comment by JosephTLyons** [comment]
I think this is being fast-tracked to today's release, v0.79.x!
