### ISSUE TITLE
support todo highlight

### ISSUE THREAD

**Issue by d1y** [zed-industries/community#1157]
### Check for existing issues

- [X] Completed

### Describe the feature

<img width="523" alt="image" src="https://user-images.githubusercontent.com/45585937/225674300-5d78aa64-cb14-4681-a5c5-5cabf45c5207.png">

**Comment by JosephTLyons** [comment]
Hey @d1y, just remembered we have an issue for this.  Can you upvote this one with a 👍?

- https://github.com/zed-industries/community/issues/833
