### ISSUE TITLE
Indicators in the file panel to quickly identify edited files

### ISSUE THREAD

**Issue by mypalvikram** [zed-industries/community#1160]
### Check for existing issues

- [X] Completed

### Describe the feature

There are indicators in the file panel on VS Code that allow developers to identify edited files and folders quickly.

### If applicable, add mockups / screenshots to help present your vision of the feature

<img width="371" alt="Screenshot 2023-03-16 at 9 44 19 AM" src="https://user-images.githubusercontent.com/6226652/225691685-e918513a-941f-4e88-bc79-2bd8e848cee4.png">

**Comment by mypalvikram** [comment]
> Hey @mypalvikram, are you wanting this to be based on the what has changed from git's perspective or via some other way?
> 
> If its the former, we have this issue here with a ton of upvotes (👍).
> 
> * [Git MVP integration (at least `git status` in the tree view) #29](https://github.com/zed-industries/community/issues/29)

My apologies, that's exactly the feature I was suggesting. Thanks for pointing that out!

**Comment by JosephTLyons** [comment]
No worries :)
