### ISSUE TITLE
Prompt user before setting Zed as default editor

### ISSUE THREAD

**Issue by jackbow** [zed-industries/community#1161]
### Check for existing issues

- [X] Completed

### Describe the feature

Upon installing it seems like Zed has made itself my default editor on macOS. It would've been nice if I'd been prompted because there doesn't seem to be an easy way to undo this.

**Comment by JosephTLyons** [comment]
We just landed some code on main that should prevent this from happening, but that won't land in stable for a few weeks.  I'm going to close this out - if it surfaces again in or after v0.79.x, feel free to reopen this.
