### ISSUE TITLE
Prettier Format on Save Does not Honor .prettierrc.json

### ISSUE THREAD

**Issue by crawfordleeds** [zed-industries/community#1162]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Following the configuration guide in the docs [here](https://docs.zed.dev/languages/javascript), I have found prettier on save to not honor the .prettierrc.json file in the root of the file. Whenever I run `prettier --write .` from the root of my project it seems to work. I can tell because we have `"tabWidth": 4` but saving the file within Zed is reverting back to the default `"tabWidth": 2`.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by crawfordleeds** [comment]
Looks like this was because I was working in .ts files and had configured just the `JavaScript` language override. adding the same format_on_save to `TypeScript` within `language_overrides` seems to have fixed the issue.

**Comment by farskid** [comment]
> Looks like this was because I was working in .ts files and had configured just the `JavaScript` language override. adding the same format_on_save to `TypeScript` within `language_overrides` seems to have fixed the issue.

I ran into the same issue with `TSX` requiring the same overrides as TypeScript and JavaScript. Since I work with languages that Prettier can format, I set the formatter option globally and stopped duplicating overrides per language.
```json
"format_on_save": "on",
  "formatter": {
    "external": {
      "command": "node_modules/.bin/prettier",
      "arguments": [
        "--stdin-filepath",
        "{buffer_path}"
      ]
    }
  }
```

**Comment by cezarneaga** [comment]
Hey everyone,

i am still having issues with this. Prettier config isnt being used.
i have
```
/** @type {import("prettier").Config} */
const config = {
   "embeddedLanguageFormatting": "auto",
  "htmlWhitespaceSensitivity": "css",
  "printWidth": 100,
  "proseWrap": "always",
  "quoteProps": "as-needed",
  "singleQuote": true,
  "tabWidth": 2,
  "trailingComma": "all",
  "plugins": ["prettier-plugin-tailwindcss"]
};

export default config;
```
inside root folder `.prettierrc.mjs`

and 
```
"format_on_save": {
    "external": {
      "command": "prettier",
      "arguments": [
        "--stdin-filepath",
        "{buffer_path}"
      ]
    }
  },
  ``` inside zed's conf
