### ISSUE TITLE
Configure project panel to not auto-focus opened files

### ISSUE THREAD

**Issue by adamdebono** [zed-industries/community#1166]
### Check for existing issues

- [X] Completed

### Describe the feature

When you focus a file in an editor through any means, it focuses that file in the project panel, by expanding the tree and scrolling to the item. I find this quite jarring, especially when I am quickly switching between open tabs.

I'm sure some people like this feature, so I think it would be great to have a configuration which can disable this.

**Comment by JosephTLyons** [comment]
Just linking this issue for internal organization - I realize it is not asking for the same thing:

https://github.com/zed-industries/community/issues/800

**Comment by xpader** [comment]
It's part of same thing.

**Comment by JosephTLyons** [comment]
> It's part of same thing.

Yeah, you're right, closing this one out in favor of:

- https://github.com/zed-industries/community/issues/800
