### ISSUE TITLE
Failed to deserialize Rust-Analyzer latest version response

### ISSUE THREAD

**Issue by ddprrt** [zed-industries/community#1178]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run on a fresh installation of Zed on Mac (downloaded today, March 17). When I try to open a Rust file or JSON file, I get the following error messages when the download of the language server fails:

```
Language server error: Rust

error deserializing latest release

Caused by:
    missing field `name` at line 1 column 279
```

Same with `Language server error: JSON`. Folders are created in `/Users/<myuser>/Library/Application Support/Zed/languages` but they remain empty

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by freedomlang** [comment]
Same here

**Comment by ddprrt** [comment]
Language servers that didn't fail to install/update:
- TypeScript
- YAML

**Comment by JosephTLyons** [comment]
Hey all, we are working to get these failed-to-install language server issues fixed.

**Comment by ForLoveOfCats** [comment]
I'm not quite sure what's going on here, I'll take a look soon but it doesn't seem to be the same issue as a bunch of other's which are being resolved very shortly
