### ISSUE TITLE
CLI: Add option to open file at specific line:column

### ISSUE THREAD

**Issue by porsager** [zed-industries/community#1184]
### Check for existing issues

- [X] Completed

### Describe the feature

To improve interoperability with other tools it would be great if the zed cli allowed opening a file at a specific line and column. This is implemented in every other editor.

Eg. sublime does it this way:

```
subl someFile.js:42:10
```

Which will open the file and position the cursor at line 42 column 10.

Semi related issues are:
https://github.com/zed-industries/community/issues/557
https://github.com/zed-industries/community/issues/560

**Comment by purpleclay** [comment]
I was just about to open this exact issue. I can see lots of use cases where the zed cli can be used alongside other workflows to open an editor with a specified set of files at specific line numbers and columns

**Comment by JosephTLyons** [comment]
Closing this out, as it will be available in v0.87.0.
