### ISSUE TITLE
Per-project/workspace configuration

### ISSUE THREAD

**Issue by norskeld** [zed-industries/community#1213]
### Check for existing issues

- [X] Completed

### Describe the feature

AFAIK Zed uses only one—global—config right now: `~/.config/zed/settings.json`. It would be great, if Zed supported something similar to what VS Code does: global config + per-project/workspace config that may override global settings via something like `<workspaceRoot>/.zed/settings.json`.

**Comment by JosephTLyons** [comment]
hey @norskeld - there's an older issue with a handful of upvotes here:

- https://github.com/zed-industries/community/issues/70

Would you mind upvoting it with a 👍 emoji?  Going to close this one out as a duplicate.  Thanks for the feedback :)

**Comment by norskeld** [comment]
Oh, damn, I did search for one, but somehow missed it. Sorry and thanks!
