### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by rad182** [zed-industries/community#1225]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Won't launch, tried to reinstall, reboot same.

### Environment

M1 Pro
Ventura 13.1

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://user-images.githubusercontent.com/71201/226222545-5f6c12e2-9dbf-407d-bed5-85aaf5afd0d2.png)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

no log file was generated

**Comment by JosephTLyons** [comment]
Hey @rad182, for some reason, Zed is not able to create the following directory:

~/.config/zed

What happens if you make that directory manually and try to reopen Zed?

**Comment by rad182** [comment]
@JosephTLyons that worked! thank you very much! for some reason my existing `.config` was own by root and I have no idea why
