### ISSUE TITLE
Add Zed Editor to Homebrew Casks?

### ISSUE THREAD

**Issue by arjpar** [zed-industries/community#1254]
### Check for existing issues

- [X] Completed

### Describe the feature

I wasn't able to find zed editor on homebrew. It would be useful to have it available on homebrew so we can install it via CLI.

**Comment by josser** [comment]
Homebrew don't like beta versions :( https://docs.brew.sh/Acceptable-Casks#stable-versions
but they have separate repository for them. 

Maybe we have to wait until stable release

**Comment by JosephTLyons** [comment]
There is a cask for this now:

https://formulae.brew.sh/cask/zed

Closing this out.

**Comment by arjpar** [comment]
@JosephTLyons Can't seem to install `zed` from Homebrew. I get this error:
```
Error: private method `download_name' called for #<Cask::Download:0x000000010c81cc90>
```

**Comment by JosephTLyons** [comment]
@arjpar 

I just fixed an error with the download endpoint tonight, but I'm not sure if it's related to your issue. Can you verify if its working on your end or still busted?

**Comment by hovsater** [comment]
I believe this was an upstream issue with Homebrew. Looks like https://github.com/Homebrew/brew/pull/15348 fixed it.

**Comment by arjpar** [comment]
@JosephTLyons Seems to work now. Thanks for the fix!
