### ISSUE TITLE
Python code completion requires system Node installation

### ISSUE THREAD

**Issue by az-hienas** [zed-industries/community#1265]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Code completion for python does not work. Haven't tried for other languages.

Followed the steps at:
https://docs.zed.dev/languages/python
but no luck.

If I access my code partner's session I get code completion on their side. 

I tried  "uninstalling" Zed removing Zed from Applications folder, when I reinstall again I am still logged in to GitHub, my initial chosen theme is still active. 

So I guess there are 2 issues:
1. no code completion for Python 
2. can't completely uninstall which might fix 1. 

Thank you

### Environment

Zed: v0.77.3 (stable)
OS: macOS 12.6.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/11031602/Zed.log)

**Comment by az-hienas** [comment]
I also looked at the `pyright` folder and it's empty

``` bash
kkwq480@rokxcd93g90fDD pyright % pwd
/Users/kkwq480/Library/Application Support/Zed/languages/pyright
kkwq480@rokxcd93g90fDD pyright % ls -lah
total 0
drwxr-xr-x  2 kkwq480  staff    64B Mar 21 20:20 .
drwxr-xr-x  3 kkwq480  staff    96B Mar 21 20:20 ..
```

I tried running the command `editor: restart language server`, but no luck.

**Comment by JosephTLyons** [comment]
Hey @az-hienas, when you start up Zed and open a python project, do you see a status message in the lower left-hand corner about the python language server being downloaded?  We've had some issues with language servers failing to download, and I'm wondering if that's the case here.

**Comment by az-hienas** [comment]
Hi @JosephTLyons 

I do get an error message in the lower left-hand corner, the message is:
`Failed to download Python language server. Click to show error.`

The detailed error is:
```
Language server error: Python

failed to run npm info

Caused by:
    No such file or directory (os error 2)
```

I don't have node / npm installed.

Thanks

**Comment by az-hienas** [comment]
It looks like from #1288 that the solution is to install node. 
I don't see node as a requirement in the docs. Will try to install and see if anything changes.

**Comment by diimdeep** [comment]
Installing node with brew or nvm didn't help.

```
Language server error: Python

failed to run npm info

Caused by:
    No such file or directory (os error 2)
```

zsh
nvm alias default v18
~/.nvm/versions/node/v18.15.0/bin/node
~/.nvm/versions/node/v18.15.0/bin/npm

npm@9.5.0 /usr/local/Cellar/node@18/18.15.0/lib/node_modules/npm

**Comment by JosephTLyons** [comment]
Hey all, just wanted to mention that a fix should be coming soon for language server bugs mentioning having npm issues.

**Comment by AravindhStanley** [comment]
Is having node an absolute requirement for this? I have no use for node from programming perspective.

**Comment by hovsater** [comment]
> Is having node an absolute requirement for this? I have no use for node from programming perspective.

Given that the language server itself is written in JavaScript the short answer is yes. The Zed team is working on shipping a bundled version of Node which would mean Node would be handled by Zed itself and no installation would be required on your part.

Until that has shipped, a proper Node installation is required.
