### ISSUE TITLE
rename in side panel doesn't take the letter 'h'

### ISSUE THREAD

**Issue by arte7** [zed-industries/community#1268]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hey not sure if this is the default setting,
when renaming a file or folder via right click in the panel (and click on rename) it is not possible to type the letter 'h'.
When hitting 'h' the folder with the file I tried to rename collapses.

### Environment

zed: Zed 0.77.3
macOS:  13.2.1 (22D68)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @arte7, are you using the Atom keymap?  If so, check out this issue:

- https://github.com/zed-industries/community/issues/1100

If this is what you are experiencing, would you mind closing this as a duplicate, but if you aren't using the Atom keymap, leave this open and we will dig into it.  Thank you.

**Comment by arte7** [comment]
Hey @JosephTLyons,
yes I'm using Atom keymap.
sorry I didn't find that other issue, will close this as duplicate.
