### ISSUE TITLE
wrap not working

### ISSUE THREAD

**Issue by jbrodriguez** [zed-industries/community#1272]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

set soft-wrap to none, both at a global and language level

open a file with long lines, it still wraps text at around 80 chars

![Screenshot 2023-03-22 at 07 37 49](https://user-images.githubusercontent.com/1305422/226906943-ac262497-c9d0-42ce-8e53-aae582b30261.png)

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

i do have an error about no worktree for path ? although i can  see the file is present at that location

``` log
2023-03-22T12:33:51 [INFO] Opening main db
2023-03-22T12:33:51 [ERROR] No worktree for path: "/Users/<redacted>/.config/zed/settings.json/"
2023-03-22T12:34:55 [WARN] request completed with error: failed to connect to the server
2023-03-22T12:34:55 [ERROR] failed to connect to the server

Caused by:
    [7] Couldn't connect to server
```

**Comment by JosephTLyons** [comment]
Hey @jbrodriguez, what happens if you remove these trailing commas?

<img width="393" alt="image" src="https://user-images.githubusercontent.com/19867440/227248079-866993d2-56f9-4e67-8d0b-2f0d899e3001.png">

**Comment by JosephTLyons** [comment]
No worries @jbrodriguez - I think we have a problem with this errors being too hard to see.  I've had numerous issues like this myself and have noticed many others as having it as well.

**Comment by jbrodriguez** [comment]
i'm on zed preview, it's not an issue for me anymore
