### ISSUE TITLE
 Configurable Sidebar Position for Enhanced User Experience

### ISSUE THREAD

**Issue by mirho** [zed-industries/community#1287]
### Check for existing issues

- [X] Completed

### Describe the feature

I would like to suggest a user-friendly feature that I believe would further enhance the app experience for many users. Currently, the sidebar is displayed on the left side of the app interface. It would be wonderful if we could have the option to configure the sidebar position, allowing users to choose between the left or the right side based on their preference.

Thank you!

**Comment by Delapouite** [comment]
Duplicate of https://github.com/zed-industries/community/issues/287

**Comment by mirho** [comment]
Closing as there is an open issue for this https://github.com/zed-industries/community/issues/287
