### ISSUE TITLE
Language support for csharp/.net

### ISSUE THREAD

**Issue by victor-teles** [zed-industries/community#1303]
### Check for existing issues

- [X] Completed

### Language

csharp

### Tree Sitter parser link

https://github.com/tree-sitter/tree-sitter-c-sharp

### Language server link

https://github.com/OmniSharp/omnisharp-vscode

**Comment by JosephTLyons** [comment]
Appreciate the feedback @victor-teles.  There is an issue for this open with some upvotes already (👍), would you mind voting on that issue so we can keep everything in one place?  Thanks.

- https://github.com/zed-industries/community/issues/293
