### ISSUE TITLE
Custom font not being red

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1312]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed stopped reading custom fonts

### Environment

Zed: v0.78.1 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

The `~/Library/Logs/Zed/Zed.log` shows:
`[ERROR] No worktree for path: "/Users/paka/.config/zed/settings.json/"`
Based on above the pointer to default `json` is incorrect as if it was folder.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

`[ERROR] No worktree for path: "/Users/paka/.config/zed/settings.json/"`

**Comment by krstp** [comment]
Somewhat solved: trailing comma was present under setting `json`:
```
{
[...]
    "remove_trailing_whitespace_on_save": true,   // <--- trailing comma
}
```
Removal of end comma `,` solved the issue. I believe this should not be the reason why `settings.json` is not read.

**Comment by iamnbutler** [comment]
Unfortunately, trailing commas DO make JSON invalid. We should figure out how to be more lenient with this, but for now this is working as intended. 

Feel free to open an issue about this if there isn't one, or vote on one if there is.

**Comment by krstp** [comment]
Thanks @iamnbutler . As per your suggestion trailing comma "bug" submitted under #1322 .
