### ISSUE TITLE
Add Bash/Zsh syntax highlighting

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1313]
### Check for existing issues

- [X] Completed

### Describe the feature

Missing Bash/Zsh etc. syntax highlighting. Please add it.

**Comment by JosephTLyons** [comment]
Hey @krstp, would you mind upvoting this issue with a 👍?

- https://github.com/zed-industries/community/issues/86

Going to close this as a duplicate.  Appreciate your feedback.
