### ISSUE TITLE
Drag'n'drop file to Zed window

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1317]
### Check for existing issues

- [X] Completed

### Describe the feature

As in the topic, this is request for a drag'n'drop files into Zed window. Currently I can drop the file on the app icon, which will open the file, but dropping on-top of the Zed window does nothing. Also drop in particular tab should also allow for a file open in this particular tab.

Thanks for great product and all the team hard work!

**Comment by krstp** [comment]
As of today, version `0.79.1` the drag'n'drop to icon stopped working the way it was working, now opening file in stand-alone window instead of existing tab. Just providing this input for more insight.

**Comment by kwando** [comment]
Observed some of my colleagues struggle with this yesterday. I have mostly worked around it myself though :)

They tried to move a file from a Finder window into a project folder, which works in their usual editor of choice vs *ode.

**Comment by JosephTLyons** [comment]
Just to bring others up to speed - we have a working prototype of this in our codebase, but its not fully complete and we will need to finish off our port to GPUI2 and moving to open source before we fully implement it.  That being said, its something we should be able to land, relatively easily, after those blockers are out of the way.

**Comment by JosephTLyons** [comment]
This is implemented in [v0.119.4 preview](https://zed.dev/releases/preview/0.119.4).

**Comment by krstp** [comment]
Thank you much, it is a work facilitator indeed. One more note though at it seems closely related, I cannot find the ticket now, except https://github.com/zed-industries/community/issues/957, which mentions in the comments drag and dropping panes between separate windows.

**Comment by danielneubert** [comment]
Hi there, have a very similar bug that may be tied to this one.

Opening a file with Zed always creates a new window. This is also the case for the [v0.119.4 preview](https://zed.dev/releases/preview/0.119.4).

Example use case for me is editing some config files via Finder or Transmit (FTP client) via "Open with" results always in an new window. I'd rather have a new tab attaching to the existing window.
