### ISSUE TITLE
Select all occurrences of string find and replace with new string

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1318]
### Check for existing issues

- [X] Completed

### Describe the feature

Ability to select ALL OCCURRENCES of a given string and replace all with a new string.

### If applicable, add mockups / screenshots to help present your vision of the feature

![custom_syntax_highlighting](https://user-images.githubusercontent.com/4711498/228724536-59f38d42-dcf8-4504-9471-4dd39b738bef.png)

_No response_

**Comment by JosephTLyons** [comment]
Hey @krstp, just curious, are you looking for more of a traditional `replace`, as in `Find and Replace`, or are you looking for a command similar to `editor: select next`, that adds in multiple cursors, but for all occurrences in the current buffer?

**Comment by krstp** [comment]
Rather select ALL instances (at the same time) such as `<string>` and as it selects I can type and replace the string. Currently there is F2 "Rename symbol", but it does not apply to custom string selection. I hope this clarifies, let me know.

**Comment by jallen92** [comment]
I would also love a `Find and Replace` feature. Just ran into a use case where I was sorely missing it while editing a Markdown file. Something like the `F2` Rename Symbol feature would be fine with me if it worked for any string. Traditional `Find and Replace` is fine by me too, but I'm not picky since this is infrequent but painful when needed and lacking.

**Comment by krstp** [comment]
Either way seems similar to #75

**Comment by HananoshikaYomaru** [comment]
this feature is a must for a text editor!!

**Comment by krstp** [comment]
A somewhat workaround and maybe something that could be leverage to bigger scale is to use F2 at the moment. It will work for a lot of definitions such as objects, but whenever there is `Docstring` or just a `String` to replace F2 will not recognize it, so... yes one can use for now F2, but its usage will be limited. Yeah, I am really longing for all-around find-replace.

**Comment by krstp** [comment]
Another workaround I have just notice is pointed out here: #75 . Hold `CMD+D` so it selects all instances. After all of them are selected (at times it can take some time) one can type to replace.

**Comment by iamvoidcoder** [comment]
+1 for this (and +1 for classic Find and Replace too)

**Comment by hoomp3** [comment]
another +1 for both of the above

**Comment by krstp** [comment]
I think we already started somewhat having this in latest releases, or maybe only in preview. When you search for a "string", then use "option+enter" it will select all instances. Thank you ZED team for implementing!

**Comment by anvox** [comment]
+1 for (Search and) replace. But trying with `option+enter`, seems it's more fun than the old way 🤩
