### ISSUE TITLE
Lint and format files on save

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1355]
### Check for existing issues

- [X] Completed

### Describe the feature

Files upon save should have an option to be formatted and linted to the tools of choice (installed within current system).

**Comment by hovsater** [comment]
[Formatting on save](https://docs.zed.dev/configuration/configuring-zed#format-on-save) already exist and is powered by the implementation of the specific language server. Some language servers allow you to customize what tool to use for formatting. Linting/diagnostics is also powered by the language server. I believe (don't take my word for it) that Zed currently support diagnostics [published](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics) by the language server itself. I.e., the language server informs Zed about any relevant issues. 

A more recent addition to the language server specification is [pull diagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_pullDiagnostics) in which the relationship  is reversed. Instead, Zed would ask the language server for diagnostics at its own discretion. I don't believe this is supported right now, but most likely will be in the future.

**Comment by krstp** [comment]
Correct it does, not sure why it missed my attention. Now I recall it would show linting issue... nonetheless when trying to add external formatter such as `black` for Python, it fails 🤔

**Comment by krstp** [comment]
Also a selector would be helpful here, such as:
![Vi5UO](https://user-images.githubusercontent.com/4711498/230212111-00c51504-3f29-47fb-a235-1757365642dc.png)

**Comment by JosephTLyons** [comment]
Hey @krstp, try this snippet

```json
"Python": {
  "format_on_save": {
    "external": {
      "command": "black",
      "arguments": [
        "-"
      ]
    }
  }
},
```

**Comment by hovsater** [comment]
To follow up on what @JosephTLyons wrote, the `-` argument informs black to read from standard input. Thus, no file reference is needed. 🙂

**Comment by krstp** [comment]
Thank you to both of you, `-` is what I was looking for trying `%` and `$` arguments etc.

Nonetheless, I did try `-` trying to use it two ways, through:
- `formatter` key with `external` ([link](https://docs.zed.dev/configuration/configuring-zed#formatter))
- adding `Python` block within the `language_overrides` block ([link](https://docs.zed.dev/configuration/configuring-zed#language-overrides))

Just for the kicks to make sure I tried all the options, I tried to use it as standalone block. None of the above options worked 😞 For reference here is the block I used:
![black_formatting](https://user-images.githubusercontent.com/4711498/230394979-c2f9ef09-cb35-4208-be12-e08b90cd8d26.png)
BTW: Per your above comments, I didn't know `format_on_save` can be used with `external` as well. Good to know `external` can be used with other keys as well on top of `formatting`.

**Comment by krstp** [comment]
Also checking logs, for one of the setups at start there is just single log such as this:
```
2023-04-06T13:31:32 [INFO] ========== starting zed ==========
2023-04-06T13:31:32 [INFO] Opening main db
2023-04-06T13:31:32 [INFO] Opening main db
2023-04-06T13:31:32 [INFO] open paths ["/Users/<user_path>"]
2023-04-06T13:31:32 [INFO] set status on client 0: Authenticating
2023-04-06T13:31:32 [INFO] set status on client 0: Connecting
2023-04-06T13:31:32 [INFO] Opening main db
2023-04-06T13:31:32 [INFO] Opening main db
2023-04-06T13:31:33 [ERROR] No worktree for path: "/Users/<user>/.config/zed/settings.json/"
2023-04-06T13:31:33 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2023-04-06T13:31:33 [INFO] add connection to peer
2023-04-06T13:31:33 [INFO] waiting for server hello
2023-04-06T13:31:33 [INFO] got server hello
2023-04-06T13:31:33 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 47, id: 76993 })
2023-04-06T13:31:33 [INFO] set status on client 0: Connected { peer_id: PeerId { owner_id: 47, id: 76993 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2023-04-06T13:31:35 [ERROR] failed to format via external command "black"
```

**Comment by krstp** [comment]
Ah... wait. I realized the env ZED runs in shell did not have `black` installed. After `pip install black`, the black formatting works. Thanks all for help! Closing.

**Comment by krstp** [comment]
Side question: can one use multiple formatters such as in case of Python: `black` and `flake8`. Toying with it now, but seems it only accepts a single one.

**Comment by hovsater** [comment]
Multiple formatters are currently not supported.

**Comment by deHelden** [comment]
@hovsater 
I'm trying to sync zed with ESlint, so my JS configuration at .eslintrc would be used on save.
I'm trying something like 
```json
{
  "language_overrides": {
    "JavaScript": {
      "format_on_save": true,
      "formatter": {
        "external": {
          "command": "eslint",
          "arguments": [
            "--fix",
            "--stdin",
            "--stdin-filename",
            "{FILENAME}"
          ]
        }
      }
    }
  }
}
```

**Comment by alecmarcus** [comment]
```json
  "formatter": {
    "external": {
      "command": "node_modules/.bin/eslint",
      "arguments": ["{buffer_path}", "--fix"]
    }
  }
```
Works for me, though it is very slow (about 2 seconds), and I seem to have to save twice. 

I have eslint installed globally and as a project dependency.
