### ISSUE TITLE
How to turn off checking python imports?

### ISSUE THREAD

**Issue by igor-yusupov** [zed-industries/community#1357]
### Check for existing issues

- [X] Completed

### Language

Python

**Comment by hovsater** [comment]
Zed uses [pyright](https://microsoft.github.io/pyright) as the language server for Python. pyright can be configured using a `pyrightconfig.json` file in the root of your project. You can find the available configuration options that go in that file [here](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options).

I believe what you're looking after is `reportMissingImports`. It's default value is `true` but can easily be set to `false` using the configuration file. See this [sample configuration](https://microsoft.github.io/pyright/#/configuration?id=sample-config-file) for inspiration.

**Comment by igor-yusupov** [comment]
@hovsater it works, thank you!
