### ISSUE TITLE
A way (eg. ctrl/cmd+click) to follow links in markdown

### ISSUE THREAD

**Issue by yw662** [zed-industries/community#1358]
### Check for existing issues

- [X] Completed

### Describe the feature

There are often links to another file or directory in the project, or a web page in markdown file. Vscode allow you to follow these links with ctrl+click (and a single click in preview). It will open the file in a new tab, or open the directory in the sidebar, or  open the url in browser.

It would be handy if zed could support the same feature.

**Comment by JosephTLyons** [comment]
Hey @yw662, appreciate the feedback.  Once we integrate a language server for Markdown, we should get this feature out of the box.  That being said, I think I'll close this issue in favor of the issue for adding language server support to Markdown.  Would you mind upvoting that one?

- https://github.com/zed-industries/community/issues/454

Thanks
