### ISSUE TITLE
The generated path from "Copy Path" in Project Panel is wrong

### ISSUE THREAD

**Issue by hovsater** [zed-industries/community#1364]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The path generated by "Copy Path" in the project panel seem to include the root of the project as well. E.g., `<project>/relative/path/to/file.txt`.

### Environment

Zed: v0.80.5 (stable)
OS: macOS 13.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

See the attached video.

https://user-images.githubusercontent.com/503025/230308859-d65347e2-6081-4209-9146-f52cc395293f.mov

**Comment by JosephTLyons** [comment]
Looks like someone made that decision on purpose

```rust
fn copy_path(&mut self, _: &CopyPath, cx: &mut ViewContext<Self>) {
    if let Some((worktree, entry)) = self.selected_entry(cx) {
        let mut path = PathBuf::new();
        path.push(worktree.root_name());
        path.push(&entry.path);
        cx.write_to_clipboard(ClipboardItem::new(path.to_string_lossy().to_string()));
    }
}
```

... that being said, I'm a bit on the fence about it - not having a strong opinion either way.  Does this feel clearly wrong, or should there be some sort of setting to include / omit the root portion?

**Comment by hovsater** [comment]
I believe @iamnbutler already said it's a bug as per our discussion in Discord. I've never seen a relative path include the root of the project and most tools out there would not accept the path as it currently stands.

**Comment by JosephTLyons** [comment]
I think you are right - need to check with the team, but was is your opinion on the naming of these things?   Not sure these feel quite right, but not sure what to tweak.

<img width="427" alt="SCR-20230407-cmzj" src="https://user-images.githubusercontent.com/19867440/230549512-3b668be1-b906-4af2-a815-43828415e33b.png">

**Comment by JosephTLyons** [comment]
Also, how do these paths look?

<img width="946" alt="SCR-20230407-cnkn" src="https://user-images.githubusercontent.com/19867440/230549678-6f684b97-5b3c-4230-8de5-d2b37e4321eb.png">

**Comment by JosephTLyons** [comment]
Figured I'd also toss it into the command palette when the editor itself is focused too, not just when the project panel is focused:

<img width="634" alt="SCR-20230407-cnow" src="https://user-images.githubusercontent.com/19867440/230549743-15f47364-7993-4e04-a767-f78ee789a04a.png">

**Comment by hovsater** [comment]
@JosephTLyons I think you're spot on. 🙂 This is exactly what I would expect and I appreciate that you've added the actions to the command palette as well.

**Comment by JosephTLyons** [comment]
Do you have any suggestions for the default key bindings for these?

**Comment by JosephTLyons** [comment]
Also, looks like Pulsar (Atom) uses `Copy Full Path` and `Copy Project Path`

<img width="218" alt="SCR-20230407-csqw" src="https://user-images.githubusercontent.com/19867440/230551451-916a44a6-5af8-436e-a53c-24c5694911af.png">

**Comment by hovsater** [comment]
Good question. In Sublime Text, there's no default keybindings for these and I pretty much exclusively use the command palette to grab either the absolute or relative path.

In VSCode, it seems like these are the default keybindings within the project panel itself:

<img width="269" alt="Screenshot 2023-04-07 at 08 08 44" src="https://user-images.githubusercontent.com/503025/230551829-f7190a0f-fd31-46aa-add0-4140d39886e9.png">

and within the file itself, you can can use these shortcuts (revealed by right clicking the tab containing the file itself) to copy the paths:

![Uploading Screenshot 2023-04-07 at 08.09.49.png…]()
