### ISSUE TITLE
Detect language based on shebang

### ISSUE THREAD

**Issue by exalted** [zed-industries/community#1367]
### Check for existing issues

- [X] Completed

### Describe the feature

Now that we can manually set the language of any buffer, this is not a major issue, but still, I wish Zed was able to detect a file's language based on the [shebag](https://en.wikipedia.org/wiki/Shebang_(Unix)) on the first line. This would be nice for files without an extension.

```
Zed: v0.80.5 (stable)
OS: macOS 13.3.0
Memory: 64 GiB
Architecture: aarch64
```

**Comment by hovsater** [comment]
Zed now has the ability to detect syntax based on shebang interpreter directives. Currently for a select few. I'm going to close this one out. Feel free to open an issue for a specific shebang you'd like to support. 🙂

**Comment by exalted** [comment]
Thanks for the house keeping @hovsater . I appreciate you! 🙇
