### ISSUE TITLE
Language server failure: c++ (timeout)

### ISSUE THREAD

**Issue by cjlala** [zed-industries/community#1377]
### Check for existing issues

- [X] Completed

### Language

C++

### Misc notes

Dear developers,

I just want to ask is there a possible to download C++ language server by myself. Cause I always get the result of `[28] Timeout was reached`.

**Comment by TENX-S** [comment]
The is part of https://github.com/zed-industries/community/issues/887. There are two workarounds:

1. Download the server manually and unzip it to `$HOME/Library/Application Support/Zed/languages`:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/40336192/230531248-5b340761-c5ac-4743-9056-ecaea47a1297.png">

2. Delete the folder `languages/clangd`. Set the `http_proxy` in a terminal session and launch zed from there.

**Comment by JosephTLyons** [comment]
Super appreciate you mentioning the workaround here @TENX-S, would you have any interest in adding a `Share a Tip` forum post in our Discussions for this?

I'm also compiling a new list of issues surrounding language server download bugs, to give to the team, and I'll include the issue about adding an `http_proxy` setting.

**Comment by TENX-S** [comment]
> Super appreciate you mentioning the workaround here @TENX-S, would you have any interest in adding a `Share a Tip` forum post in our Discussions for this?
> 
> I'm also compiling a new list of issues surrounding language server download bugs, to give to the team, and I'll include the issue about adding an `http_proxy` setting.

Done. #1395

**Comment by JosephTLyons** [comment]
> > Super appreciate you mentioning the workaround here @TENX-S, would you have any interest in adding a `Share a Tip` forum post in our Discussions for this?
> > I'm also compiling a new list of issues surrounding language server download bugs, to give to the team, and I'll include the issue about adding an `http_proxy` setting.
> 
> Done. #1395

Thank you so much!  Hugely appreciated!

**Comment by cjlala** [comment]
Thanks for your help! It really helps a lot! 👍  @TENX-S

**Comment by hovsater** [comment]
I'll close this one out as it looks like we found a resolution. 🙂
