### ISSUE TITLE
Inlay Hint Support

### ISSUE THREAD

**Issue by Cupnfish** [zed-industries/community#138]
**Is your feature request related to a problem? Please describe.**
It's a lot easier to have this when I'm writing rust code in vscode. And it increases the efficiency of reading the code.

**Describe the solution you'd like**
Something like vscode would be nice: 
![vscode inlay hint](https://user-images.githubusercontent.com/13157904/169626384-4c3fc38c-93c7-4bb3-b2dc-486f6e84b73b.png)

**Describe alternatives you've considered**
[I'm not sure how difficult it would be to implement this, but there are definitions in the lsp documentation.](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint)

**Screenshots**
![inlay hints at the tail end](https://user-images.githubusercontent.com/23398472/124373902-10434480-dcb4-11eb-9649-4a74a9735d16.png)

**Comment by ChristopherBiscardi** [comment]
This would be nice to have for teaching as well, since it allows me to show the flow of types through the program all at the same time.

**Comment by JosephTLyons** [comment]
This feature alone makes such a massive difference, especially for individuals who are still beginners in some language.  Giving the editor some sort of mechanism to display type information sent by the language server, would be excellent.

**Comment by nathansobo** [comment]
I have always found these distracting because they can make lines pretty long, but I know they're quite popular. Curious about the second screenshot where they show at the end of the line. Wonder what the rule is for which type to show when there are multiple possibilities.

**Comment by JosephTLyons** [comment]
I've always felt these inlays were annoying, but that the value they added was worth the annoyance.  I wish there was a way to redesign hint inlays to be less annoying and still just as useful.

**Comment by iamnbutler** [comment]
We've talked about this a few times. I agree these are useful but am not sold on the visual approach used in VSCode/elsewhere. When I have some time to rev on design for this I'll add a discussion topic & link it here.

**Comment by Cupnfish** [comment]
> I have always found these distracting because they can make lines pretty long, but I know they're quite popular. Curious about the second screenshot where they show at the end of the line. Wonder what the rule is for which type to show when there are multiple possibilities.

The two images are different implementations of ide, so the display is different. Also this feature is optionally switched off, at least in vscode. @nathansobo

**Comment by WindSoilder** [comment]
Take a note message from discord: 

In vscode, inlay hints is annoying to me at first, but after vscode let us configure inlay hints behavior, everything becomes so cool 🙂
![img](https://user-images.githubusercontent.com/22256154/204451610-019154df-ac4b-4595-af72-a7d5b2db3498.png)

**Comment by SomeoneToIgnore** [comment]
One of the funny things related to the inlay hints impl in VSCode, is that there's a hardcoded debounce time for the hints, so they do not update frequently.

Yet, r-a is actually able to send back the hints update very fast, see old hints behavior in the video https://github.com/rust-lang/rust-analyzer/pull/8955#issue-899114939 , on the moment of `.insert` usage, the hint updates almost instantly. 
Zed can avoid debouncing too, to look blazingly fast, compared to VSCode in here too.

**Comment by bobosola** [comment]
Hard disagree with OP - I find inlay hints **reduce** Rust readability and introduce too much visual clutter. I turned them off in VS Code as soon as I found out how to. I realise this is very much a personal opinion thing though. I much prefer Zed's current method (as of March 23) of hover popovers - they have all the info you need without all the additional visual clutter. If you do introduce inlay hints, please include the option to hide them.

**Comment by senevr** [comment]
I'm in the middle of bobosola and the OP, supporting inlay hints but also adding options on when it should be visualised would be a killer feature for me, i currently use the "offUnlessPressed" option on VSCode which hides the inlay hints until i press Ctrl+Option, I would love to see this in Zed.

**Comment by assayire** [comment]
> I have always found these distracting because they can make lines pretty long, but I know they're quite popular. Curious about the second screenshot where they show at the end of the line. Wonder what the rule is for which type to show when there are multiple possibilities.

How can there be multiple possibilities? 🤔

Say you have multiple possibilities, the best is to drop hints for that line.

**Comment by SomeoneToIgnore** [comment]
Initial hints version will appear in Zed 0.94.x, so I'll close the issue: please open separate issues for the related bugs.

We plan to improve the hints further, and add dynamic features to them, similar to what VSCode does, but that will follow later.
