### ISSUE TITLE
Project Diagnostics errors result in Zombie indicator

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1381]
### Check for existing issues

- [X] Completed

### Describe the feature

After all the development windows are closed, where some of them were show _Project Diagnostics_ (PD) errors (say `7`), the _Project Diagnostic_ status bar icon indicator remains as zombie UI artifact showing the same old count (`7`). Even opening the new files (say error count `2`) with different errors does not update the PD errors indicator, which remains at `7`.

The only option to reset the counter is to close ZED and reopen.

### If applicable, add mockups / screenshots to help present your vision of the feature

![diagnostics](https://user-images.githubusercontent.com/4711498/230405072-3eb7d8ca-59ad-42a2-aceb-46a6471b5067.png)

**Comment by ls-ivan-kiselev** [comment]
Seems similar, indicator on the bottom left shows completely different number than if you open project diagnostics in a tab: 

<img width="547" alt="Screenshot 2023-04-26 at 10 46 49" src="https://user-images.githubusercontent.com/86964964/234522290-3e95cfc5-bc96-4d14-8a2c-2d28aa2076ff.png">

**Comment by krstp** [comment]
Correct, I experience the same... the refresh rate does not seem to be consistent... sometime it will update, sometimes not, surely restart helps, but still 🙄

**Comment by Raffo** [comment]
Same for me and it has been the single most annoying problem. When doing a refactor I can't rely on this indicator at all as it makes impossible to use zed for any serious coding.

**Comment by JosephTLyons** [comment]
I just wanted to chime in here to let you all know we know this is a huge problem.  We deal with it on the team a lot.  This has historically been a very hard problem to track down and figure out, which is why you haven't seen any progress on it.  I'll bring this up again in the next team meeting.

**Comment by JosephTLyons** [comment]
I somehow missed the fact that this is a duplicate, so to keep things tidy, I'm going to close in favor of the earlier one posted.  Please go upvote that issue / add any extra details in the comments.

- https://github.com/zed-industries/community/issues/1227
