### ISSUE TITLE
Code folding on multiple levels (also on open)

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1387]
### Check for existing issues

- [X] Completed

### Describe the feature

There are similar issues ( #250 , #657 , #667 ) that are closed, but they only provide partial solution.

What I would like to see is:
- ability to open a file with all blocks folder at particular (function) level
     - Sublime has nicely sorted it out where I can indicate level of choice, such as:
         -`CMD+K+0` - show full code
         -`CMD+K+1` - show folded to first/highest level
         -`CMD+K+2` - show folded to second level
         -`CMD+K+3` - show folded to third level

What would also be nice: any file upon opening could be displayed with all the blocks folded to given level of choice (this would be driven by fold config).

### If applicable, add mockups / screenshots to help present your vision of the feature

Fully unfolded code (`CMD+K+0`):

![0](https://user-images.githubusercontent.com/4711498/230470166-d3fa5104-07c0-4191-b295-955579cd8980.png)

First level (`CMD+K+1`):

![1](https://user-images.githubusercontent.com/4711498/230470229-b0d68d9a-1756-4381-8d2a-bc211d6099f6.png)

Second level (`CMD+K+2`):

![2](https://user-images.githubusercontent.com/4711498/230470278-25cc6550-7a9f-4d16-ac1f-116dfe6d97dc.png)

Third level (`CMD+K+3`) - in this sample case equivalent to `0`:

![3](https://user-images.githubusercontent.com/4711498/230470342-eebeb7b5-7e5e-4b91-9735-3156da767139.png)

**Comment by krstp** [comment]
the other piece we could have, which I guess with Zed is natural, is code folding such as in VIM: `zo`, `zO`, `zf`, `zF`

**Comment by JosephTLyons** [comment]
Hey @krstp, does this issue cover your needs?

- https://github.com/zed-industries/community/issues/667

**Comment by krstp** [comment]
Double checking, indeed it does. I thought it was closed. Thanks for reviewing. Long day.

**Comment by JosephTLyons** [comment]
No worries at all, I appreciate the effort you've been putting into giving us feedback!
