### ISSUE TITLE
Provide full path to the file under edit

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1389]
### Check for existing issues

- [X] Completed

### Describe the feature

Would be good to have CMD+SHIFT+P option and associated key-binding to provide and copy the path of the file under edit.

**Comment by JosephTLyons** [comment]
Hey @krstp, are you saying the command would copy the path into the system clipboard?

**Comment by krstp** [comment]
Correct

**Comment by krstp** [comment]
This is somewhat related to #1364 . Either way, would be nice to get copy path from edit file tab or simply from within the edit file as mentioned above from the keybaord shortcut

**Comment by JosephTLyons** [comment]
Yep, I landed the fix to allow copying of both the full and relative paths in the project panel:

<img width="464" alt="SCR-20230407-lfng" src="https://user-images.githubusercontent.com/19867440/230643672-c5d28aec-e693-4238-96cb-153f87584e9e.png">

... as well as in the command palette, when focused on the editor:

<img width="1253" alt="SCR-20230407-lfld" src="https://user-images.githubusercontent.com/19867440/230643648-6326974f-bb7f-4cba-b1a0-f8d9a0d1961b.png">

I think this should go out in v0.82.x.  I'll close this for now, but feel free to re-open if anything is bugged, once it goes out.

**Comment by krstp** [comment]
Just a side note, with current release v.0.80.5, the `CMD+OPTION+C` brings up for some reason search window:

![search](https://user-images.githubusercontent.com/4711498/230661213-522bff14-e86a-4c1f-8488-8be8b759549a.png)

double chekcing the _Default Key Bindings_ it shows the same:

![key_bindings](https://user-images.githubusercontent.com/4711498/230661406-6f02c8fd-ff26-4f25-942b-44c3ff2ec8a5.png)

I am sure you are aware of it since you already make/made it work for the upcoming release, but just double checking so it is fully functional.
