### ISSUE TITLE
Zed won't open

### ISSUE THREAD

**Issue by etep** [zed-industries/community#1419]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After downloading both Zed 0.80.5 and Zed 0.79.1 (just to be sure, I tried different versions) and installing (opening the .dmg file and dragging to Applications), Zed will not open. I have clicked through from the Applications gui and tried to open using the `zed` binary under `Applications/Zed.app/Contents/MacOS`. In the terminal, I see the following:

```
>RUST_BACKTRACE=full ./zed
thread 'main' panicked at 'could not create config path: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', crates/zed/src/main.rs:283:56
stack backtrace:
   0:        0x106be6bc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   1:        0x106c054b8 - core::fmt::write::hc60df9bae744c40c
   2:        0x106be0a68 - std::io::Write::write_fmt::h1c4129dfc94f7c33
   3:        0x106be69d8 - std::sys_common::backtrace::print::h34db077f1fa49c76
   4:        0x106be8530 - std::panicking::default_hook::{{closure}}::hff4fe3239c020cef
   5:        0x106be8288 - std::panicking::default_hook::hd2988fbcc86fdc46
   6:        0x106be8b54 - std::panicking::rust_panic_with_hook::h01730ad11d62092c
   7:        0x106be8974 - std::panicking::begin_panic_handler::{{closure}}::h30f454e305d4a708
   8:        0x106be702c - std::sys_common::backtrace::__rust_end_short_backtrace::hb7ff1894d55794a1
   9:        0x106be86d0 - _rust_begin_unwind
  10:        0x106d938c0 - core::panicking::panic_fmt::hf1070b3fc33229fa
  11:        0x106d93bf8 - core::result::unwrap_failed::h334387d5f1f555c1
  12:        0x104add188 - Zed::main::h3ede68c77edf0427
  13:        0x104aef790 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb0c48201b725886f
  14:        0x104ac56e0 - std::rt::lang_start::{{closure}}::h231bd61fbeca8b79
  15:        0x106bdaee0 - std::rt::lang_start_internal::h24d09c16ec322e75
  16:        0x104adf460 - _main
```

### Environment

New Apple M2 mac book pro. Cannot open zed, hence cannot run copy system specs from the command palette.

### If applicable, add mockups / screenshots to help explain present your vision of the feature

n/a

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
>cd ~/Library/Logs/Zed 
cd: no such file or directory: /Users/jps/Library/Logs/Zed
```

**Comment by maxbrunsfeld** [comment]
It looks like is failing to write to a file in your home directory (probably `/Users/jps`). We should tolerate that situation. I'm curious though - what is the output of the commands `whoami` and `echo $HOME` in your terminal? If that `$HOME` directory exists, what permissions do you  have set on it? Is it expected that Zed would be not allowed to write any files in it?

**Comment by etep** [comment]
Hi @maxbrunsfeld ,

Thank you for the reply. I wonder if there is a way to track down which file it can't open and why. Here are some replies to your inquiries:
```
jps@jps-mbp:~>whoami
jps
jps@jps-mbp:~>echo $HOME
/Users/jps
jps@jps-mbp:~>pwd -P
/Users/jps
```

```
jps@jps-mbp:/Users>ls -lah   
total 0
drwxr-xr-x   5 root  admin   160B Mar 29 14:35 .
drwxr-xr-x  20 root  wheel   640B Feb  9 01:39 ..
-rw-r--r--   1 root  wheel     0B Feb  9 01:39 .localized
drwxrwxrwt   3 root  wheel    96B Feb  9 02:36 Shared
drwxr-x---+ 31 jps   staff   992B Apr 10 11:34 jps
```

**Comment by hovsater** [comment]
@etep what is the output of the following commands?

```console
$ ls -ld ~/.config
$ ls -ld ~/Library
```

**Comment by etep** [comment]
Hi @hovsater -

Thanks for the reply. Here is what I see from those `ls` commands:
```
jps@jps-mbp:~>ls -ld ~/.config
drwxr-xr-x  3 root  staff  96 Apr  1 11:58 /Users/jps/.config
jps@jps-mbp:~>ls -ld ~/Library
drwx------@ 88 jps  staff  2816 Apr 14 10:07 /Users/jps/Library
```

**Comment by hovsater** [comment]
> Hi @hovsater -
> 
> Thanks for the reply. Here is what I see from those `ls` commands:
> 
> ```
> jps@jps-mbp:~>ls -ld ~/.config
> drwxr-xr-x  3 root  staff  96 Apr  1 11:58 /Users/jps/.config
> jps@jps-mbp:~>ls -ld ~/Library
> drwx------@ 88 jps  staff  2816 Apr 14 10:07 /Users/jps/Library
> ```

Thanks for that. It looks like your `.config` folder is owned by root. I have no idea how that happened. Could you please run the following command (you may be prompted to enter your password) and then check if it resolved your issue? 🙂 


```console
sudo chown -R $(whoami):staff ~/.config
```

**Comment by etep** [comment]
Hi @hovsater ,

Yes, and hmmm. Somehow I was just looking at the permission bits and did not even notice the ownership. Things are working now. Thank you for solving that puzzle.

**Comment by hovsater** [comment]
Glad I could help. 🙂

**Comment by ozkantatli** [comment]
thx it worked for me too

**Comment by absynce** [comment]
I helped a coworker, @ianmagalhaes, with a similar issue. Nothing indicated the error unless we ran from the terminal as mentioned by the OP. 

But instead of permission issues, `~/.config` was a file instead of a directory for some reason. 

Error on terminal:
```
thread 'main' panicked at 'could not create config path: Os { code: 20, kind: NotADirectory, message: "Not a directory" }', crates/zed/src/main.rs:350:56
```

Once we recreated `~/.config` as a directory, the app opened. 🎉
