### ISSUE TITLE
Go: How does one pass "gopls" settings options via Zed?

### ISSUE THREAD

**Issue by marwan-at-work** [zed-industries/community#1423]
### Check for existing issues

- [X] Completed

### Describe the feature

Since I can't see Zed's codebase just yet, I'm not sure if and how a user can pass the following options to the gopls editor: https://github.com/golang/tools/blob/master/gopls/doc/settings.md

It would be great to document and allow gopls options here https://docs.zed.dev/languages/go 

Thanks!

**Comment by hovsater** [comment]
Currently you can’t. Feel free to upvote https://github.com/zed-industries/community/issues/585 to make this happen. 🙂

**Comment by JosephTLyons** [comment]
Going to close this one out as a more specific request of the generalized one mentioned by @hovsater.  @marwan-at-work - feel free to upvote the other linked issue. 😄

**Comment by coooold** [comment]
gopls is not compatible with golang version before 1.16. try upgrading golang first, it works for me
