### ISSUE TITLE
Open releases notes in Zed instead of having to open in a browser

### ISSUE THREAD

**Issue by assayire** [zed-industries/community#1427]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great if Zed opens release notes / change log in Zed itself. A menu item - Release Notes, could be added under the Help menu in the menu bar so that we can read the release notes on demand.

Some editors like VS Code do it.

**Comment by hovsater** [comment]
There’s https://github.com/zed-industries/community/issues/924 already. Mind closing and upvoting that one instead? 🙂

**Comment by assayire** [comment]
Closing in lieu of #924
