### ISSUE TITLE
An option to put the 'Close tab' button on the left

### ISSUE THREAD

**Issue by adamsoutar** [zed-industries/community#144]
**Is your feature request related to a problem? Please describe.**

Close tab buttons in macOS are usually on the left of the tab. See: Safari and tabs in Finder.

**Describe the solution you'd like**

VS Code has `"workbench.editor.tabCloseButton": "left",` and Atom had https://atom.io/packages/close-on-left

It'd be great to get this feature in Zed, too. I imagine it'd be relatively simple to do, but not obvious as a feature that some people would want 😅 

**Describe alternatives you've considered**

We could wait until Zed has mature extension support and try to implement it via an extension, like with Atom. But it would be nice to have it built in like Visual Studio.

**Screenshots (side-by-side mockup)**

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/26578100/175612988-8180b3fe-438c-45c7-86a9-04fdc2f17d72.png">

**Comment by iamnbutler** [comment]
This is easy enough to add, but I'd like to see if there is a larger demand for this. (There is upcoming work on tabs as we start to add things like terminal that will use the left real estate more.) Do you tend to use the mouse to close tabs or `cmd+w`?

Honestly, I'm surprised I've never noticed this, I've been using macOS pretty much all my life and never really identified that close tends to be on the left. Thanks for the feedback.

**Comment by iamnbutler** [comment]
I think this is a reasonable argument. I can't say I've explored it before at all, but I'll take a look at it next time I'm working on the tab bar/tabs 🙂

**Comment by jbergstroem** [comment]
First day in beta, I'm mostly a cmd+w user but my brain has made me mis-click the close tab more times the last few hours than I would care to admit. +1 to choosing the alignment of the close button 😄

**Comment by probablykasper** [comment]
This was added in v0.96:
- https://github.com/zed-industries/community/issues/1760
```json
  "tabs": {
    "close_position": "left"
  },
```
