### ISSUE TITLE
JS/TS always use absolute import paths

### ISSUE THREAD

**Issue by posthardcode** [zed-industries/community#1451]
### Check for existing issues

- [X] Completed

### Describe the feature

For JavaScript/TypeScript files, Zed currently automatically adds an import when typing a variable name and pressing tab - which is awesome.

It also seems to respect `tsconfig` and use absolute import paths - but not always. If the module to be imported is at the same level, or a level above, relative paths are used.

Is there a way to force absolute paths to always be used? If not, is this on your roadmap?

Thanks!

**Comment by hovsater** [comment]
I'm not sure this is something Zed can address. Zed delegates most language-specific features to the specific language server. For JavaScript/TypeScript, it's [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server). Perhaps you could tweak it to your liking by adjusting `importModuleSpecifierPreference`. 🙂

**Comment by hovsater** [comment]
@posthardcode did you find a solution to your problem?

**Comment by reloadedhead** [comment]
@hovsater I did face the same problem, which in other IDEs e.g. VSCode setting the property you mentioned to `relative` does the job. However, on Zed, having 

```json
 "lsp": {
    "typescript-language-server": {
      "initialization_options": {
        "preferences": {
          "importModuleSpecifier": "relative"
        }
      }
    }
  }
```
on my `settings.json` apparently has no effect. Am I missing something here?

**Comment by hovsater** [comment]
@reloadedhead I'm pretty sure the key must be `importModuleSpecifierPreference` to work. At least judging by the [docs](https://github.com/typescript-language-server/typescript-language-server?tab=readme-ov-file#initializationoptions).

**Comment by reloadedhead** [comment]
@hovsater Indeed, my bad. Caffeine levels were low 😅 can confirm it works like a charm! Extremely happy with Zed :)
