### ISSUE TITLE
Vim keybindings can't go NextWordEnd in Chinese

### ISSUE THREAD

**Issue by genepg** [zed-industries/community#1454]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

https://user-images.githubusercontent.com/20477170/232964079-0b155dff-c567-49cb-a94a-677e0ecc63f9.mov

### Environment

![Screen Shot 2023-04-19 at 12 07 47](https://user-images.githubusercontent.com/20477170/232964636-a9f7f97c-1dd5-43a9-8ad4-6f45ea06b363.png)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by hovsater** [comment]
@genepg could you write out the Chinese characters that you're using in the video above? It will make it easier to reproduce. 🙂

**Comment by genepg** [comment]
@hovsater 
The example:

```js
console.log('愛上');
console.log('love');
```

**Comment by hovsater** [comment]
Thanks. I've been able to re-produce this now.

**Comment by ConradIrwin** [comment]
This specific issue seems to have been fixed at some point in the last 6 months, so closing for now.

Please do keep reporting these!
