### ISSUE TITLE
GitHub Copilot after "hide" disappears altogether + better login handling

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1460]
### Check for existing issues

- [X] Completed

### Describe the feature

Two issues:
- I would like to request better Copilot login handling, as such right now there is no good feedback except looking into Zed log, i.e.:
```
{
  "type": 2,
  "message": "Thank you for participating in the GitHub Copilot Technical Preview. Your extended access has ended.",
  "actions": [
    {
      "title": "Signup for GitHub Copilot"
    },
    {
      "title": "Dismiss"
    }
  ]
}
```
I recond there should be more explicit user feedback on login.

- second point, after right clicking (`bottom-right`) Copilot icon and selecting `HIDE`, the icon disappears all together. Even `CMD+SHIFT+P` does not find the copilot command as if it was gone from Zed.

Note: Zed restart does not help.

### If applicable, add mockups / screenshots to help present your vision of the feature

Zed: `v0.82.7` (stable)
OS: macOS `13.2.1`
Memory: `32 GiB`
Architecture: `x86_64`

After right-bottom Copilot HIDE icon, no `copilot` `CMD+SHIFT+P` command available anymore:
![copilot-gone](https://user-images.githubusercontent.com/4711498/233490297-710ff4e9-d767-4648-bdb7-83841fa9037e.png)

**Comment by mikayla-maki** [comment]
You can re-enable copilot by going into your settings and setting the ‘copilot’ feature to ‘on’

**Comment by mikayla-maki** [comment]
As for the login handling, could you give me the sequence of actions you took so I can identify the problem? :)

**Comment by iamnbutler** [comment]
FWIW, the hide action is basically "I never want to see this again".

This is a new thing we are exploring for tools. Feel free to share thoughts on the terminology.

**Comment by krstp** [comment]
- So re-enabling with `true` works, the icon returned back.
- as for the login handling, I just try to login either by command bar or via icon and nothing happens, all I get is this log message :( so not sure how to login yet... exploring.
- Hmm... "never want to see it again"... I see HIDE rather as HIDE icon, but not necessary setting given feature to `false` - this is my thought.

**Comment by krstp** [comment]
Not sure how this happened, but magically copilot works now... I guess it pulls it from git ssh config I guess 🤔

**Comment by mikayla-maki** [comment]
Huh, strange that it started working but didn't provide error messages. Can you show me the full text of the log line related to this problem? Glad it's working for you!

**Comment by mikayla-maki** [comment]
Gonna close this one since it's resolved, but I am still interested in the log contents :)

**Comment by krstp** [comment]
Regarding the message, the only message that got displayed is attached above. To the root of the problem, truly must have been missing subscription. However, some still... in future some more handling around it would be helpful, but is not critical.

In terms of HIDE... I would rather name it TURN OFF, because hide itself indicates it is just hidden not turned off ;) 

Either way, thanks for prompt support.

**Comment by mikayla-maki** [comment]
Actually, the part I want to see is the line just above the JSON blob, specifically the part that is underneath your command palette in the screenshot :). 

That said, yeah, I think we should probably change the name to 'Disable copilot integration'

**Comment by krstp** [comment]
Not having it anymore... but AFAIK there was nothing outstanding. Sorry.
