### ISSUE TITLE
ElixirLS not working

### ISSUE THREAD

**Issue by layeddie** [zed-industries/community#1468]
### Check for existing issues

- [X] Completed

### Language

Elixir

### Misc notes

Trying to configure elixir-ls

Its there but not working in the editor

~/Library/Application Support/Zed/languages/elixir-ls                                                                                                                          13:26:12
❯ ls
'elixir-ls_Release v0.14.3'

**Comment by hovsater** [comment]
@layeddie do you have Elixir installed locally? What does the following output on your machine:

```console
$ elixir --version
```

**Comment by layeddie** [comment]
Yes - elixir-ls is working in vscode and in helix
❯ elixir -v
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

**Comment by hovsater** [comment]
Interesting. I'm working on a Elixir project myself, and ElixirLS works just fine for me. Does the Zed log reveal anything of interest? You can check by pressing `⌘⇧P` and type `zed: open log`.

**Comment by layeddie** [comment]
Oh thats interesting. I know when I initially installed Zed it tried to pickup elixir-ls but then I briefly saw an error message which promptly dissappeared. Is there I key sequence I should be using when I place the cursor over and elixir function?
Have you got it working with Heex files too?

log shows a number of these errors - didnt want to paste the whole log here..

2023-04-22T11:21:15 [ERROR] lsp request failed

Caused by:
    Invalid Request
2023-04-22T11:22:40 [INFO] unhandled notification window/logMessage:
{
  "message": "Unmatched request: %{\"id\" => 30, \"jsonrpc\" => \"2.0\", \"method\" => \"textDocument/codeAction\", \"params\" => %{\"context\" => %{\"diagnostics\" => [], \"only\" => [\"\", \"quickfix\", \"refactor\", \"refactor.extract\", \"source\"]}, \"range\" => %{\"end\" => %{\"character\" => 25, \"line\" => 1}, \"start\" => %{\"character\" => 25, \"line\" => 1}}, \"textDocument\" => %{\"uri\" => \"file:///Users/elay14/projects/2023/examples/svelte_ph__lv_tw/lib/phovelte_web/live/page_live.ex\"}}}",
  "type": 2
}
2023-04-22T11:22:40 [ERROR] lsp request failed

Caused by:
    Invalid Request
2023-04-22T11:22:41 [INFO] unhandled notification window/logMessage:
{
  "message": "Unmatched request: %{\"id\" => 31, \"jsonrpc\" => \"2.0\", \"method\" => \"textDocument/codeAction\", \"params\" => %{\"context\" => %{\"diagnostics\" => [], \"only\" => [\"\", \"quickfix\", \"refactor\", \"refactor.extract\", \"source\"]}, \"range\" => %{\"end\" => %{\"character\" => 25, \"line\" => 1}, \"start\" => %{\"character\" => 25, \"line\" => 1}}, \"textDocument\" => %{\"uri\" => \"file:///Users/elay14/projects/2023/examples/svelte_ph__lv_tw/lib/phovelte_web/live/page_live.ex\"}}}",
  "type": 2
}
2023-04-22T11:22:41 [ERROR] lsp request failed

**Comment by layeddie** [comment]
Also gettting error messages like this - 

  "message": "Process #PID<0.1061.0> raised an exception\n** (File.Error) could not set current working directory to \"/Users/elay14/projects/2023/examples/svelte_ph__lv_tw/deps/floki\": no such file or directory\n    (elixir 1.14.3) lib/file.ex:1580: File.cd!/1\n    (elixir 1.14.3) lib/file.ex:1604: File.cd!/2\n    (language_server 0.14.3) lib/language_server/build.ex:83: anonymous fn/3 in ElixirLS.LanguageServer.Build.reload_project/0\n    (stdlib 4.0) maps.erl:411: :maps.fold_1/3\n    (language_server 0.14.3) lib/language_server/build.ex:81: ElixirLS.LanguageServer.Build.reload_project/0\n    (language_server 0.14.3) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3\n    (stdlib 4.0) timer.erl:235: :timer.tc/1\n    (language_server 0.14.3) lib/language_server/build.ex:14: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3",
  "type": 1
}
2023-04-22T11:20:56 [INFO] unhandled notification window/logMessage:
{
  "message": "Unmatched request: %{\"id\" => 2, \"jsonrpc\" => \"2.0\", \"method\" => \"textDocument/codeAction\", \"params\" => %{\"context\" => %{\"diagnostics\" => [], \"only\" => [\"\", \"quickfix\", \"refactor\", \"refactor.extract\", \"source\"]}, \"range\" => %{\"end\" => %{\"character\" => 9, \"line\" => 4}, \"start\" => %{\"character\" => 9, \"line\" => 4}}, \"textDocument\" => %{\"uri\" => \"file:///Users/elay14/projects/2023/examples/svelte_ph__lv_tw/lib/phovelte_web/live/page_live.ex\"}}}",
  "type": 2
}
2023-04-22T11:20:56 [ERROR] lsp request failed

**Comment by layeddie** [comment]
I have looked through the default settings file for working directory and LSP settings which are at the end of the default settings file.

 "working_directory": "current_project_directory",

   // Different settings for specific languages.
    "languages": {
        "Plain Text": {
            "soft_wrap": "preferred_line_length"
        },
        "Elixir": {
            "tab_size": 2
        },
        "Go": {
            "tab_size": 4,
            "hard_tabs": true
        },
        "Markdown": {
            "soft_wrap": "preferred_line_length"
        },
        "JavaScript": {
            "tab_size": 2
        },
        "TypeScript": {
            "tab_size": 2
        },
        "TSX": {
            "tab_size": 2
        },
        "YAML": {
            "tab_size": 2
        }
    },
    // LSP Specific settings.
    "lsp": {
        // Specify the LSP name as a key here.
        // As of 8/10/22, supported LSPs are:
        // pyright
        // gopls
        // rust-analyzer
        // typescript-language-server
        // vscode-json-languageserver
        // "rust-analyzer": {
        //     //These initialization options are merged into Zed's defaults
        //     "initialization_options": {
        //         "checkOnSave": {
        //             "command": "clippy"
        //         }
        //     }
        // }
    }
}

**Comment by layeddie** [comment]
Hi hovsater,
Its working now - I didnt do anything except change to try a few other elixir projects. Don't know why it didnt work on the example svelte project.. thanks for helping out

**Comment by hovsater** [comment]
Great that you got it working. 🙂

**Comment by layeddie** [comment]
Hello Kevin,

Have you managed to get ZED to recognise heex / leex files and HTML / CSS
files?
Although ElixirLS is working it is not as functional as it is in vscode.
It's slow to open.
Links to Hexdocs dont work and it has no colourized highlights of the code
snippets.
Any other useful setup you have for elixir would be useful too.
ZED certainly seems to use less memory than vscode
It's faster too.
Eddie

**Comment by hovsater** [comment]
> Have you managed to get ZED to recognise heex / leex files and HTML / CSS
files?

I suggest you keep an eye on #725 for everything Heex related.

> Although ElixirLS is working it is not as functional as it is in vscode. It's slow to open.

Would you mind expanding on this? What is slow? Opening the editor? Or did you mean something else?

> Links to Hexdocs dont work and it has no colourized highlights of the code
snippets.

Could give me an example of what you mean? 🙂

**Comment by layeddie** [comment]
_I suggest you keep an eye on https://github.com/zed-industries/community/issues/725 for everything Heex related._
Just read it - Do I need to install treesitter? Not clear to me how to do that...

_Would you mind expanding on this? What is slow? Opening the editor? Or did you mean something else?_
I mean elixirls is slow opening when I hover over a function - sometimes - not always..

Picture show vscode elixirls box definition colours on code samples and view in hexdocs in blue is an active link to hexdocs. In Zed this does not work and text is all the same colour.


![863CD15F-9B19-40C8-B52E-19D4C68D10F5](https://user-images.githubusercontent.com/26161952/234947980-7def3638-bfc1-4010-9e1c-6a400bff2b41.jpeg)

**Comment by hovsater** [comment]
> Just read it - Do I need to install treesitter? Not clear to me how to do that...

No. That's an issue regarding Heex support. Whenever the issue is closed, it should have landed in the latest version of Zed.

> I mean elixirls is slow opening when I hover over a function - sometimes - not always..

That sounds like an ElixirLS problem rather than a Zed problem.

> Picture show vscode elixirls box definition colours on code samples and view in hexdocs in blue is an active link to hexdocs. In Zed this does not work and text is all the same colour.

Yeah, I don't believe Zed does any parsing for documentation tooltips (yet). That could definitely be improved.
