### ISSUE TITLE
The download of rust-analyzer cannot continue after the download is interrupted

### ISSUE THREAD

**Issue by l1Dan** [zed-industries/community#1474]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The download of rust-analyzer cannot continue after the download is interrupted

### Environment

Zed: v0.82.8 (stable)
OS: macOS 12.6.5
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by hovsater** [comment]
Hey @l1Dan, would you mind trying the following steps:

1. Quit Zed completely.
2. In a terminal of your choice, run the following command
```console
$ rm -rf ~/Library/Application\ Support/Zed/languages/rust-analyzer
```
3. Re-open Zed.

Did that help?

**Comment by hovsater** [comment]
Glad it worked out. In the future, we can hopefully improve the experience so you won't end up in a bad state like this again. 🙂
