### ISSUE TITLE
Documentation Update: Document support for pyproject.toml file

### ISSUE THREAD

**Issue by jeff-phil** [zed-industries/community#1509]
On the [Python](https://docs.zed.dev/languages/python) language documentation, `pyproject.toml` is not mentioned for configuring pyright including `venv`.

Since `pyproject.toml` is supported, a quick note seems needed.

**Comment by hovsater** [comment]
Fixed in https://github.com/zed-industries/docs/commit/097f268e979b7687272ed2c43bb307082ba265f7.
