### ISSUE TITLE
[Shell] Support disable shell window when Zed launched

### ISSUE THREAD

**Issue by tiyee** [zed-industries/community#1522]
### Check for existing issues

- [X] Completed

### Describe the feature

I often use Zed just for a text editor,
It  is no need to  show the shell window.
I can do that by myself if it is necessary.

**Comment by krstp** [comment]
Similar issue: https://github.com/zed-industries/community/discussions/1386

**Comment by SomeoneToIgnore** [comment]
Zed stores terminal state now, and does not show it by deafult for newly opened files: https://github.com/zed-industries/community/discussions/1386#discussioncomment-6102367
