### ISSUE TITLE
Custom keyboard layout bug

### ISSUE THREAD

**Issue by TomPlanche** [zed-industries/community#1540]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I have a custom keyboard layout where 'alt-ù' is '{' and 'alt-`' is '}' and I can't type any curly brackets.

### Environment

MacBook Pro M2 Max 14" 64Go - Ventura 13.3.1 (a)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SogoCZE** [comment]
This issue is probably already reported here https://github.com/zed-industries/community/issues/772.
