### ISSUE TITLE
Option to toggle Git Annotation

### ISSUE THREAD

**Issue by Vynex** [zed-industries/community#1559]
### Check for existing issues

- [X] Completed

### Describe the feature

The option to see the Author and Commit details for the current line would be incredibly helpful. This can be shown in the Status Bar or at the end of the Current Line.

The GitLens Plugin in VS Code does a great job at this imo.

**Comment by hovsater** [comment]
There's an already open issue about this. See https://github.com/zed-industries/community/issues/1441. Closing
