### ISSUE TITLE
Command to recursively collapse all directories in project browser

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#158]

**Comment by rkusa** [comment]
Definitely something I also missed while solely using Zed for a whole day. The most common use-case for me is when I jumped to definition into a `node_modules` dependency, which opens the `node_modules` directory that is known to have a lot of directors. So scrolling up to find the root to collapse it takes a while.

VSCode as an example has a CMD+P command and a button in the sidebar. I personally don't care for the button, but would very much like the command:
![Screenshot 2022-07-21 at 14 34 55](https://user-images.githubusercontent.com/409021/180215120-0a32e14a-1731-444b-9353-2ba4ccddfaa1.png)
![Screenshot 2022-07-21 at 14 35 19](https://user-images.githubusercontent.com/409021/180215126-79ea43fb-8f8a-4ddc-9e1b-33b0dd6bfb1b.png)

**Comment by nathanael-ruf** [comment]
On a similar note: How about recursively collapsing all children when collapsing a dir (maybe with an option to turn this on or off)?

**Comment by JosephTLyons** [comment]
A PR just landed that adds a `project panel: collapse all entries` command and will be out in v0.98.

**Comment by jezikk** [comment]
@JosephTLyons  It's not available in 0.98.1 version:
<img width="594" alt="missing" src="https://github.com/zed-industries/community/assets/7671531/0136daf4-3991-45e2-a1af-4fe794e2304c">
