### ISSUE TITLE
Project Search always displays "No Results"

### ISSUE THREAD

**Issue by ognen** [zed-industries/community#1581]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Whenever I want to search within the project the window never displays any results, the "No Results" label shows up very quickly after pressing enter. One can notice the label switching to something else (probably "Searching") but in an instant reverts to "No Results". 

### Environment

Zed: v0.87.6 (stable)
OS: macOS 13.3.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1639" alt="Screenshot 2023-05-30 at 21 05 02" src="https://github.com/zed-industries/community/assets/48983/0430ab49-a3d4-424f-8478-e19a0f2a2d34">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/11604399/Zed.log)

**Comment by JosephTLyons** [comment]
Hey @ognen, will you check this issue and see if your current project is set up in the same way as this users?

- https://github.com/zed-industries/community/issues/780

**Comment by ognen** [comment]
Hmm, it does looked funny that the files are too grey, yes.  I manage my `$HOME` dir using git with the following `.gitignore`:

```
/**
!/.gitignore
!/.zprofile
!/.vscode
!/.config/
!.config/**
```
I.e. everything but the config files is set to ignored. 

The example in question is in `$HOME/Workspace/fp/new-ingresses` which is a git repo on its own with no .gitignore. 

I guess you shouldn't look for a .gitignore anywhere up from the currently opened project?

**Comment by ognen** [comment]
Yes, definitely the case with #780. Just tested with a project outside of my home folder and search works nicely.

**Comment by JosephTLyons** [comment]
I do think we need to offer some sort of flexibility here so that users can run Zed in this sort of setup.
