### ISSUE TITLE
0.88.3 crashes right at start

### ISSUE THREAD

**Issue by rsaccon** [zed-industries/community#1592]
I am on mac OS 11.7.7, here the backtrace:

(base) robertosaccon@Robertos-MBP MacOS % cd /Applications/Zed.app/Contents/MacOS
(base) robertosaccon@Robertos-MBP MacOS % ./zed                                  
{
  "thread": "main",
  "payload": "called `Result::unwrap()` on an `Err` value: could not find a non-empty font family matching one of the given names",
  "location_data": {
    "file": "crates/gpui/src/fonts.rs",
    "line": 301
  },
  "backtrace": [
    "   0: backtrace::capture::Backtrace::new",
    "   1: Zed::init_panic_hook::{{closure}}",
    "   2: std::panicking::rust_panic_with_hook",
    "   3: std::panicking::begin_panic_handler::{{closure}}",
    "   4: std::sys_common::backtrace::__rust_end_short_backtrace",
    "   5: _rust_begin_unwind",
    "   6: core::panicking::panic_fmt",
    "   7: core::result::unwrap_failed",
    "   8: std::thread::local::LocalKey<T>::with",
    "   9: <gpui::fonts::TextStyle as core::default::Default>::default",
    "  10: <theme::Theme as core::default::Default>::default",
    "  11: std::thread::local::LocalKey<T>::with",
    "  12: theme::theme_registry::ThemeRegistry::new",
    "  13: theme::init",
    "  14: core::ops::function::FnOnce::call_once{{vtable.shim}}",
    "  15: gpui::platform::mac::platform::did_finish_launching",
    "  16: <unknown>",
    "  17: <unknown>",
    "  18: <unknown>",
    "  19: <unknown>",
    "  20: <unknown>",
    "  21: <unknown>",
    "  22: <unknown>",
    "  23: <unknown>",
    "  24: <unknown>",
    "  25: <unknown>",
    "  26: <unknown>",
    "  27: <unknown>",
    "  28: <unknown>",
    "  29: <unknown>",
    "  30: <unknown>",
    "  31: <unknown>",
    "  32: <unknown>",
    "  33: <unknown>",
    "  34: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::run",
    "  35: gpui::app::App::run",
    "  36: Zed::main",
    "  37: std::sys_common::backtrace::__rust_begin_short_backtrace",
    "  38: std::rt::lang_start::{{closure}}",
    "  39: std::rt::lang_start_internal",
    "  40: _main",
    ""
  ]
}

**Comment by Emblaze** [comment]
Same here, with same OS version. @rsaccon are you running an Intel Mac too?

**Comment by Sparkenstein** [comment]
Same here, on m2. Tho I didn't get any logs. it's crashing downright

**Comment by Sameer2307** [comment]
I am using macOS 13.0 and having an intel macbook. Crashes right away for me too

**Comment by Sameer2307** [comment]
To fix it I have uninstalled Zed (Removed from Applications) and using brew I installed it
`brew install --cask zed`
Installs version 0.87.6 and works like a charm

**Comment by Gbuomprisco** [comment]
Same - crashing on a Macbook Air M2

**Comment by Hala2Madrid** [comment]
Same - crashing on a Macbook Air M1

**Comment by srikanth-wgl** [comment]
Crashing on MacBook Air 2017 running macOS 12.6.6

**Comment by hovsater** [comment]
I just wanted to let you know that the Zed team is looking into the crashes. In the meantime you could downgrade to [0.83.2](https://zed.dev/api/releases/stable/0.83.2/Zed.dmg).

**Comment by JosephTLyons** [comment]
Sorry about the busted build everyone.  As @hovsater said, we're looking into it.

**Comment by JosephTLyons** [comment]
Hey all, we just hit publish on v0.88.4.  Can you all download it and see if you can open Zed again?

**Comment by carojkov** [comment]
App unresponsive after start. No UI shows. Thanks for looking into this. 
```
Date/Time:        2023-06-01 08:41:52.138 -0700
End time:         2023-06-01 08:42:28.242 -0700
OS Version:       macOS 12.6.5 (Build 21G531)
Architecture:     x86_64h
Report Version:   35.1
Incident Identifier: D070ADE8-E25F-48F1-B750-86A8F79062EF

Data Source:      Stackshots
Shared Cache:     E0BE2D6E-28EF-33AB-8499-8D9D42337BE7 slid base address 0x7ff804394000, slide 0x4394000
Shared Cache:     57DB871C-A979-37D2-B7C1-B4A0600112B9 slid base address 0x7ff8040e3000, slide 0x40e3000

Command:          zed
Path:             /Applications/Zed.app/Contents/MacOS/zed
Identifier:       dev.zed.Zed
Version:          0.88.4 (20230601.145642)
Team ID:          MQ55VZLNZQ
Architecture:     x86_64
Parent:           launchd [1]
PID:              8813
Time Since Fork:  36s

Event:            hang
Duration:         36.10s
Duration Sampled: 1.10s (process was unresponsive for 35 seconds before sampling)
Steps:            11 (100ms sampling interval)

Hardware model:   Macmini7,1
Active cpus:      4
HW page size:     4096
VM page size:     4096

Time Awake Since Boot: 1638211s
Time Since Wake:  n/a (machine hasn't slept)

Fan speed:        1791 rpm
Total CPU Time:   0.432s (1368.4M cycles, 938.3M instructions, 1.46c/i)
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  98.13 GB/233.57 GB, low space threshold 3072 MB

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  11  start + 462 (dyld + 21806) [0x115e1852e]
  11  main + 44 (zed + 123964) [0x10506143c]
  11  std::rt::lang_start_internal::h733b9f59d292f4af + 784 (zed + 48069792) [0x107e1aca0]
  11  std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h70fc64fde041709a + 12 (zed + 494828) [0x1050bbcec]
  11  std::sys_common::backtrace::__rust_begin_short_backtrace::hf1f757012b4cb488 + 6 (zed + 129926) [0x105062b86]
  11  Zed::main::h48a59bea541690ce + 3681 (zed + 115345) [0x10505f291]
  11  gpui::app::App::run::h1575cbc2921946c8 + 197 (zed + 272197) [0x105085745]
  11  _$LT$gpui..platform..mac..platform..MacForegroundPlatform$u20$as$u20$gpui..platform..ForegroundPlatform$GT$::run::ha82b014a05e5ad09 + 335 (zed + 42941695) [0x107936cff]
  11  -[NSApplication run] + 586 (AppKit + 195801) [0x7ff8071a4cd9]
  11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 251434) [0x7ff8071b262a]
  11  _DPSNextEvent + 2036 (AppKit + 259010) [0x7ff8071b43c2]
  11  AEProcessAppleEvent + 54 (HIToolbox + 261346) [0x7ff80d43ace2]
  11  aeProcessAppleEvent + 419 (AE + 17183) [0x7ff80ae2c31f]
  11  ??? (AE + 44250) [0x7ff80ae32cda]
  11  ??? (AE + 46192) [0x7ff80ae33470]
  11  _NSAppleEventManagerGenericHandler + 80 (Foundation + 214422) [0x7ff8055ac596]
  11  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308 (Foundation + 214820) [0x7ff8055ac724]
  11  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665 (AppKit + 282000) [0x7ff8071b9d90]
  11  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541 (AppKit + 282940) [0x7ff8071ba13c]
  11  -[NSApplication _sendFinishLaunchingNotification] + 208 (AppKit + 292204) [0x7ff8071bc56c]
  11  -[NSApplication _postDidFinishNotification] + 305 (AppKit + 292894) [0x7ff8071bc81e]
  11  -[NSNotificationCenter postNotificationName:object:userInfo:] + 82 (Foundation + 38910) [0x7ff8055817fe]
  11  _CFXNotificationPost + 735 (CoreFoundation + 291784) [0x7ff8047433c8]
  11  _CFXRegistrationPost + 496 (CoreFoundation + 1125040) [0x7ff80480eab0]
  11  ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1125170) [0x7ff80480eb32]
  11  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 481084) [0x7ff80477173c]
  11  gpui::platform::mac::platform::did_finish_launching::h3208ee52aad5f575 + 147 (zed + 42960979) [0x10793b853]
  11  core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hf534abb966ccfcd2 + 756 (zed + 222468) [0x105079504]
  11  settings::settings_file::handle_settings_file_changes::h49a7f33614521b1e + 55 (zed + 37997079) [0x10747fa17]
  11  async_io::driver::block_on::h9cee42696902a8ca + 344 (zed + 37993336) [0x10747eb78]
  11  parking::Inner::park::h20d947b94d86abbc + 210 (zed + 46146114) [0x107c45242]
  11  std::sync::condvar::Condvar::wait::h0ab9c89f54776edb + 112 (zed + 46143984) [0x107c449f0]
  11  __psynch_cvwait + 10 (libsystem_kernel.dylib + 17370) [0x7ff80467b3da]
 *11  psynch_cvcontinue + 0 (pthread + 20825) [0xffffff800376d159]


Process:          zed (Zed) [8813] [unique pid 108302]
UUID:             C901A235-E767-3C4E-AD03-F79B5B74F3F1
Path:             /Applications/Zed.app/Contents/MacOS/zed
Identifier:       dev.zed.Zed
Version:          0.88.4 (20230601.145642)
Team ID:          MQ55VZLNZQ
Shared Cache:     E0BE2D6E-28EF-33AB-8499-8D9D42337BE7 slid base address 0x7ff804394000, slide 0x4394000
Architecture:     x86_64
Parent:           launchd [1]
UID:              501
Footprint:        40.75 MB
Time Since Fork:  36s
Num samples:      11 (1-11)
Note:             Unresponsive for 35 seconds before sampling
Note:             1 idle work queue thread omitted

  Thread 0x5749b0    DispatchQueue "com.apple.main-thread"(1)    Thread name "main"    11 samples (1-11)    priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [150], IO tier 0>
  11  start + 462 (dyld + 21806) [0x115e1852e] 1-11
    11  main + 44 (zed + 123964) [0x10506143c] 1-11
      11  std::rt::lang_start_internal::h733b9f59d292f4af + 784 (zed + 48069792) [0x107e1aca0] 1-11
        11  std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h70fc64fde041709a + 12 (zed + 494828) [0x1050bbcec] 1-11
          11  std::sys_common::backtrace::__rust_begin_short_backtrace::hf1f757012b4cb488 + 6 (zed + 129926) [0x105062b86] 1-11
            11  Zed::main::h48a59bea541690ce + 3681 (zed + 115345) [0x10505f291] 1-11
              11  gpui::app::App::run::h1575cbc2921946c8 + 197 (zed + 272197) [0x105085745] 1-11
                11  _$LT$gpui..platform..mac..platform..MacForegroundPlatform$u20$as$u20$gpui..platform..ForegroundPlatform$GT$::run::ha82b014a05e5ad09 + 335 (zed + 42941695) [0x107936cff] 1-11
                  11  -[NSApplication run] + 586 (AppKit + 195801) [0x7ff8071a4cd9] 1-11
                    11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 251434) [0x7ff8071b262a] 1-11
                      11  _DPSNextEvent + 2036 (AppKit + 259010) [0x7ff8071b43c2] 1-11
                        11  AEProcessAppleEvent + 54 (HIToolbox + 261346) [0x7ff80d43ace2] 1-11
                          11  aeProcessAppleEvent + 419 (AE + 17183) [0x7ff80ae2c31f] 1-11
                            11  ??? (AE + 44250) [0x7ff80ae32cda] 1-11
                              11  ??? (AE + 46192) [0x7ff80ae33470] 1-11
                                11  _NSAppleEventManagerGenericHandler + 80 (Foundation + 214422) [0x7ff8055ac596] 1-11
                                  11  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308 (Foundation + 214820) [0x7ff8055ac724] 1-11
                                    11  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665 (AppKit + 282000) [0x7ff8071b9d90] 1-11
                                      11  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541 (AppKit + 282940) [0x7ff8071ba13c] 1-11
                                        11  -[NSApplication _sendFinishLaunchingNotification] + 208 (AppKit + 292204) [0x7ff8071bc56c] 1-11
                                          11  -[NSApplication _postDidFinishNotification] + 305 (AppKit + 292894) [0x7ff8071bc81e] 1-11
                                            11  -[NSNotificationCenter postNotificationName:object:userInfo:] + 82 (Foundation + 38910) [0x7ff8055817fe] 1-11
                                              11  _CFXNotificationPost + 735 (CoreFoundation + 291784) [0x7ff8047433c8] 1-11
                                                11  _CFXRegistrationPost + 496 (CoreFoundation + 1125040) [0x7ff80480eab0] 1-11
                                                  11  ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1125170) [0x7ff80480eb32] 1-11
                                                    11  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 481084) [0x7ff80477173c] 1-11
                                                      11  gpui::platform::mac::platform::did_finish_launching::h3208ee52aad5f575 + 147 (zed + 42960979) [0x10793b853] 1-11
                                                        11  core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hf534abb966ccfcd2 + 756 (zed + 222468) [0x105079504] 1-11
                                                          11  settings::settings_file::handle_settings_file_changes::h49a7f33614521b1e + 55 (zed + 37997079) [0x10747fa17] 1-11
                                                            11  async_io::driver::block_on::h9cee42696902a8ca + 344 (zed + 37993336) [0x10747eb78] 1-11
                                                              11  parking::Inner::park::h20d947b94d86abbc + 210 (zed + 46146114) [0x107c45242] 1-11
                                                                11  std::sync::condvar::Condvar::wait::h0ab9c89f54776edb + 112 (zed + 46143984) [0x107c449f0] 1-11
                                                                  11  __psynch_cvwait + 10 (libsystem_kernel.dylib + 17370) [0x7ff80467b3da] 1-11
                                                                   *11  psynch_cvcontinue + 0 (pthread + 20825) [0xffffff800376d159] 1-11
\
```

**Comment by rsaccon** [comment]
For me now it works again with v0.88.4. Thanks guys for fixing the issue.

**Comment by gogocharli** [comment]
Thanks for the quick update! Unfortunately, v0.88.4 opens but also crashes on my system whenever I select a theme.
I'm on an M1 Pro chip with macOS 12.6.5.

**Comment by JosephTLyons** [comment]
> Thanks for the quick update! Unfortunately, v0.88.4 opens but also crashes on my system whenever I select a theme.
> I'm on an M1 Pro chip with macOS 12.6.5.

Do you have anything in the logs or a crash report?  Would you mind opening a new issue if so?

**Comment by JosephTLyons** [comment]
> 0.88.3 and 0.88.4 - App unresponsive after start. No UI shows. Thanks for looking into this.
> 
> ```
> Date/Time:        2023-06-01 08:41:52.138 -0700
> End time:         2023-06-01 08:42:28.242 -0700
> OS Version:       macOS 12.6.5 (Build 21G531)
> Architecture:     x86_64h
> Report Version:   35.1
> Incident Identifier: D070ADE8-E25F-48F1-B750-86A8F79062EF
> 
> Data Source:      Stackshots
> Shared Cache:     E0BE2D6E-28EF-33AB-8499-8D9D42337BE7 slid base address 0x7ff804394000, slide 0x4394000
> Shared Cache:     57DB871C-A979-37D2-B7C1-B4A0600112B9 slid base address 0x7ff8040e3000, slide 0x40e3000
> 
> Command:          zed
> Path:             /Applications/Zed.app/Contents/MacOS/zed
> Identifier:       dev.zed.Zed
> Version:          0.88.4 (20230601.145642)
> Team ID:          MQ55VZLNZQ
> Architecture:     x86_64
> Parent:           launchd [1]
> PID:              8813
> Time Since Fork:  36s
> 
> Event:            hang
> Duration:         36.10s
> Duration Sampled: 1.10s (process was unresponsive for 35 seconds before sampling)
> Steps:            11 (100ms sampling interval)
> 
> Hardware model:   Macmini7,1
> Active cpus:      4
> HW page size:     4096
> VM page size:     4096
> 
> Time Awake Since Boot: 1638211s
> Time Since Wake:  n/a (machine hasn't slept)
> 
> Fan speed:        1791 rpm
> Total CPU Time:   0.432s (1368.4M cycles, 938.3M instructions, 1.46c/i)
> Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
> Free disk space:  98.13 GB/233.57 GB, low space threshold 3072 MB
> 
> --------------------------------------------------
> Timeline format: stacks are sorted chronologically
> Use -i and -heavy to re-report with count sorting
> --------------------------------------------------
> 
> 
> Heaviest stack for the main thread of the target process:
>   11  start + 462 (dyld + 21806) [0x115e1852e]
>   11  main + 44 (zed + 123964) [0x10506143c]
>   11  std::rt::lang_start_internal::h733b9f59d292f4af + 784 (zed + 48069792) [0x107e1aca0]
>   11  std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h70fc64fde041709a + 12 (zed + 494828) [0x1050bbcec]
>   11  std::sys_common::backtrace::__rust_begin_short_backtrace::hf1f757012b4cb488 + 6 (zed + 129926) [0x105062b86]
>   11  Zed::main::h48a59bea541690ce + 3681 (zed + 115345) [0x10505f291]
>   11  gpui::app::App::run::h1575cbc2921946c8 + 197 (zed + 272197) [0x105085745]
>   11  _$LT$gpui..platform..mac..platform..MacForegroundPlatform$u20$as$u20$gpui..platform..ForegroundPlatform$GT$::run::ha82b014a05e5ad09 + 335 (zed + 42941695) [0x107936cff]
>   11  -[NSApplication run] + 586 (AppKit + 195801) [0x7ff8071a4cd9]
>   11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 251434) [0x7ff8071b262a]
>   11  _DPSNextEvent + 2036 (AppKit + 259010) [0x7ff8071b43c2]
>   11  AEProcessAppleEvent + 54 (HIToolbox + 261346) [0x7ff80d43ace2]
>   11  aeProcessAppleEvent + 419 (AE + 17183) [0x7ff80ae2c31f]
>   11  ??? (AE + 44250) [0x7ff80ae32cda]
>   11  ??? (AE + 46192) [0x7ff80ae33470]
>   11  _NSAppleEventManagerGenericHandler + 80 (Foundation + 214422) [0x7ff8055ac596]
>   11  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308 (Foundation + 214820) [0x7ff8055ac724]
>   11  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665 (AppKit + 282000) [0x7ff8071b9d90]
>   11  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541 (AppKit + 282940) [0x7ff8071ba13c]
>   11  -[NSApplication _sendFinishLaunchingNotification] + 208 (AppKit + 292204) [0x7ff8071bc56c]
>   11  -[NSApplication _postDidFinishNotification] + 305 (AppKit + 292894) [0x7ff8071bc81e]
>   11  -[NSNotificationCenter postNotificationName:object:userInfo:] + 82 (Foundation + 38910) [0x7ff8055817fe]
>   11  _CFXNotificationPost + 735 (CoreFoundation + 291784) [0x7ff8047433c8]
>   11  _CFXRegistrationPost + 496 (CoreFoundation + 1125040) [0x7ff80480eab0]
>   11  ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1125170) [0x7ff80480eb32]
>   11  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 481084) [0x7ff80477173c]
>   11  gpui::platform::mac::platform::did_finish_launching::h3208ee52aad5f575 + 147 (zed + 42960979) [0x10793b853]
>   11  core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hf534abb966ccfcd2 + 756 (zed + 222468) [0x105079504]
>   11  settings::settings_file::handle_settings_file_changes::h49a7f33614521b1e + 55 (zed + 37997079) [0x10747fa17]
>   11  async_io::driver::block_on::h9cee42696902a8ca + 344 (zed + 37993336) [0x10747eb78]
>   11  parking::Inner::park::h20d947b94d86abbc + 210 (zed + 46146114) [0x107c45242]
>   11  std::sync::condvar::Condvar::wait::h0ab9c89f54776edb + 112 (zed + 46143984) [0x107c449f0]
>   11  __psynch_cvwait + 10 (libsystem_kernel.dylib + 17370) [0x7ff80467b3da]
>  *11  psynch_cvcontinue + 0 (pthread + 20825) [0xffffff800376d159]
> 
> 
> Process:          zed (Zed) [8813] [unique pid 108302]
> UUID:             C901A235-E767-3C4E-AD03-F79B5B74F3F1
> Path:             /Applications/Zed.app/Contents/MacOS/zed
> Identifier:       dev.zed.Zed
> Version:          0.88.4 (20230601.145642)
> Team ID:          MQ55VZLNZQ
> Shared Cache:     E0BE2D6E-28EF-33AB-8499-8D9D42337BE7 slid base address 0x7ff804394000, slide 0x4394000
> Architecture:     x86_64
> Parent:           launchd [1]
> UID:              501
> Footprint:        40.75 MB
> Time Since Fork:  36s
> Num samples:      11 (1-11)
> Note:             Unresponsive for 35 seconds before sampling
> Note:             1 idle work queue thread omitted
> 
>   Thread 0x5749b0    DispatchQueue "com.apple.main-thread"(1)    Thread name "main"    11 samples (1-11)    priority 46 (base 46)
>   <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [150], IO tier 0>
>   11  start + 462 (dyld + 21806) [0x115e1852e] 1-11
>     11  main + 44 (zed + 123964) [0x10506143c] 1-11
>       11  std::rt::lang_start_internal::h733b9f59d292f4af + 784 (zed + 48069792) [0x107e1aca0] 1-11
>         11  std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h70fc64fde041709a + 12 (zed + 494828) [0x1050bbcec] 1-11
>           11  std::sys_common::backtrace::__rust_begin_short_backtrace::hf1f757012b4cb488 + 6 (zed + 129926) [0x105062b86] 1-11
>             11  Zed::main::h48a59bea541690ce + 3681 (zed + 115345) [0x10505f291] 1-11
>               11  gpui::app::App::run::h1575cbc2921946c8 + 197 (zed + 272197) [0x105085745] 1-11
>                 11  _$LT$gpui..platform..mac..platform..MacForegroundPlatform$u20$as$u20$gpui..platform..ForegroundPlatform$GT$::run::ha82b014a05e5ad09 + 335 (zed + 42941695) [0x107936cff] 1-11
>                   11  -[NSApplication run] + 586 (AppKit + 195801) [0x7ff8071a4cd9] 1-11
>                     11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 251434) [0x7ff8071b262a] 1-11
>                       11  _DPSNextEvent + 2036 (AppKit + 259010) [0x7ff8071b43c2] 1-11
>                         11  AEProcessAppleEvent + 54 (HIToolbox + 261346) [0x7ff80d43ace2] 1-11
>                           11  aeProcessAppleEvent + 419 (AE + 17183) [0x7ff80ae2c31f] 1-11
>                             11  ??? (AE + 44250) [0x7ff80ae32cda] 1-11
>                               11  ??? (AE + 46192) [0x7ff80ae33470] 1-11
>                                 11  _NSAppleEventManagerGenericHandler + 80 (Foundation + 214422) [0x7ff8055ac596] 1-11
>                                   11  -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 308 (Foundation + 214820) [0x7ff8055ac724] 1-11
>                                     11  -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 665 (AppKit + 282000) [0x7ff8071b9d90] 1-11
>                                       11  -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 541 (AppKit + 282940) [0x7ff8071ba13c] 1-11
>                                         11  -[NSApplication _sendFinishLaunchingNotification] + 208 (AppKit + 292204) [0x7ff8071bc56c] 1-11
>                                           11  -[NSApplication _postDidFinishNotification] + 305 (AppKit + 292894) [0x7ff8071bc81e] 1-11
>                                             11  -[NSNotificationCenter postNotificationName:object:userInfo:] + 82 (Foundation + 38910) [0x7ff8055817fe] 1-11
>                                               11  _CFXNotificationPost + 735 (CoreFoundation + 291784) [0x7ff8047433c8] 1-11
>                                                 11  _CFXRegistrationPost + 496 (CoreFoundation + 1125040) [0x7ff80480eab0] 1-11
>                                                   11  ___CFXRegistrationPost_block_invoke + 49 (CoreFoundation + 1125170) [0x7ff80480eb32] 1-11
>                                                     11  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 481084) [0x7ff80477173c] 1-11
>                                                       11  gpui::platform::mac::platform::did_finish_launching::h3208ee52aad5f575 + 147 (zed + 42960979) [0x10793b853] 1-11
>                                                         11  core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hf534abb966ccfcd2 + 756 (zed + 222468) [0x105079504] 1-11
>                                                           11  settings::settings_file::handle_settings_file_changes::h49a7f33614521b1e + 55 (zed + 37997079) [0x10747fa17] 1-11
>                                                             11  async_io::driver::block_on::h9cee42696902a8ca + 344 (zed + 37993336) [0x10747eb78] 1-11
>                                                               11  parking::Inner::park::h20d947b94d86abbc + 210 (zed + 46146114) [0x107c45242] 1-11
>                                                                 11  std::sync::condvar::Condvar::wait::h0ab9c89f54776edb + 112 (zed + 46143984) [0x107c449f0] 1-11
>                                                                   11  __psynch_cvwait + 10 (libsystem_kernel.dylib + 17370) [0x7ff80467b3da] 1-11
>                                                                    *11  psynch_cvcontinue + 0 (pthread + 20825) [0xffffff800376d159] 1-11
> \
> ```

This actually looks like this [other issue](https://github.com/zed-industries/community/issues/1590) were about to release a fix for.

**Comment by JosephTLyons** [comment]
I'm going to close this issue, as I think we fixed the issue specific to this.  If you run into a crash mentioning `could not find a non-empty font family matching one of the given` on v0.88.4 or higher, please re-open.
