### ISSUE TITLE
cmd+enter for Go To Definition

### ISSUE THREAD

**Issue by hibangun** [zed-industries/community#1608]
### Check for existing issues

- [X] Completed

### Describe the feature

Is it possible to change current f12 into cmd+enter?

I tried to add these in `keymap.json`, but doesn't work

```
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-enter": "editor::GoToDefinition"
    },
  },
  {
    "context": "Editor && mode == full",
    "bindings": {
      "cmd-enter": "editor::GoToDefinition"
    },
  }
]
```

**Comment by hovsater** [comment]
Hi! I tried adding the following binding myself and it seems to work just fine.

```json
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-enter": "editor::GoToDefinition"
    }
  }
]
```

Are you sure the binding isn't working? Perhaps the go-to-definition command just doesn't work in the scenario you're trying out?

**Comment by hibangun** [comment]
works well now, thanks to @liebkne 

> @hibangun Try removing those trailing `,`s.
