### ISSUE TITLE
No way to quickly hide and then show terminal *with it already focused*

### ISSUE THREAD

**Issue by wzxu** [zed-industries/community#1611]
### Check for existing issues

- [X] Completed

### Describe the feature

So I totally miss the simple, no fuss ctrl-` to quickly hide/show terminal in VS Code.

In Zed, ctrl-` creates a terminal when there's none, and toggles focus back and forth between panels when a terminal exists. Used to be, we can at least use shift-esc to hide/show terminal, but that's changed to maximizing panel with the new panel system too. 

Now, there's a new cmd-J to toggle the bottom panel, but with one glaring downside (not sure if bug or feature) — when toggled, it just shows up but doesn't gets focused! So I have to cmd-J and ctrl-` now in order to show the terminal and focus it. Total productivity killer. 

I think the most logical fix is to make bottom panel automatically focused when toggled? (Now that I think of it I should probably have filled this a bug instead of enhancement. Oh well.)

**Comment by mikayla-maki** [comment]
This seems right, I think maybe we can make the two actions (cmd-j, ctrl-`) identical then.

**Comment by liebkne** [comment]
Not really the same issue... 

I move the terminal quite a lot based on the window size.

I can use the same key to show/hide the terminal whether the terminal is placed bottom/right/expanded before the new panel system. Now I have to use different keys/commands to hide it.

**Comment by WindSoilder** [comment]
Yeah I think it'd be great to toggle and get focused within one key :-)

**Comment by wzxu** [comment]
So I found out that clicking the terminal button in the bottom toolbar works as expected, and the tooltip reveals that to get this behavior via keyboard, you need to:
- cmd+J to hide bottom panel
- cmd+` to focus terminal (no need to cmd+J to show bottom panel first)

Wish I could just toggle it with the same shortcut.

**Comment by zachdaniel** [comment]
Yeah, would love if I could get cmd+` to show (and focus) and hide the terminal, not toggle it focused/unfocused.

**Comment by WindSoilder** [comment]
I think it's fixed on v0.92.3, currently it works fine for me!

**Comment by mikayla-maki** [comment]
Good catch :D Yes, this should be fixed now.
