### ISSUE TITLE
Solarized Light disappeared after upgrade to 0.89.2

### ISSUE THREAD

**Issue by benregn** [zed-industries/community#1613]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After upgrading, the Solarized theme isn't available any more when I run the `theme selector: toggle` command palette action.

### Environment

Zed: v0.89.2 (stable)
OS: macOS 12.6.0
Memory: 32 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by mdogan** [comment]
`Solarized Dark` is there but `Light` version is not. This is what I see in settings:

<img width="1001" alt="Screenshot 2023-06-08 at 13 20 37" src="https://github.com/zed-industries/community/assets/1201712/36130dd3-d83f-4a78-b064-d62abe6e505e">

**Comment by laike9m** [comment]
+1

**Comment by JosephTLyons** [comment]
Hey all, I think this will be restored in our next release, v0.90.x.  Going to close this for now, but please reopen if its not in next week's release!
