### ISSUE TITLE
Unselect / Skip select

### ISSUE THREAD

**Issue by liebkne** [zed-industries/community#1630]
### Check for existing issues

- [X] Completed

### Describe the feature

Add commands to unselect/skip next/previous selection.

### If applicable, add mockups / screenshots to help present your vision of the feature

**Unselect**

![output](https://github.com/zed-industries/community/assets/5475262/a48d7702-a6e2-44a4-8a5a-f4becf2b9b98)

**Skip select**
![output](https://github.com/zed-industries/community/assets/5475262/04bb9ee2-a2d0-4a1f-b03a-66dbdd0ce551)

**Comment by hovsater** [comment]
Hey @liebkne. You can use `⌘+U` to undo a selection. `⌘+⇧+U` to redo a selection and `⌘+K D` to skip the current selection. Hopefully that helps! 🙂

**Comment by liebkne** [comment]
@hovsater Thanks for the information about undo. How about skipping?

**Comment by hovsater** [comment]
@liebkne like I said, use `⌘+K D` to skip a selection. That is, Press `⌘+K`, release and press `D`.

**Comment by liebkne** [comment]
@hovsater 😅 Sorry, I should read it more carefully.

**Comment by hovsater** [comment]
No worries. 🙂

**Comment by liebkne** [comment]
> Press and hold ⌘ and then press K followed by D.

I think that should be called <kbd>⌘-k</kbd> <kbd>⌘-d</kbd>, <kbd>⌘-k</kbd> <kbd>d</kbd> could be a little confusing since the default keymap looks like 

```
      "cmd-k cmd-d": [
        "editor::SelectNext",
        {
          "replace_newest": true
        }
      ],
```

**Comment by hovsater** [comment]
Both works. You can either press `⌘+K` followed by `⌘+D` or just hold `⌘` and then press `K` followed by `D`.

**Comment by liebkne** [comment]
Hi, I mean the way of writing up the key sequences, not the way how to press it.

>  and ⌘+K D to skip the current selection.

looks like press a `⌘+K`, release both then a `D`.

**Comment by hovsater** [comment]
Right. I actually think we do write them up as you expect. E.g., `⌘+K M` means press and release `⌘+K` followed by `M`. Sorry for the confusion. 🙂
