### ISSUE TITLE
Zed v0.90.2 displays a bright pink blank screen

### ISSUE THREAD

**Issue by Thorin0ak** [zed-industries/community#1640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I updated Zed to the latest version this morning, and now all I get is a bright pink screen. Menus seem functional, but I cannot see the command palette. Only the About popup seems to be working. Opening a previous project opens the same blank pink app.

### Environment

MBP M2 Max with Ventura 13.4. Zed is 0.90.2

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/community/assets/94575046/c7991090-c108-4547-b3b5-11f74b24da38)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

Log output when opening the log file itself:

2023-06-16T04:10:58 [ERROR] oneshot canceled
2023-06-16T04:10:58 [ERROR] oneshot canceled
2023-06-16T04:10:58 [ERROR] oneshot canceled

**Comment by Thorin0ak** [comment]
I manually installed v0.90.1 and it is working fine.

**Comment by JosephTLyons** [comment]
Woah, this I really weird. If you install 0.90.2 again, does it show up again? Just trying to see if it was some bugged install or if its always there, even after another install.

**Comment by Thorin0ak** [comment]
It works fine if doing another install, thanks!

**Comment by matthewgapp** [comment]
I just got this after downloading the latest. On m2 mac
