### ISSUE TITLE
Hide cursor when Zed is in the background

### ISSUE THREAD

**Issue by probablykasper** [zed-industries/community#1654]
### Check for existing issues

- [X] Completed

### Describe the feature

Zed currently shows the blinking cursor even when a different app is focused. Would be nice to hide the cursor, like other apps do

**Comment by JosephTLyons** [comment]
Hey @probablykasper, just recalled seeing this request not long ago and went and looked it up.  Going to close this one out in favor of that one.  Would you mind upvoting that one with a 👍? Thanks

- https://github.com/zed-industries/community/issues/1607

**Comment by probablykasper** [comment]
Of course, sorry for missing that one!
