### ISSUE TITLE
buffers scroll too far down

### ISSUE THREAD

**Issue by maddanio** [zed-industries/community#1672]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

when scrolling down in a buffer it scrolls until the last line is at the top. that seems rather useless to me. I often wanna quickly go to the bottom of the file, but with thed after flicking down I always have to move back up a bit to actually see anything

### Environment

Zed: v0.90.2 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by rkusa** [comment]
There are some - including me - that, when writing code, prefer to have the cursor close to the top of their monitor. This is why most editors allow to scroll past the end of the file. However, it might make sense to put it behind a preference (e.g. in Sublime Text the preference is called `scroll_past_end`).

**Comment by maddanio** [comment]
ok, yah, then at least such a preference would be really nice :)

**Comment by wzxu** [comment]
I believe this is covered by #1053. I've love the option too. Please give it a 👍!

**Comment by JosephTLyons** [comment]
Appreciate the feedback @maddanio - I think we will close this one in favor of #1053, like @wzxu mentioned, to keep the 👍 in one place.
