### ISSUE TITLE
In terminal window have the link to the line in error

### ISSUE THREAD

**Issue by nippotam** [zed-industries/community#1694]
### Check for existing issues

- [X] Completed

### Describe the feature

When there is an error raised in the terminal view (in python for example) have the link to the line in the program of the raised error

**Comment by JosephTLyons** [comment]
Hey @nippotam, I think this issue already covers what you are asking about. I'm going to close this one as a duplicate. Could you upvote the linked issue with a 👍 ?

- https://github.com/zed-industries/community/issues/560
