### ISSUE TITLE
Provide ability to disable assistant

### ISSUE THREAD

**Issue by mattbaker** [zed-industries/community#1711]
### Check for existing issues

- [X] Completed

### Describe the feature

I'm not really sure why I need to access ChatGPT from my editor, or why it makes sense to be embedded inside Zed at all. I don't plan to use it, it'd be nice if I could disable the feature the same way I can disable copilot. 

Curious in general how the assistant fits into Zed's strategy, is it intended to be a ChatGPT interface? It seems tacked on and I don't really understand why it's there. Right now the icon and the panel are just noise for me.

**Comment by JosephTLyons** [comment]
A setting has been added to remove the assistant panel button in v0.100.0.

**Comment by JosephTLyons** [comment]
> I’m running on 0.100.1 and I can’t find the setting nor anything referring to such a setting in the [settings documentation](https://docs.zed.dev/configuration/configuring-zed).

Sorry for not having docs for this - all of our docs are pretty outdated, haven't come up with a good plan to keep it in sync with new developments.  This should do the trick:

```json
  "assistant": {
    "button": false
  },
```

**Comment by Gaffen** [comment]
Is it also possible to override the keyboard shortcut that toggles the right pane? The icon is now gone for me, but every time I try to refresh my browser window too soon after context switching I return to the editor with a prompt for an OpenAI key I will never provide or have use for. Maybe this is a separate issue...

**Comment by JosephTLyons** [comment]
> Is it also possible to override the keyboard shortcut that toggles the right pane? The icon is now gone for me, but every time I try to refresh my browser window too soon after context switching I return to the editor with a prompt for an OpenAI key I will never provide or have use for. Maybe this is a separate issue...

Yep, slap this snippet in your `keymap.json` file:

```json
{
  "context": "Workspace",
  "bindings": {
    "cmd-r": null
  }
}
```

**Comment by Gaffen** [comment]
@JosephTLyons you have just improved my quality of life, thanks!
