### ISSUE TITLE
Incorrect code action implemented in rust

### ISSUE THREAD

**Issue by Utshaan** [zed-industries/community#1718]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running the 'Fill match arms' code action causes some unwanted outcome, as shown in the video attached below

### Environment

Zed: v0.92.3 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/69788046/fb6f4082-ad2a-4635-916f-b69eddfa50e6

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxbrunsfeld** [comment]
I'm pretty sure this is rust-analyzer getting confused by the macro, not Zed.

**Comment by Utshaan** [comment]
> I'm pretty sure this is rust-analyzer getting confused by the macro, not Zed. Does VS Code do something different with that code action?

Oh could be. I don't have VS Code, I'll get it setup and check

**Comment by SomeoneToIgnore** [comment]
Procmacro are the ones to blame, most probably, here's the corresponding r-a issue: https://github.com/rust-lang/rust-analyzer/issues/12938

**Comment by Utshaan** [comment]
Yes I think this is exactly the same issue. I'll keep an eye on that issue, thanks.
