### ISSUE TITLE
[Assistant] Change OpenAI key once the key is set

### ISSUE THREAD

**Issue by gokhanarkan** [zed-industries/community#1725]
### Check for existing issues

- [X] Completed

### Describe the feature

It came to my attention that this is not possible with the Assistant update. Or, perhaps, I couldn't find it!

**Comment by liebkne** [comment]
<img width="557" alt="image" src="https://github.com/zed-industries/community/assets/5475262/e8d29595-5d26-42a8-9e03-e8e5bafa61ae">

You need to run the command in the assistant pane.

**Comment by gokhanarkan** [comment]
> <img alt="image" width="557" src="https://user-images.githubusercontent.com/5475262/250562991-e8d29595-5d26-42a8-9e03-e8e5bafa61ae.png">
> You need to run the command in the assistant pane.

for some odd reason, I don't actually have those settings! here what I have:

<img width="596" alt="CleanShot 2023-07-04 at 12 48 42@2x" src="https://github.com/zed-industries/community/assets/5124654/219f8398-e62e-4057-a8e2-c42d824ab18a">

any idea why?

**Comment by mrkrupski** [comment]
@gokhanarkan You need to have input focus on the chat on the right sidebar.

**Comment by gokhanarkan** [comment]
@mrkrupski thanks!! this done the trick!
