### ISSUE TITLE
Make it possible to change the Syntax Highlighting from the Command Palette 

### ISSUE THREAD

**Issue by Kerollmops** [zed-industries/community#1729]
Changing the syntax highlighting directly from the command palette would be great. You can do that in Sublime Text, and it is a pleasure not to use the mouse to click at the bottom right. It could be under another sub-palette menu, but I would prefer to have it at level one (like ST).

**Comment by aexvir** [comment]
that's already possible
open the command palette via `cmd+shift+p` then type language selector and that will open a modal with all supported languages
the default shortcut is `cmd+k m` which you can replace with what feels more comfortable for you

**Comment by Kerollmops** [comment]
Thank you very much. Closing then 🙈
