### ISSUE TITLE
Vim keys disabled when auto-completion popup is active

### ISSUE THREAD

**Issue by FlorentCollin** [zed-industries/community#1746]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The Vim keys are deactivated when the completion popup is active after returning to normal mode. By pressing escape a second time, the popup is deactivated and the Vim keys start working again.

It's seems to be a regression because it worked in earlier versions.

See the video below for a visual explanation:

https://github.com/zed-industries/community/assets/44946845/9e962898-2161-4f46-b4ef-2091a0f99ff5

### Environment

Zed: v0.93.4 (stable)
OS: macOS 13.4.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
I believe this is now fixed (escape will first hide completions and leave you in insert mode, so you can't get into a state where the completion window is open in normal mode). Please let me know if you know otherwise.

**Comment by SpicyRicecaker** [comment]
I think it would be nice to have `esc` close out of insert mode immediately even when the auto-completion popup is visible. I'm currently writing Rust code, and if I do a quick edit like adding `as f64` to a number, the auto completion shows on the `f64` and I have to tap `esc` twice to leave even when I'm done typing, which feels inefficient.

The current behavior of the VSCodeVim extension in VSCode is just to close completion and exit insert mode immediately.

**Comment by ConradIrwin** [comment]
That makes sense to me, will change.

I'm also going to add some vim-specific keybindings for the various completion tools so that you can use `ctrl-x ctrl-z` to close the current completion menu. (`ctrl-x ctrl-o` for the zed completion menu, `ctrl-x ctrl-c` for co-pilot, `ctrl-x ctrl-l` for the LSP-powered refactoring menu, `ctrl-x ctrl-a` for the openAI assistant).
