### ISSUE TITLE
[Z-2421] Add ESLint documentation

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#1748]
We have [this comment](https://github.com/zed-industries/community/issues/340#issuecomment-1593294069) from this user mentioning that we need to support ESLint, to my knowledge, we do! I quickly realized that even I dont know how to set this up, so I think some quick documentation is necessary.

<sub>From [SyncLinear.com](https://synclinear.com) | [Z-2421](https://linear.app/zed-industries/issue/Z-2421/add-eslint-documentation)</sub>

**Comment by ijsnow** [comment]
Hi could you provide a link to the docs that completed this? I can't find them and the thread didn't solve my problems with eslint.

**Comment by ruiconti** [comment]
Ditto.
