### ISSUE TITLE
Custom key bindings are not presented in UI

### ISSUE THREAD

**Issue by jezikk** [zed-industries/community#1751]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

If You change default key bindings in project panel, the custom key bindings are not presented in context menu (default values are presented instead).
```
[
  {
    "context": "ProjectPanel",
    "bindings": {
      "enter": "project_panel::Rename"
    }
  }
]

```

### Environment

Zed: v0.93.4 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="961" alt="error" src="https://github.com/zed-industries/community/assets/7671531/6fa01a07-ae90-4ca6-b8e0-94f511878b5f">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by SomeoneToIgnore** [comment]
That should come with Zed 0.97

![image](https://github.com/zed-industries/zed/assets/2690773/cbf29eca-0fca-4aff-be50-810eb80fdcb5)
![image](https://github.com/zed-industries/zed/assets/2690773/330054eb-ba92-4c8f-862f-06f276cc262b)
