### ISSUE TITLE
Command pallette should preserve input or order by most recent commands

### ISSUE THREAD

**Issue by tychedelia** [zed-industries/community#1753]
### Check for existing issues

- [X] Completed

### Describe the feature

As a user, I'm exceptionally lazy, and want to format a bunch of files one by one, but I've forgotten the keybinding for format and refuse to learn it. I open a file, fuzzy search "format" and hit enter. However, when I click on a new file to format and open the command palette, I have to type "format" all over again, which is hard because I'm lazy. Ideally, the command palette would preserve the most recently entered text, so I can just spam it + enter on a bunch of different files. An alternative would be to include recent actions that could be navigated by arrow keys. See IntelliJ for prior art.

**Comment by nonameolsson** [comment]
This was actually one of the first things I noticed when I started to use Zed. I thought it was a bug, but now I understand that it is just a missing feature. 
Looking forward to this 👍🏻

**Comment by osiewicz** [comment]
Hey,
This was just released in stable 0.104.0. Feel free to reopen this issue if there are any problems. =)
