### ISSUE TITLE
Hope to support Vue syntax

### ISSUE THREAD

**Issue by xiyuan-code** [zed-industries/community#1757]
### Check for existing issues

- [ ] Completed

### Hope to support Vue syntax

I hope to support custom import extension of the 'Tree sitter' component。

#### Reference plugin:  
https://github.com/ikatyang/tree-sitter-vue

### If applicable, add mockups / screenshots to help present your vision of the feature

There are quite a few Vue users among web developers, and supporting Vue syntax can quickly promote it

**Comment by osiewicz** [comment]
See also: https://github.com/zed-industries/community/issues/335

**Comment by aexvir** [comment]
@xiyuan-code please upvote the issue linked by @osiewicz
I'll close this one to avoid unnecessary noise
