### ISSUE TITLE
Add command/shortcut to toggle inlay hints

### ISSUE THREAD

**Issue by liebkne** [zed-industries/community#1764]
### Check for existing issues

- [X] Completed

### Describe the feature

Add command/shortcut to toggle inlay hints.

**Comment by aexvir** [comment]
is that an action you'd perform often enough to justify adding a shortcut? 🤔 
neither vscode nor intellij based ides seem to have this option, although it's quickly accessible in intellij via the actions menu

**Comment by liebkne** [comment]
See https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints , although that's not a 'real toggle'.

I normally don't show inlay hints by default. But when I'm confused by the type system, I toggle the hints to make things clearer sometimes.

**Comment by domaschh** [comment]
I also think this would be a great addition to the editor

**Comment by SomeoneToIgnore** [comment]
`editor::ToggleInlayHints` comes with Zed 0.101 for this, along with a small panel to toggle it: 
![image](https://github.com/zed-industries/community/assets/2690773/26a025a0-8bf6-4be2-9f82-dab214629a59)
