### ISSUE TITLE
Large repositories take a while to appear in the sidebar

### ISSUE THREAD

**Issue by paperdave** [zed-industries/community#1770]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I am testing Zed out on Bun's codebase, which includes WebKit as a git submodule. When using Zed on that WebKit submodule, it doesnt

- Clone WebKit (this is a huge repo, sorry)
- Open it in Zed
- Click in the sidebar to find Source/JavaScriptCore
- Issue: it takes a solid few minutes for this dropdown to load. In the loading space, no files are visible.
<img width="346" alt="image" src="https://github.com/zed-industries/community/assets/24465214/9c23ae3a-7772-497b-b4c5-425c90b5418a">

- Click on Source/JavaScriptCore/builtins
- It repeats
<img width="340" alt="image" src="https://github.com/zed-industries/community/assets/24465214/49a517b6-1d24-46db-a8de-d15614084606">

### Environment

Zed: v0.94.4 (stable)
OS: macOS 13.4.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/12072847/Zed.log)

**Comment by paperdave** [comment]
as a followup, after 20 minutes since filing the issue and leaving Zed open, that `builtins` folder is still not loaded. cmd p doesn't find files in there (try `PromiseOperations.js`)

**Comment by paperdave** [comment]
I tried zed again with just the bun repo, quick to clone but still a little chunky.

[screen recording on youtube](https://youtu.be/lJRsETeJiHs)

```
git clone https://github.com/oven-sh/bun
cd bun
make init-submodules # this clones all BESIDES webkit
```

i dont have any clue on how zed works but my guess is something is being prioritized over loading the specific file the user requests to open, or reading the directory the user is specifically trying to load into; and indexing of every file ever is being done first and only after that can files be loaded/searched for. just a guess

hope that helps in any way possible.

**Comment by maxbrunsfeld** [comment]
Ok, there was a problem with the way that we were retrieving the git status of files. In repos like WebKit, where `git status` is super slow to run, our approach was very inefficient. Zed 0.97 will have a new approach to this. There is still a bit of a delay, when initially opening `WebKit` in zed (while we run the libgit2 equivalent of `git status`). But I believe after that initial delay, everything should be responsive.

We may follow up with further improvements, but I think the situation is much much better after this change.

**Comment by paperdave** [comment]
yeah that would do it. git is a nightmare in that repo haha. i'll check it out again later.
