### ISSUE TITLE
Vim mode fails to select last character of word. 

### ISSUE THREAD

**Issue by khalil-omer** [zed-industries/community#1796]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Repro:

1. `w` to go to first char of nextword. 
2. `v` to enter visual mode
3. `e` to go to end of current word
4. `s` to replace selection.

You'll see that the last character remains. 

### Environment

Zed: v0.95.2 (stable)
OS: macOS 13.1.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
cc: @ConradIrwin

**Comment by JosephTLyons** [comment]
This should be fixed in v0.100.x - please reopen if the issue persists.
