### ISSUE TITLE
In Find, "Select Previous/Next Match" with enter key is broken

### ISSUE THREAD

**Issue by wzxu** [zed-industries/community#1801]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I hit enter to "Select Next Match", focus goes from the search field into the editor area, so subsequent enters won't do search but inputs newlines in the editor. And shift-enter clears the search field instead of performing "Select Previous Match".

### Environment

Zed: v0.96.1 (preview)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks for the heads up @wzxu. We'll work to get this fixed and publish a new build!

**Comment by JosephTLyons** [comment]
This will be fixed in today's preview release (v0.96.2).
