### ISSUE TITLE
Split Pane is very small and not resizable

### ISSUE THREAD

**Issue by aarongeorge** [zed-industries/community#1803]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Split any pane in any direction and the resulting split is very tiny and non-resizable

### Environment

Zed: v0.95.2 (stable)
OS: macOS 13.4.1
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2023-07-22 at 02 07 16](https://github.com/zed-industries/community/assets/1924496/665295a4-ca82-441f-97cb-8188701344d8)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/12130453/Zed.log)

**Comment by JosephTLyons** [comment]
This one is pretty strange @aarongeorge.  I'm not able to reproduce it. Do you feel comfortable pasting in the content of your `settings.json` file?

**Comment by aarongeorge** [comment]
Yeah no worries @JosephTLyons

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
    "buffer_font_size": 15,
    "hard_tabs": true,
    "tab_size": 4,
    "theme": "Ayu Dark",
    "projects_online_by_default": false,
    "base_keymap": "SublimeText",
    "format_on_save": "on",
    "telemetry": {
        "diagnostics": false,
        "metrics": false
    },
    "project_panel": {
        "dock": "right",
        "git_status": true
    },
    "journal": {
        "hour_format": "hour12"
    },
    "active_pane_magnification": 200,
    "languages": {
        "JavaScript": {
            "tab_size": 4,
            "hard_tabs": true
        },
        "TypeScript": {
            "tab_size": 4,
            "hard_tabs": true
        },
        "HTML": {
            "tab_size": 4,
            "hard_tabs": true,
            "remove_trailing_whitespace_on_save": true,
            "show_whitespaces": "selection"
        }
    }
}
```

**Comment by aarongeorge** [comment]
Somehow active_pane_magnification has been set to 200. That immediately resolved the issue. Sorry for wasting any time.

**Comment by JosephTLyons** [comment]
No worries at all! That was actually my only theory for what was happening, wouldn't of had a clue what was going on if it wasn't related to that setting 🤣
