### ISSUE TITLE
PHP language server does not recognize variable

### ISSUE THREAD

**Issue by RemcoSmitsDev** [zed-industries/community#1820]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When you are typing `$` you will see a list of available variables that you can use, this works fine as far I can see. 
But autocompletion when you are typing is not working for variables.

**Example**:
When you have a variable `$firstName` and you type `$` you will see a list of variables including `$firstName`. You can press **tab** or **enter** to confirm the autocompletion.

But when you are typing `$` and see the list and don't see the variable that you want to use and type `$f` there is no autocompletion anymore. And when you remove `f` → `$` the autocompletion does not trigger to see all the available variables.

### Environment

Zed: v0.96.2 (preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/62463826/694c1e73-bc59-496c-9e37-062aa74c9b85

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
cc: @osiewicz

**Comment by osiewicz** [comment]
Hey, 
Thanks for reporting this issue :)
It looks like we did not recognise `$` as valid start of identifier, which messed with our PHP integration.

https://github.com/zed-industries/community/assets/24362066/d67cb0fe-d81e-4793-9cf2-17e94f7b9cfe

We are working on a fix that would also allow us to override characters on a language-by-language basis. If anything though, this fix should be a part of next week's Preview.

**Comment by osiewicz** [comment]
This is shipping into tomorrow's Preview. Thanks!

**Comment by RemcoSmitsDev** [comment]
@osiewicz You did a good job! Now I can rely on autocompletion and be lazy again.

**Comment by RemcoSmitsDev** [comment]
This is fixed in **0.101.0**
