### ISSUE TITLE
Module javascript file extensions

### ISSUE THREAD

**Issue by jezikk** [zed-industries/community#1822]
### Check for existing issues

- [X] Completed

### Describe the feature

The following file extensions should be associated to JavaScript by default:
- .mjs
- .cjs

Example:
- prettier.config.cjs

**Comment by JosephTLyons** [comment]
Hey @jezikk, we have a request to add a general system to allow users to define these mappings in their settings:

- https://github.com/zed-industries/community/issues/595
 
I think once that system is in place, we'd just need to provide some common defaults, like the ones you have above. I think that issue generically covers what you are asking for here, so I'll close this one out.

**Comment by JosephTLyons** [comment]
I went ahead and baked these into Zed - should be out in v0.100.x. If you have any more requests like this, drop them in over there:

- https://github.com/zed-industries/community/discussions/1917
