### ISSUE TITLE
Add a shortcut to toggle the ability of finding project files or all files

### ISSUE THREAD

**Issue by Yevgnen** [zed-industries/community#1843]
### Check for existing issues

- [X] Completed

### Describe the feature

The file finder does not support for finding non-project files. It would be nice to have a shortcut to enable and disable the ability of finding all files (hidden files like `.env` or other files) in the project.

**Comment by Yevgnen** [comment]
Well, I was wrong, it does support for finding all files. But some of them are ignored by `.gitignore`.

**Comment by JosephTLyons** [comment]
Yeah, that's a current limitation in Zed.  You can upvote any of these issues if you are looking to have some control over that:

- https://github.com/zed-industries/community/issues/1813
- https://github.com/zed-industries/community/issues/1538
- https://github.com/zed-industries/community/issues/70
