### ISSUE TITLE
Svelte - Receiving diagnostic message for reactive statements

### ISSUE THREAD

**Issue by jamauro** [zed-industries/community#1844]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm using a package that enables custom reactive statements that use the syntax `$m: ` instead of svelte's `$: `. For example:

```js
<script>
  // other code here
  $m: todos = Todos.find().fetch()
</script>

{#each todos as todo (todo._id)}
  <Todo {todo} />
{/each}
```

I see the diagnostic message "Could not find name 'todos'. Did you mean 'Todos'?"

Is there a way to prevent this diagnostic message from displaying since the syntax is valid?

Here's the message I hover over `$m`:
<img width="344" alt="Screenshot 2023-08-23 at 4 12 24 PM" src="https://github.com/zed-industries/community/assets/1749828/4811ffcd-6807-4e4a-b703-3404430b8848">

And here's what it looks like when I hover over `todos`:
<img width="506" alt="Screenshot 2023-08-23 at 4 11 57 PM" src="https://github.com/zed-industries/community/assets/1749828/aa64dae1-7357-40be-af4c-15483c7f3154">

### Environment

Zed: v0.96.3 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: aarch64

**Comment by jamauro** [comment]
@mikayla-maki Thanks for adding svelte support! Do you know of anything I can do on my end to resolve this issue? Maybe something in Zed settings? If not, can I provide a bribe to add a fix to Zed? :) I'm sure it's probably not a top priority but would greatly appreciate you taking a look.

**Comment by mikayla-maki** [comment]
Hi Jamauro, thanks for the laugh :)

What package are you using? And do you have a code snippet / repo I could use to reproduce the issue?

**Comment by jamauro** [comment]
Here's a quick repro: https://github.com/jamauro/zed-repro

I'm using https://github.com/zodern/melte. Here's some more info on the custom `$m` label it creates: https://github.com/zodern/melte#tracker-statements. Behind the scenes, it looks like it relies on [melte-complier](https://github.com/zodern/melte-compiler/tree/4fb95a1e84bb50249bf6d80acfc2e698ddd00826) to handle the `$m` label [here](https://github.com/zodern/melte-compiler/blob/4fb95a1e84bb50249bf6d80acfc2e698ddd00826/MelteCompiler.js#L343).

Thanks so much for taking a look!

**Comment by jamauro** [comment]
My guess is that this will eventually be solved when these Svelte-related packages migrate to Svelte 5.

If there’s a way to silence the diagnostic messages though, please let me know.
