### ISSUE TITLE
vim mode: support P (paste before)

### ISSUE THREAD

**Issue by networkhermit** [zed-industries/community#1869]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Currently zed vim mode support `p` but not `P` for pasting text, it's better to also support the paste before variant so it is consistent.

Related:
https://github.com/zed-industries/community/issues/469#issuecomment-1227458187

### Environment

Zed: v0.96.4 (stable)
OS: macOS 13.4.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
This should be fixed as of v0.101, please let me know if you see differently!
