### ISSUE TITLE
quick fix to import missed function in Rust

### ISSUE THREAD

**Issue by xudesheng** [zed-industries/community#1888]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode, when the cursor hovers over the function not in the current scope, a shortcut would be provided to import the missed scope.

<img width="676" alt="image" src="https://github.com/zed-industries/community/assets/8742037/cc5bf39d-f5c4-4bf7-a8ad-7a0cd2b53844">

But ZED doesn't have this shortcut:
<img width="563" alt="image" src="https://github.com/zed-industries/community/assets/8742037/040a79a5-3b5a-45a1-af1f-07d67f7fab74">

This shortcut is very helpful during Rust coding.

**Comment by JosephTLyons** [comment]
Hey @xudesheng, if you put your cursor somewhere in `channel`, you should see a lightning bolt show up in the gutter. If you click the lightning bolt, you'll get the code assists that the language server offers:

<img width="347" alt="SCR-20230806-buha" src="https://github.com/zed-industries/community/assets/19867440/d7cdec15-eedb-419e-8bca-006295695199">

You can also use the key binding `cmd-.` when the cursor is in the word `channel` to bring the code assist menu up.

Lastly, if you're typing the word `channel` out, the autocompletion menu should show up, and selecting the `channel` entry will automatically add the import:

<img width="731" alt="SCR-20230806-buzo" src="https://github.com/zed-industries/community/assets/19867440/f7119477-fdfc-4b23-b1a3-266b56fcbc38">

**Comment by xudesheng** [comment]
> Hey @xudesheng, if you put your cursor somewhere in `channel`, you should see a lightning bolt show up in the gutter. If you click the lightning bolt, you'll get the code assists that the language server offers:
> 
> <img alt="SCR-20230806-buha" width="347" src="https://user-images.githubusercontent.com/19867440/258622359-d7cdec15-eedb-419e-8bca-006295695199.png">
> You can also use the key binding `cmd-.` when the cursor is in the word `channel` to bring the code assist menu up.
> 
> Lastly, if you're typing the word `channel` out, the autocompletion menu should show up, and selecting the `channel` entry will automatically add the import:
> 
> <img alt="SCR-20230806-buzo" width="731" src="https://user-images.githubusercontent.com/19867440/258622412-f7119477-fdfc-4b23-b1a3-266b56fcbc38.png">
> Do these alternatives feel ok to you?

Thank you for your reply.
Both approaches work for me! I was just used to hover the cursor.
