### ISSUE TITLE
Option to disable cursor blink

### ISSUE THREAD

**Issue by ianthehenry** [zed-industries/community#189]
**Is your feature request related to a problem? Please describe.**
I really dislike cursor blink.

**Describe the solution you'd like**
Let me disable cursor blink.

**Describe alternatives you've considered**
Use Sublime text, which allows me to disable cursor blink.

**Comment by restfuladi** [comment]
I would also appreciate this, it's the first change I make in every editor or terminal. I find it very distracting and it makes it difficult to focus on reading. When the blink draws my attention away it feels like a mini context switch.

**Comment by restfuladi** [comment]
This seems like an easy fix. Every editor has this option.

**Comment by yashank09** [comment]
Can we also have settings like making the cursor an underline, bold, thin etc.? Maybe a few different animations for blinks as well? 🙈 
Not sure if I should create a new ticket for this^

**Comment by TENX-S** [comment]
any update on this 👀?

**Comment by as-cii** [comment]
Cursor blinking can be disabled by adding `"cursor_blink": false` in your local settings. This has been in Zed for a few versions at this point, but we forgot to close this issue when the setting was released. Thanks so much for the report!

@yashank09: it'd be great if you could create another issue that just captures the ability to change cursor style. Thanks!
