### ISSUE TITLE
VIM Mode - full stop character (dot - . ) does not repeat previous operation

### ISSUE THREAD

**Issue by OlegGulevskyy** [zed-industries/community#1895]
### Check for existing issues

- [X] Completed

### Describe the feature

In VIM whenever you use `.` operator, it repeats previously done operation
It would be good to have it in Zed also

**Comment by ConradIrwin** [comment]
Thanks! This is also tracked here: https://github.com/zed-industries/community/issues/946.

I'm planning to take this on over the next few weeks, so stay tuned!
