### ISSUE TITLE
It's not possible to quit app using CMD + Q

### ISSUE THREAD

**Issue by jezikk** [zed-industries/community#1898]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After the latest update to 0.99 version It's not possible to quit the app using CMD + Q. 

### Environment

Zed: v0.99.0 (preview)
OS: macOS 13.5.0
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Thanks @jezikk, we're currenlty investigating this!  Will update as soon as I know more.

**Comment by JosephTLyons** [comment]
We are building a patch now.  Should be up in a bit.

**Comment by JosephTLyons** [comment]
Should be fixed in v0.99.1.
