### ISSUE TITLE
An option to disable double quotation auto insertion

### ISSUE THREAD

**Issue by iamvoidcoder** [zed-industries/community#1903]
### Check for existing issues

- [X] Completed

### Describe the feature

Can an option to disable double quotation auto insertion be added please? Not many editors have this on by default and if they do there is always a way to turn it off. Don't think there is a way to disable this in the current build. At least I wan't able to find anything relevant in the config file nor any info in discussions.

**Comment by JosephTLyons** [comment]
Thanks for the feature request @iamvoidcoder -I dont think we have a setting for this at the moment, but it makes sense that we would add something like this.
