### ISSUE TITLE
Allow setting keybindings to the newly added case conversion actions

### ISSUE THREAD

**Issue by wzxu** [zed-industries/community#1909]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently there are no default bindings set for them and there seems to be no way to set new bindings for them.
I'm used to having "⌘K ⌘U" for transforming to upper case and "⌘K ⌘L" for lower case. This is default in Sublime Text.
Please add a way to do so.

**Comment by JosephTLyons** [comment]
Hey @wzxu, I currently have my key bindings set up this way.. try this snippet out:

```json
{
  "context": "Editor",
  "bindings": {
    "cmd-k cmd-u": "editor::ConvertToUpperCase",
    "cmd-k cmd-l": "editor::ConvertToLowerCase"
  }
}
```

If this doesn't work for you, feel free to paste in all of your `keymap.json` file and I can help debug.

**Comment by wzxu** [comment]
@JosephTLyons Thank you, that works. I suppose the root problem is that there's no way an end user would know the actions exist if they're not part of Default Key Bindings. Will have to keep an eye on #196, I guess.
