### ISSUE TITLE
Visual Block mode Cursor Error

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/community#1950]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Right
![image](https://github.com/zed-industries/community/assets/19868292/c3194472-e2f4-4db0-8adc-f8137cc95880)
wrong
![image](https://github.com/zed-industries/community/assets/19868292/1079fb01-5b70-4e8a-9f36-0797c0c4c4c0)

### Environment

Zed: v0.101.0 (preview)
OS: macOS 13.4.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
cc/ @ConradIrwin

**Comment by ConradIrwin** [comment]
Thanks for the speedy report! I was preserving the column positions just slightly late, so this was broken if you get to the start position using a sideways motion, and then the first change to the selection adjusted the goal.

Fix will be in the next preview.
