### ISSUE TITLE
`CTRL` + `Space` should trigger syntax hints

### ISSUE THREAD

**Issue by widersky** [zed-industries/community#1967]
### Check for existing issues

- [X] Completed

### Describe the feature

In VSCode as well as in Jetbrains IDE's there is the ability to show syntax hints if for some reason they do not show up (for example, when you insert a space after `->` in PHP). When you press `CTRL` + `Space` the menu reappears.

### If applicable, add mockups / screenshots to help present your vision of the feature

![image](https://github.com/zed-industries/community/assets/45122321/d2898f6c-c64a-4335-9586-4a5556b23fb8)

**Comment by JosephTLyons** [comment]
We actually implemented this behavior.  In the command palette, it is `editor: show completions`, but there is an issue with the keybinding not working for some reason.

Adding this [older issue](https://github.com/zed-industries/community/issues/1120) in for reference.

**Comment by JosephTLyons** [comment]
Hey @widersky, are you still running into this? I had the same issue, but found that macOS was stealing the key binding:

`System Settings` > `Keyboard` > `Keyboard Shortcuts` > `Input Sources` > deselect `Select the previous input source`

**Comment by widersky** [comment]
@JosephTLyons looks like it works now properly :)
