### ISSUE TITLE
Project manager

### ISSUE THREAD

**Issue by zisra** [zed-industries/community#1976]
### Check for existing issues

- [X] Completed

### Describe the feature

Can there please be a project manager similar but better than VScode? I want to create a new window but it always shows the new "untitled" file. It would be nice if this project manager saved a list of project directories, automatically removing those that don't exist.

**Comment by jezikk** [comment]
There is a basic project manager already:
<img width="405" alt="image" src="https://github.com/zed-industries/community/assets/7671531/fa5ea8d5-573c-4f12-995a-321ff2dcd5a7">

**Comment by zisra** [comment]
Thanks @jezikk , what theme is that?

**Comment by JosephTLyons** [comment]
There is also a modal project selector as well -> `opt-command-o`.  That being said, we may want to get a little more sophisticated in the future with project management, so feedback is definitely welcome here.

**Comment by zisra** [comment]
Thank you and sorry for missing the feature
