### ISSUE TITLE
How to `go back` after `go to definition`

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2001]
### Check for existing issues

- [X] Completed

### Describe the feature

This is essential binding for me but I can't find how to do it.

I searched here: https://zed.dev/ref/default.json

Thought it was `"shift-f8": "editor::GoToPrevDiagnostic",` but it was not.

What is it?

**Comment by bigspawn** [comment]
Hi! I think these examples could be helpful https://github.com/zed-industries/keymaps

**Comment by nikitavoloboev** [comment]
`pane::GoBack` is what I needed, thank you
