### ISSUE TITLE
How to have one keybind that will open/close project panel

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2005]
### Check for existing issues

- [X] Completed

### Describe the feature

I only found this `project_panel::ToggleFocus` but it does not do what I need.

I need one binding that will close the project panel if its currently open. And same keybind that will open it if its not currently open and bring focus to it.

**Comment by nikitavoloboev** [comment]
<img width="214" alt="image" src="https://github.com/zed-industries/community/assets/6391776/3b72c4ca-c4d8-4e85-b0fc-d5bcc1911960">

<img width="259" alt="image" src="https://github.com/zed-industries/community/assets/6391776/b560bd50-430d-40a3-9d81-02925fd6ed1a">


I see its cmd+r but i don't get how to rebind it to `cmd+t` to open/close.

**Comment by JosephTLyons** [comment]
Hey @nikitavoloboev, try this snippet:

```json
{
  "context": "Workspace",
  "bindings": {
    "ctrl-t": "workspace::ToggleRightDock"
}
```

If this alone doesn't work, you might have to null out the `transpose` command:

```json
{
  "context": "Editor",
  "bindings": {
    "ctrl-t": null
  }
}
```

**Comment by JosephTLyons** [comment]
Let me know if this works for you.

**Comment by nikitavoloboev** [comment]
Yep that worked, thanks.

I actually started to prefer the cmd+r default keymap that does this so will be using that.
