### ISSUE TITLE
`prettier` formatter does not run on .tsx files when it should

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2016]
### Check for existing issues

- [X] Completed

### Describe the feature

Not sure why but for some reason when I edit `.tsx` files in Zed, the formatter with `prettier` just not run on the file.

This is in Zed after saving.

<img width="549" alt="image" src="https://github.com/zed-industries/community/assets/6391776/93b85c76-f4c8-4a4e-9330-622016755823">

This same file in same project in VSCode after saving.

<img width="526" alt="image" src="https://github.com/zed-industries/community/assets/6391776/30c13082-d39a-499b-92e4-eb04be63cc1f">

Not sure what is happening but seems formatter is simply disabled or something for `.tsx` files.

**Comment by nikitavoloboev** [comment]
It kind of shows by lack of highlighting in `<div>`. I guess there is not yet support for `.tsx`

<img width="484" alt="image" src="https://github.com/zed-industries/community/assets/6391776/5e4f8815-a947-4ab6-8e52-1354325fc491">

**Comment by jwnx** [comment]
There is a similar discussion going on here: https://github.com/zed-industries/community/issues/340

**Comment by fpigeonjr** [comment]
confirmed, I am having the same issue on `.tsx` files not formatting with prettier

**Comment by SomeoneToIgnore** [comment]
This is odd, since now we should have prettier support.

Is there a `"formatter"` setting in your settings.json? If it's absent, it now defaults to `"formatter": "auto"` which invokes prettier for applicable files (tsx included).
Could you also check for LSP logs: prettier entry should be there and if it's not, for Zed logs?

If there's a project and a file I can try it in, it's also very helpful.

**Comment by fpigeonjr** [comment]
👍 thanks @SomeoneToIgnore, I'll add more details after work today.

**Comment by fpigeonjr** [comment]
```json
// zed/settings.josn
{
  "theme": "One Dark",
  "buffer_font_size": 15.5,
  "autosave": "on_focus_change",
  "buffer_font_family": "MonaLisa",
  "project_panel": {
    "dock": "right"
  }
}
```
and then the prettier config
```json
module.exports = {
	arrowParens: 'avoid',
	bracketSameLine: false,
	bracketSpacing: true,
	embeddedLanguageFormatting: 'auto',
	endOfLine: 'lf',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: false,
	printWidth: 80,
	proseWrap: 'always',
	quoteProps: 'as-needed',
	requirePragma: false,
	semi: false,
	singleAttributePerLine: false,
	singleQuote: true,
	tabWidth: 2,
	trailingComma: 'all',
	useTabs: true,
	overrides: [
		{
			files: ['**/*.json'],
			options: {
				useTabs: false,
			},
		},
		{
			files: ['**/*.mdx'],
			options: {
				proseWrap: 'preserve',
				htmlWhitespaceSensitivity: 'ignore',
			},
		},
	],
}

```

**Comment by fpigeonjr** [comment]
> If there's a project and a file I can try it in, it's also very helpful.

I am working thru Kent C Dodd's Epic Web course [repo](https://github.com/epicweb-dev/full-stack-foundations)

**Comment by SomeoneToIgnore** [comment]
Thank you, this is a project with `"workspaces"` that groups packages differently, compared to "regular" package.json projects, and Zed fails to find prettier in a proper place.
Will work on a fix.

**Comment by fpigeonjr** [comment]
Thanks @SomeoneToIgnore, appreciate the acknowledgement and engagement here. Please let me know if I can help in any way.

**Comment by SomeoneToIgnore** [comment]
Zed Preview 0.111.2 contains the fix and the project formatting works for me now, stable will get it next Wednesday.
