### ISSUE TITLE
How to by default open terminal on right side

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2025]
### Check for existing issues

- [X] Completed

### Describe the feature

Currently opening terminal always opens it on the bottom. My preferred way is on the right side.

How can I tell Zed to always open it on right side.

Similar issue to this is https://github.com/zed-industries/community/issues/2004 that I also wish was added.

I want to focus in on existing terminal instead of opening a new terminal every time the command is called.

**Comment by mikayla-maki** [comment]
Right click on the terminal icon and select 'Dock right'!

**Comment by nikitavoloboev** [comment]
> Right click on the terminal icon and select 'Dock right'!

Yes I can do this. But then i have to do this every single time the terminal is created. 

Or am I missing something? I want all terminals to open on right side.

**Comment by nikitavoloboev** [comment]
@mikayla-maki 

> ctrl-\

This does nothing for me.

<img width="1512" alt="image" src="https://github.com/zed-industries/community/assets/6391776/d41eca6b-02ce-4dc9-b62f-9181ebb6f79c">

I have this, editor in focus. I press `ctrl-\` and nothing happens, focus does not jump to terminal.

What is the action of it in `keymap.json`, maybe I can rebind it to another keybind and try again?

<img width="632" alt="image" src="https://github.com/zed-industries/community/assets/6391776/3bc6d882-d0f9-4684-9919-6e0591f555eb">

Thank you.

**Comment by mikayla-maki** [comment]
Oh sorry, `ctrl-backtick` is what I meant. Hard to type that character properly in markdown 😅

The action is `terminal_panel::ToggleFocus`, and if you want to browse all of the actions we have bound you can use the `zed: open default keymap` action from the command palette 🙂

**Comment by nikitavoloboev** [comment]
<img width="515" alt="image" src="https://github.com/zed-industries/community/assets/6391776/8931f4ab-c121-4b78-af54-eb072c87609d">

How can I do above. I did `zed: open default keymap` but can't find how to bring focus back to editor.

The thing is that `ctrl-`` does what I want. It switches focus between editor and terminal on same key. I just want to rebind it to `cmd+j`. But I don't know how it does it:

<img width="858" alt="image" src="https://github.com/zed-industries/community/assets/6391776/474495b7-ea59-498d-97ca-d3f3c112429d">

As there is only one key bound there. How does it know to switch back?

**Comment by mikayla-maki** [comment]
The `_panel::ToggleFocus` commands look at what you currently have focus (the center working area, or the panel) and shift your focus to the other one. I'd suggest binding it in the global context (no `context` field) to enable that kind of behavior, like we do in the default keymap:

```json
[
  {
  "cmd-j": "terminal_panel::ToggleFocus"
  }
]
