### ISSUE TITLE
Tailwind CSS support in Svelte components

### ISSUE THREAD

**Issue by jeppech** [zed-industries/community#2029]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Basic Tailwind CSS support was added in `Zed 0.103.1`. It seems to be working in HTML/JSX/TSX files, but not `Svelte` files.

### Environment

Zed: v0.104.0 (preview)
OS: macOS 13.5.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Screenshot where no Tailwind classes are shown when writing `h-`: https://i.jeppe.ch/7hMBggmMtG0n.png

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
cc @ForLoveOfCats (tailwind) / @mikayla-maki (svelte).

**Comment by zachdaniel** [comment]
Would also be great have this in `.heex` files (Phoenix LiveView templates) :)

**Comment by jmkmay** [comment]
This is the single thing preventing me from adopting Zed over VS Code. Godspeed!

**Comment by Spikeysanju** [comment]
Zed Tailwind CSS support in Svelte would be fantastic.

**Comment by JosephTLyons** [comment]
Coming soon!

**Comment by JosephTLyons** [comment]
This is available in today's preview release - v0.110.0.
