### ISSUE TITLE
Allow stopping blinking cursor in terminal

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2042]
### Check for existing issues

- [X] Completed

### Describe the feature

I cannot change blinking cursor in my Fish shell itself, it has to be done 

<img width="994" alt="image" src="https://github.com/zed-industries/community/assets/6391776/c0b9a8b5-8ad1-47e3-bbe9-0196624eca9d">

Warp [allows you to do this](https://docs.warp.dev/appearance/text-fonts-cursor).

Please allow turning off blinking cursor in terminals in Zed too.

Similar to how you already have `"cursor_blink": false` for Editor cursor.

Thanks.

**Comment by nikitavoloboev** [comment]
Although on 2nd thought the blinking part is useful as it shows that the terminal is in focus.

Still would be nice to have option for non blinking cursor in terminal.

**Comment by mikayla-maki** [comment]
Hi Nikita, 

Similar to the keymaps, we already have this setting available, like so:

```json
{
  "terminal": {
    "blinking": "off"
  }
}
```

You can use the command `zed: open default settings` to see the initial settings we think are sensible defaults in Zed, + documentation for each one :)
