### ISSUE TITLE
Stuck on `Checking for updates for Rust language server`

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2050]
### Check for existing issues

- [X] Completed

### Describe the feature

Since 0.103.1 zed update, i get this showing all the time

<img width="476" alt="image" src="https://github.com/zed-industries/community/assets/6391776/245c8a90-e0ea-40d2-940b-44ff449e246f">

It stays on app restarts. It stayed there for 2 days already. I have good network. So no idea why it's stuck. Or what to do to unblock it.

**Comment by osiewicz** [comment]
Hi Nikita,
Would it be possible to get the logs? (Either from `~/Library/Logs/Zed/Zed.log` or `zed: open log` palette action)

**Comment by nikitavoloboev** [comment]
https://gist.github.com/nikitavoloboev/b22a453435aae69715393b1fd2688880

**Comment by osiewicz** [comment]
[zed-industries-issue-2050-stuck-rust-lsp.zip](https://github.com/zed-industries/community/files/12647215/zed-industries-issue-2050-stuck-rust-lsp.zip)
Mirroring your upload; we've had a few issues like that which we're trying to track down
