### ISSUE TITLE
Can't do `:w` in vim mode. `:` does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [zed-industries/community#2056]
### Check for existing issues

- [X] Completed

### Describe the feature

In vim mode if I try save file with `:w` it would actually do a jump to a word. Basically `:` seems fully broken with recent update.

**Comment by JosephTLyons** [comment]
cc @ConradIrwin

**Comment by ConradIrwin** [comment]
This just shipped in Zed 0.106 preview if you want to try it out and leave feedback (here or through `:feedback`, please do!).
