### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#206]
**Is your feature request related to a problem? Please describe.**
Something I would enjoy having in Zed would be file icons.

**Describe the solution you'd like**
The easiest route would be to just use the [images that were used for Atom's File Icons plugin](https://github.com/file-icons/icons). The license permits these to be used in commercial software.  A VS Code package was made with this image set as well, but I think VS Code may use a different set of images by default.

Places images could show up:

- File Tree  
- Tabs
- File Searcher
- Anywhere else that displays file names?

**Comment by kyjus25** [comment]
Alternatively, and preferably in my opinion, use the icons in [vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme). 15M downloads speaks for itself, also licensed as MIT

Super excited for this feature (and phenominal job to the team thus far, btw!)

**Comment by jakobbouchard** [comment]
I also prefer the material icon theme, for what it's worth. I find it more consistent and better looking.

**Comment by totsteps** [comment]
There's also [icons list](https://jetbrains.design/intellij/resources/icons_list) from **IntelliJ Platform UI Guidelines**.

Not sure if they are up-to-date and require a license.

**Comment by eggnaut** [comment]
> For what it's worth, I think this is one of the best looking icon packs in the market. Might be usefull for this ticket https://github.com/miguelsolorio/vscode-symbols

I second that. I used it with VSCode and oh my gosh it looked amazing. Simple and clean icons. Not overdone.

**Comment by kyjus25** [comment]
> For what it's worth, I think this is one of the best looking icon packs in the market. Might be usefull for this ticket https://github.com/miguelsolorio/vscode-symbols

Tried it just now and yup, changing my answer. This is the one. Seems to have even more icons than Material Icon Theme! Thanks for the recommendation!

**Comment by jakobbouchard** [comment]
I'll also say that the Symbols icons look better! Disagree that there are more icons (I guess it depends what files you use), but they look more consistent, and it seems that more get added rather quickly!

**Comment by kyjus25** [comment]
@jakobbouchard For instance, for `.component.ts` files, Symbols specifically shows an Angular logo and Material only shows a TypeScript logo

**Comment by jakobbouchard** [comment]
I think that's not necessarily a missing icon, but more of a mapping issue maybe? Not sure actually. `.component.ts` files could also technically be used for something else than Angular, might be why. Anyways, doesn't matter, Symbols looks better haha

**Comment by jbergstroem** [comment]
Style-wise, [quill icons](https://github.com/cdonohue/vscode-quill-icons) seems to be a good fit.

**Comment by jansol** [comment]
> quill icons

I especially appreciate that those are monochrome and thus easily adaptable for any color scheme. (depending on what format they are defined in)

**Comment by jakobbouchard** [comment]
Just to add one more option, the @catppuccin theme also has a [sweet icon pack](https://github.com/catppuccin/vscode-icons)!

**Comment by JosephTLyons** [comment]
Hey everyone, a PR for file icons just landed on `main` today. Please open new issues for any followup stuff related to this feature request.

**Comment by jbergstroem** [comment]
@JosephTLyons out of curiosity. Whats the process between `main` and what most people use (`beta`?)? Saw the `bash` issue close the other day and as a user there's a disconnect between something closed as "fixed" and being able to test it!

**Comment by iamnbutler** [comment]
As we usually mention when closing most issues, the typical time from main to a stable release is 2 weeks. 

Usually when something merges it will move to the preview channel in a week, and stable the next week if there are no issues/additional changes that need to be made.

Sometimes we catch issues and hold something back from being released, or certain features are developed on preview for longer than a week. It is a pretty manual process on the moment, and sometimes patch releases go out, so estimating the exact time until everyone on stable gets something is not very consistent.

We typically release on Wednesdays, so if something is merged Tuesday night you may get it in 8 days, etc.

**Comment by JosephTLyons** [comment]
Hey @jbergstroem - we just published this today!

- https://zed.dev/blog/preview-channel

**Comment by acusti** [comment]
the new file icons are great! thanks @mikayla-maki @JosephTLyons and anyone else involved in the release 🙇. the new visual language on the whole is very nice. i noticed that .json files have a database-like icon, which puzzled me, but i’m sure it’ll become familiar.

<img width="167" alt="image" src="https://github.com/zed-industries/community/assets/517889/91444fd1-03e0-4f95-8256-7f9d833a044f">

**Comment by JosephTLyons** [comment]
> the new file icons are great! thanks @mikayla-maki @JosephTLyons and anyone else involved in the release 🙇. the new visual language on the whole is very nice. i noticed that .json files have a database-like icon, which puzzled me, but i’m sure it’ll become familiar.
> 
> 
> 
> <img width="167" alt="image" src="https://github.com/zed-industries/community/assets/517889/91444fd1-03e0-4f95-8256-7f9d833a044f">
> 
> 

Glad to hear the positive feedback! Just to mention it, file icons are a work in progress.  Derek is tweaking things and adding new icons here and there, so nothing is set in stone.

**Comment by terrysahaidak** [comment]
Trying out Zed right now and I found that it's really hard for me to navigate around without colorful icons. Very exited about this feature.
