### ISSUE TITLE
True quotes and other hidden characters

### ISSUE THREAD

**Issue by fuzenco** [zed-industries/community#2072]
### Check for existing issues

- [X] Completed

### Describe the feature

True __opening__ quotation marks (both “ and ‘) aren’t able to be used in Zed. The macOS keyboard shortcuts for those: 'Option+[' and 'Option+]' don’t create any character. I like to write in Zed and then transfer to another doc, but as it stands I’ve been having to use VS Code for much of my writing because of this.

[Update by me (@fuzenco): I’ve edited the description above as the original description was too broad and not correct. The problem is now specifically noted above and below in the comments.]

**Comment by osiewicz** [comment]
Hi, thank you for the report. What keyboard layout are you using? I am using a Polish keyboard layout and it seems to work for me:
Shift+Option+[ types: ”
Shift+Option+] types: ’
We've seen keyboard layout impact these kinds of issues in the past though.

**Comment by fuzenco** [comment]
> Hi, thank you for the report. What keyboard layout are you using?

I’m using the US keyboard. I also have Latin America available to me but my default is always US.

I really don’t use the true quotes in any other language except US. But the keyboard combos I provided have been the default shortcuts for macOS and previously Mac OS for as long as I can remember…15+ years (?!).

**Comment by fuzenco** [comment]
Oops. My bad. The keyboard combos I provided were wrong. They are actually…

Opening quotation mark: Option+[

Shift+Option+[

**Comment by fuzenco** [comment]
Let me clarify this because I was incorrect in the keyboard shortcuts provided. Also, noted another problem…

Opening double quote mark: “
Keyboard sequence: Option+[
Status: Does Not Work

Close double quote mark: ”
Keyboard sequence: Shift+Option+[
Status: Does Work

Opening single quote mark: ‘
Keyboard sequence: Option+]
Status: Does Not Work

Closing single quote mark: ’
Keyboard sequence: Shift+Option+]
Status: Does Work

**Comment by fuzenco** [comment]
I know you're hard at work, but do you have any idea if this problem has been pinpointed and a possible fix coming in the next few weeks? I’m locked into VS Code until then :(

**Comment by osiewicz** [comment]
Hey, I'm sorry for not getting back to you sooner; I've found the culprit, which is that the default key bindings for Copilot occupy the `option-[` and `option-]` binds. 
Do you use Copilot in our product? The issue should present itself regardless of that, but the fix that I have in mind (propagating the keystroke if there's no Copilot-related action on your cursor) would not work if you are using Copilot actively.
I'll open up a PR shortly, you can expect it to be part of next Preview release (Wednesday, 18.10)

**Comment by fuzenco** [comment]
Interesting. I do not use Copilot. Good solution, though. Thank you.

**Comment by osiewicz** [comment]
This is in Preview now.

**Comment by fuzenco** [comment]
> This is in Preview now.

Is Preview downloadable as a simple DMG?

**Comment by osiewicz** [comment]
Yup, and it can coexist with your stable Zed. See https://zed.dev/releases/preview

**Comment by fuzenco** [comment]
Beautiful. Thanks!

**Comment by fuzenco** [comment]
> Yup, and it can coexist with your stable Zed. See https://zed.dev/releases/preview

Fixed works perfect. Thanks, and my goodness Preview is beautiful 👍
