### ISSUE TITLE
Cursor keys no longer working correctly in completion pop-up (Python)

### ISSUE THREAD

**Issue by citizenTwice** [zed-industries/community#2079]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to select any item other than the first one by pressing the 'down' key  breaks out of the completion menu and moves the editor cursor one line down. Tested (happens every time) with Python sources in 0.104.4.

How to reproduce:
 1 - type name of object variable, class or module, followed by dot "."
 2 - wait for completion menu
 3 - try to select 2nd item by pressing [Down] key

![image](https://github.com/zed-industries/community/assets/20754288/8bd348c9-af5c-427d-8418-75b785d3921d)

### Environment

Zed: v0.104.4 (stable)
OS: macOS 13.6.0
Memory: 24 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![image](https://github.com/zed-industries/community/assets/20754288/8bd348c9-af5c-427d-8418-75b785d3921d)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @citizenTwice, I'm not able to reproduce this. Are you using vim mode? Would you mind pasting in your `settings.json` file?

**Comment by citizenTwice** [comment]
Hey @JosephTLyons thank you for prompt reply. Yes, very interesting, I've added the below section to my `keymap.json` as suggested in #2036 and now completion menu navigation appears to be working correctly again. 
Can I grab the full, official `keymap.json` that belongs to the latest version of Zed  from somewhere on github?
Thanks a lot for your help!


>     "context": "Editor && (showing_code_actions || showing_completions)",
>     "bindings": {
>       "up": "editor::ContextMenuPrev",
>       "ctrl-p": "editor::ContextMenuPrev",
>       "down": "editor::ContextMenuNext",
>       "ctrl-n": "editor::ContextMenuNext",
>       "pageup": "editor::ContextMenuFirst",
>       "pagedown": "editor::ContextMenuLast"
>     }

**Comment by JosephTLyons** [comment]
I'm curious to see the full contents of your `keymap.json` file, as the defaults should be working on their own without having to manually put them into your file.  It feels like something might be clashing here.  Can you post your full config file?

**Comment by citizenTwice** [comment]
Yes indeed something looks a bit off. I've made a backup of the keymap file before adding the new section, attached here. 
Also, there may be info of interest in the log file, or at least some suspicious-looking entries that I cannot readily understand, in particular, the records:

`2023-09-24T05:46:48 [INFO] completion out of expected range`

which seem to have stopped appearing after the keymap change. I have redacted a couple of semi-private bits in the log and attached a copy of that too.

[BACKUP_OLD.keymap.json.TXT](https://github.com/zed-industries/community/files/12715321/BACKUP_OLD.keymap.json.TXT)
[copy_of_Zed.log.TXT](https://github.com/zed-industries/community/files/12715322/copy_of_Zed.log.TXT)

**Comment by JosephTLyons** [comment]
@citizenTwice - the problem here seems to be having `"down": "editor::MoveDown",` in your keymap.  Removing that fixes the problem with not being able to move down in the autocompletions list. 

Also, there seems to be a lot of duplicates in here from the `Default Key Bindings` file.  If you open the command prompt `cmd-shift-p` and run `zed: open default keymap`, you'll see all the default bindings, which should work without having to put anything into your personal key binding configuration.  I'd consider removing any bindings that exist in both your configuration and the default file, so that you have less to sift through, which will make debugging a bit easier.

**Comment by citizenTwice** [comment]
@JosephTLyons I'm actually not so sure how I ended up with such a large keymap.json - I've now zapped pretty much the whole thing and got it down to:

````
[
  {
    "context": "Editor",
    "bindings": {
      "pageup": "editor::MovePageUp",
      "shift-pageup": "editor::SelectToStartOfParagraph",
      "pagedown": "editor::MovePageDown",
      "shift-pagedown": "editor::SelectToEndOfParagraph"
    }
  }
]
````

Everything appears to be working correctly, including the completion menu.

**Comment by JosephTLyons** [comment]
> @JosephTLyons I'm actually not so sure how I ended up with such a large keymap.json - I've now zapped pretty much the whole thing and got it down to:
> 
> 
> 
> ````
> 
> [
> 
>   {
> 
>     "context": "Editor",
> 
>     "bindings": {
> 
>       "pageup": "editor::MovePageUp",
> 
>       "shift-pageup": "editor::SelectToStartOfParagraph",
> 
>       "pagedown": "editor::MovePageDown",
> 
>       "shift-pagedown": "editor::SelectToEndOfParagraph"
> 
>     }
> 
>   }
> 
> ]
> 
> ````
> 
> 
> 
> Everything appears to be working correctly, including the completion menu.
> 
> 
> 
> 

Excellent! That looks a lot better and easier to maintain :)

**Comment by citizenTwice** [comment]
@JosephTLyons Thank you for the great support, Zed rocks my world! 🌟

**Comment by JosephTLyons** [comment]
> @JosephTLyons Thank you for the great support, Zed rocks my world! 🌟

Absolutely, always here to help!
