### ISSUE TITLE
Keybind action for toggling terminal visibility _and_ focus

### ISSUE THREAD

**Issue by ryangjchandler** [zed-industries/community#2109]
### Check for existing issues

- [X] Completed

### Describe the feature

Right now, you can toggle focus on a terminal. I'd like an action that toggles the focus but also hides the terminal widget/window. I have this bound to `Cmd + Shift + T` and use the same behaviour inside of VSCode all the time.

**Comment by JosephTLyons** [comment]
Hey @ryangjchandler, which dock do you have your terminal in? We have something similar to what you are asking, but I'm not sure if it behaves exactly the same. We have commands to toggle the docks that automatically focus the panels inside, but will also hide it. For instance, I have my terminal panel in the bottom dock, and I have my keymap configured with:

`"cmd-b": "workspace::ToggleBottomDock"`

- If the dock isn't visible, running the action will open the dock and put focus on it
- If the dock is visible, running the action will close the dock and move focus back to the workspace center

**Comment by ryangjchandler** [comment]
@JosephTLyons Thanks, that should probably do what I need. I assume it keeps the terminal running still and doesn't "quit" the widget?

**Comment by JosephTLyons** [comment]
All terminal tabs in the dock stay active, they are not killed off when closing the dock.

**Comment by ryangjchandler** [comment]
Awesome! In which case, I guess this issue can be closed :) Thank you very much! I look forward to seeing what comes in future releases.
