### ISSUE TITLE
Vim mode escape do not work as expected - you need to type it twice

### ISSUE THREAD

**Issue by Nakahiru** [zed-industries/community#2127]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Steps to reproduce the issue:

- Go in visual block mode with `shift + v`
- select some line with `k` or `j`
- trying to escape vim mode with `escape`
- it don't work you need to type `escape` twice to exist

The is the same issue with other kind of vim mode.
This issue prevent totally the use of the vim mode - it's really an annoying one 🙃

### Environment

Zed: v0.107.3 (preview)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Video showing the issue: https://share.cleanshot.com/bsCBLLKc

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by Nakahiru** [comment]
@ConradIrwin Thanks for your concern.

Weird 🤔 My caps lock is bind to escape but if I directly use the escape key it's acting in the same way so I don't think it's the issue. I use the Karabiner Elements software to create custom key bindings. I just tried disabling it completely to confirm that it's not the cause of the issue. It didn't solve the issue 🤔 Very strange.

If I provide the log file it could help you or not?

**Comment by ConradIrwin** [comment]
Hmm, I also have caps lock as escape, so not that...

What keyboard layout are you using by default? That's caused some odd issues for us in the past (for example if there are characters that are typed with `<esc>+<key>` I might expect some issues).

I'll play around with Karabiner too

**Comment by Nakahiru** [comment]
The keyboard is an ANSI US layout. It is set in MacOS settings to `US International - PC`. I tried to play with it and to change some settings but nothing change. I don't think Karabiner is the problem, it was working fine some weeks ago and I didn't change anything. I don't know if the problem appear directly after a zed update or if it something that I have done on my system 🤔

I also tried to uninstall and re install zed, just in case, the issue is still present.

**Comment by Nakahiru** [comment]
@ConradIrwin So... After spending a long time on the issue, I even tried it in a VM... 🤯 I don't know what caused the issue, but I found a way to resolve it by cleaning the Zed config folder: `rm -rf ~/.config/zed/`. We may thinking that it was cause by an error in the keymap.json file but before erasing totally the folder I tried to only delete keymap.json file and it won't work ... so idk 🤷🏻‍♂️

**Comment by ConradIrwin** [comment]
Very weird! Thank you for following up.

I'm going to close this for now, but if you get into this state again, let's take a look in that folder together.
