### ISSUE TITLE
Keymap for adding new selection not working

### ISSUE THREAD

**Issue by matthewmorek** [zed-industries/community#2130]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Trying to use default keymap from VS Code for adding cursor up/down (⌘ + ⎇ + ↑/↓), but it doesn't seem to work with neither default keymap (VS Code) nor with a custom keymap, as below:
```
[
  {
    "context": "Editor",
    "bindings": {
      "cmd-alt-up": "editor::AddSelectionAbove",
      "cmd-alt-down": "editor::AddSelectionAbove"
    }
  }
]
```

### Environment

Zed: v0.106.2 (stable)
OS: macOS 13.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![CleanShot 2023-10-10 at 13 01 35@2x](https://github.com/zed-industries/community/assets/1137994/fd4e560e-fc2c-4c1a-92a2-2d2d3d0a676d)

Video: https://share.cleanshot.com/PRNg6nHYFZ627XtWm18G

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Huh, this key binding is a default one and currently works for me. I wonder if something else is clashing for you. Would you be willing to post your entire `keymap.json` file? Or is what you already posted the whole thing already?

Also, are you using any special layouts or keyboards?

**Comment by matthewmorek** [comment]
I'm using a default keymap (VS Code), check it out [keymap.json](https://github.com/zed-industries/community/files/12860210/keymap.json).

This shortcut works perfectly fine in VS Code, and I use no special keyboard/keybinds, definitely not for this action, which I use quite often. No special layouts either. The app is stock.

**Comment by JosephTLyons** [comment]
That looks like the internal default keymap, would you mind pasting in your personal keymap overrides? In the command palette (`cmd-p`) -> `zed: open keymap`

**Comment by matthewmorek** [comment]
I've no custom keymap of my own, the snippet from my first comment is the only thing I tried to get this to work. Maybe there's a way to see in Zed if it received specific keyboard events, so I could help debug this?

Worst-case scenario, I can nuke my local install and reinstall from scratch. Here's my [settings.json](https://github.com/zed-industries/community/files/12861293/settings.json), just in case you may spot anything affecting keyboard events?

**Comment by matthewmorek** [comment]
Looks like one of the latest releases has fixed the issue, and now my keymaps work correctly. Closing as fixed.
