### ISSUE TITLE
Zed crashing on startup, no error logs, clicking "Reopen" opens application as expected

### ISSUE THREAD

**Issue by Nezteb** [zed-industries/community#2136]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I did a fresh install of Zed today, 0.107.6.

Whenever I try to open it, it crashes. No matter how many times I retry, it fails.

However, if I click the macOS "Reopen" button on the crash popup, Zed starts just fine. 🤔

See attached screen recording for more detail.

There are a few other macOS crash issues, but none of them seem very similar to my issue:
- https://github.com/zed-industries/community/issues/910
- https://github.com/zed-industries/community/issues/201

### Environment

Zed: v0.107.6 (stable)
OS: macOS 13.6.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://github.com/zed-industries/community/assets/3588798/0a8ddc75-3e59-48f3-b475-056801a14fd6

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

https://github.com/zed-industries/community/files/12888140/Zed.log

If y'all also want the macOS crash report `.pl` file, let me know and I can attach it too.

**Comment by JosephTLyons** [comment]
Hey @Nezteb, the `.pl` crash report would probably help a bit here.  I'm curious what happens if you move your `settings.json` and `keymap.json` files out to a different location temporarily.  Both are located in `~/.config/zed`.

**Comment by jostyee** [comment]
> Hey @Nezteb, the `.pl` crash report would probably help a bit here. I'm curious what happens if you move your `settings.json` and `keymap.json` files out to a different location temporarily. Both are located in `~/.config/zed`.

removing files in `~/.config/zed` didn't help, any support email I can send logs to?

**Comment by JosephTLyons** [comment]
> > Hey @Nezteb, the `.pl` crash report would probably help a bit here. I'm curious what happens if you move your `settings.json` and `keymap.json` files out to a different location temporarily. Both are located in `~/.config/zed`.
> 
> 
> 
> removing files in `~/.config/zed` didn't help, any support email I can send logs to?

`hi@zed.dev` should do nicely.

**Comment by JosephTLyons** [comment]
Hey @Nezteb, we have potential fix. I'm going to put out a patch today. I'll update here when it lands.

**Comment by JosephTLyons** [comment]
Here are the releases, let me know if the issue persists or not:

- [Stable: v0.107.7](https://zed.dev/releases/stable/0.107.7)
- [Preview: v0.108.2](https://zed.dev/releases/preview/0.108.2)

**Comment by Nezteb** [comment]
@JosephTLyons The latest version has fixed the issue for me!

**Comment by JosephTLyons** [comment]
Yay! Thanks for letting us know, and thanks to @osiewicz for digging into the crash log.
