### ISSUE TITLE
Changing lines in yaml file causes other unchanged lines to show as changed

### ISSUE THREAD

**Issue by kefabean** [zed-industries/community#2148]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When editing the following file checked in to a git repo as 'main.yml'. If I comment out lines 19-27 and save the file, the following unchanged lines also show as changed: 52, 53, 58-61, 63-64.

```---
 - name: set timezone to UTC
   timezone:
      name: Etc/UTC

 - name: set hostname
   hostname:
      name: "{{ service_name }}"

 - name: set hostname in hosts file
   lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1 {{ service_name }}"
      owner: root
      group: root
      mode: 0644

 - name: copy rc.conf
   copy:
      src: rc.conf
      dest: /etc/rc.conf

 - name: rng.conf rsyslog config to move noisy log to separate file
   copy:
      src: rng.conf
      dest: /etc/rsyslog.d/rng.conf

 - name: restart rsyslog
   systemd:
       state: restarted
       name: rsyslog

 - name: copy vimrc so we can edit files nicely
   copy:
      src: vimrc
      dest: "/home/pi/.vimrc"
      owner: pi
      group: pi
      mode: 0644

 - name: add base packages required
   apt:
      name:
       - git
       - vim
       - python3-pip
       - python3-rpi.gpio
       - mosh
      state: latest
      update_cache: yes
   
 - name: set vim as the default editor 
   alternatives:
      name: editor
      path: /usr/bin/vim.tiny

 - name: disable led activity light                                             
   blockinfile:                                                                 
      path: /boot/config.txt                                                    
      marker: "# {mark} ANSIBLE MANAGED BLOCK: disable activity light"          
      content: |
         dtparam=act_led_trigger=none                                           
         dtparam=act_led_activelow=on 
```

### Environment

Zed: v0.107.6 (stable)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @kefabean - Hmm, I'm not able to reproduce any additional lines of change on my end, but maybe something didn't transfer properly when copying the file contents into the issue body. Could you include the file itself as an attachment before making any changes to it? It might also be helpful to see what the diff looks like after you comment the lines out and save, in case nothing surfaces on my side again after checking the actual file.

**Comment by kefabean** [comment]
[main.yml.zip](https://github.com/zed-industries/community/files/12934905/main.yml.zip)

Hi there, yes of course. Hopefully the file is zipped up in the link above. The file needs to be checked in to a git repo. After commenting out the lines as described this is the git diff I see (see below). The first chunk show the lines I've commented out, the second chunk shows the change to unchanged lines - note there is no visible change to the lines, I might have a look with a hex editor or something. 

```
% git diff main.yml
diff --git a/roles/base/tasks/main.yml b/roles/base/tasks/main.yml
index 9041144..ed8747c 100644
--- a/roles/base/tasks/main.yml
+++ b/roles/base/tasks/main.yml
@@ -16,15 +16,15 @@
       group: root
       mode: 0644

- - name: copy rc.conf
-   copy:
-      src: rc.conf
-      dest: /etc/rc.conf
+ # - name: copy rc.conf
+ #   copy:
+ #      src: rc.conf
+ #      dest: /etc/rc.conf

- - name: rng.conf rsyslog config to move noisy log to separate file
-   copy:
-      src: rng.conf
-      dest: /etc/rsyslog.d/rng.conf
+ # - name: rng.conf rsyslog config to move noisy log to separate file
+ #   copy:
+ #      src: rng.conf
+ #      dest: /etc/rsyslog.d/rng.conf

  - name: restart rsyslog
    systemd:
@@ -49,16 +49,16 @@
        - mosh
       state: latest
       update_cache: yes
-
- - name: set vim as the default editor
+
+ - name: set vim as the default editor
    alternatives:
       name: editor
       path: /usr/bin/vim.tiny

- - name: disable led activity light
-   blockinfile:
-      path: /boot/config.txt
-      marker: "# {mark} ANSIBLE MANAGED BLOCK: disable activity light"
+ - name: disable led activity light
+   blockinfile:
+      path: /boot/config.txt
+      marker: "# {mark} ANSIBLE MANAGED BLOCK: disable activity light"
       content: |
-         dtparam=act_led_trigger=none
-         dtparam=act_led_activelow=on
+         dtparam=act_led_trigger=none
+         dtparam=act_led_activelow=on
(END)
```

**Comment by kefabean** [comment]
I had a look at the files in a bit more detail (and in hex) and it looks like spaces at the end of these lines are getting stripped out.

**Comment by kefabean** [comment]
Just realised I'm getting these spaces stripped out if I just open the file and save. No need to make any modifications to the file. Could it be related to #1912 ?

**Comment by JosephTLyons** [comment]
If its is not changing the formatting at all, and simply stripping / normalizing trailing whitespace / newlines, then that is a expected - there is a setting to turn that off. If it is moving your content around, then that is a bug for sure.

**Comment by kefabean** [comment]
Doh user error, found it: `"remove_trailing_whitespace_on_save": true`

Can confirm turning this off 'fixes' the issue! 🤦

**Comment by JosephTLyons** [comment]
Awesome - thanks for letting us know!
