### ISSUE TITLE
**command palette** not working as expected

### ISSUE THREAD

**Issue by Stukz** [zed-industries/community#2151]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I want to use the command palette but the search it's not matching my queries as expected.

For example I have the current scenario:

I don't like when all the folders are expanded so my go to it's call the command palette to "collapse all entries." but for some reason the search/regex matching implementation it's not giving the option until I try multiple times (see attached video)

In addition to this I really like the idea of having "recently used commands" so I don't have to type every time I want to use a command that I just called before

### Environment

Zed: v0.107.7 (stable)
OS: macOS 13.5.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Zed Editor command palette command search:

https://github.com/zed-industries/community/assets/57040392/f87cfadc-cdf8-4854-9d33-3b0e6fdb22eb

VS Code command palette command search:

https://github.com/zed-industries/community/assets/57040392/ebd4b7d2-7d07-496b-9b1e-1418e12dd859

**Comment by osiewicz** [comment]
Hey, some commands in the command palette only show up within a specific context - e.g. we may only show search actions if search bar is visible. I suspect that's what's happening there - you may not be seeing the "collapse all entries" action because the project panel is not focused. Can you give that a try and see whether the action shows up for you consistently when the project panel is focused?

**Comment by osiewicz** [comment]
Oh yeah, I definitely agree that it should be easier to discover these commands - I run into this issue myself. I was just trying to figure out if the behaviour you're seeing is indeed a bug in the command palette fuzzy finder or if it was down to the project panel not being focused.
Either way I agree that these commands should be easier to execute without having to worry about focusing the panel first.

**Comment by Stukz** [comment]
I'm going to close the issue since this is not a bug but a feature request. thank you @osiewicz
