### ISSUE TITLE
Tailwind CSS support in ERB files

### ISSUE THREAD

**Issue by enstyled** [zed-industries/community#2153]
### Check for existing issues

- [x] Completed

### Describe the feature

Similar to https://github.com/zed-industries/community/issues/2029 and https://github.com/zed-industries/community/issues/2057 - ERB templates used in Ruby programs are a superset of HTML and the Tailwind autocomplete does not work within them.

**Comment by JosephTLyons** [comment]
This is available in today's preview release - v0.110.0.

**Comment by enstyled** [comment]
Testing it on `Zed Preview 0.110.2` with a Rails app with `gem "tailwindcss-rails"`:
 - The autocomplete does not work
 - Problem reporting does works though


![Image](https://github.com/zed-industries/community/assets/621097/6681fdd2-b2fb-4904-82ec-a52d3726c3c1)
