### ISSUE TITLE
Git branch filter is laggy

### ISSUE THREAD

**Issue by warpdesign** [zed-industries/community#2161]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When clicking on the branch name a filter appears: when typing something in here it's very laggy (maybe because I have lots of branches). It wouldn't be a problem to me if the filter wasn't instant, ie: it won't be applied until I stopped typing for 1-2 secs but as it is now it's difficult to use: typing several letters will be very laggy and the letters will appear after a long time.

Here I type very quickly `jobs`, as you can see in the video below, the final `s` takes several seconds to appear:

https://github.com/zed-industries/community/assets/199648/bec38ac0-5f0d-40e4-9e19-25ea5c2e90c4

### Environment

Zed: v0.108.2 (stable)
OS: macOS 13.6.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by osiewicz** [comment]
Hey,
Thanks for the report! Could you share how many branches do you have in that repository? That'll make it easier for me to repro.

**Comment by osiewicz** [comment]
I've got a PR for this up. It's not merged yet, but I expect it to be a part of next week's Preview (25.10.2023). :)

**Comment by warpdesign** [comment]
I have 569 branches.
