### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by gorenbk** [zed-industries/community#2184]
Do you plan to make Zed open source? If not, why? If yes, when?

**Comment by JosephTLyons** [comment]
Yes - we plan to go open source. Our primary goal at the moment is porting over the entire application to use the newest iteration of our UI library. This port is a blocker for open source, but it is going well. We are shredding through things and making progress. After this lands, we will have a few other smaller tasks to deal with, then we will be in a good state to release the code.

**Comment by JosephTLyons** [comment]
Closing in favor of:

- https://github.com/zed-industries/community/issues/2197
