### ISSUE TITLE
Clangd (C/C++) doesn't recognize Homebrew include path

### ISSUE THREAD

**Issue by HoussemBousmaha** [zed-industries/community#2223]
### Check for existing issues

- [ ] Completed

### Describe the feature

When using external libraries in c/c++ that are installed in the system (on macOS using homebrew they are installed in /opt/hombrew/) i want to get lsp benefits when using these libraries.

Currently the LSP doesn't recognize the include path which is /opt/homebrew/include
This is an issue for me because i keep getting errors that this path doesn't exist! what should i do?

**Comment by JosephTLyons** [comment]
Hey @HoussemBousmaha, does the language servers in other editors pick up these paths for you?

**Comment by HoussemBousmaha** [comment]
> Hey @HoussemBousmaha, does the language servers in other editors pick up these paths for you?

No, my bad, I am new to this, I found a solution which is using cmake

When using cmake it generates some config files that make clangd recognise the include paths. However without cmake you'll have to create these files yourself. Great editor btw, I hope zed get open sourced.
