### ISSUE TITLE
Protobuf support

### ISSUE THREAD

**Issue by bannnn511** [zed-industries/community#2237]
### Check for existing issues

- [X] Completed

### Language

Protobuf

### Tree Sitter parser link

https://github.com/mitchellh/tree-sitter-proto

### Language server link

https://buf.build/blog/introducing-the-buf-language-server

**Comment by JosephTLyons** [comment]
Hey @bannnn511, would you mind if we reopen this? We have a ton of issues that are marked as `potential plugin` so that we, and the community, know what sort of plugins users of Zed are wanting.

**Comment by bannnn511** [comment]
> Hey @bannnn511, would you mind if we reopen this? We have a ton of issues that are marked as `potential plugin` so that we, and the community, know what sort of plugins users of Zed are wanting.

I found this issue is duplicate of  [636](https://github.com/zed-industries/community/issues/636), so if needed you can reopen it 🤣🤣.
