### ISSUE TITLE
Issue when using the Geist Mono Font !!

### ISSUE THREAD

**Issue by enzime4u** [zed-industries/community#2251]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I tried to use the new Geist Mono font ( from Vercel ) , the font is rendered very very thin which is un-readable !

### Environment

the copy dind't work

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2023-11-09 at 20 36 30](https://github.com/zed-industries/community/assets/10274752/3a9bfa41-311b-4175-938e-3bca5acb018b)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/13312609/Zed.log)

**Comment by widersky** [comment]
It's a font issue, not Zed. Download new Geist realease. This is how it's looking for me:

![image](https://github.com/zed-industries/community/assets/45122321/d2529244-4a6f-4fc8-87c2-0209153bdfe3)

https://github.com/vercel/geist-font/issues/15
https://github.com/vercel/geist-font/issues/12

**Comment by enzime4u** [comment]
Just tested and it works smooth ! thank you
