### ISSUE TITLE
Autocomplete makes Zed use 800% CPU

### ISSUE THREAD

**Issue by kwando** [zed-industries/community#2265]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Autocomplete is broken.

Open any project, write something fast like "kjfdsafalasdfjaslk". Watch CPU go 800% and memory is just balooning 11GB now. I think I read there was something done to the autocomplete thingy recently, maybe it is time to revisit that code.

The RPC log is spewing `completionItems/resolve` and I see "dokumentation" from 
```json
{"jsonrpc":"2.0","id":2393,"method":"completionItem/resolve"......
```

I can reproduce this consistently within JS/TS projects, seems to be an issue with elixir too but not as bad.

Edit: https://zed.dev/blog/zed-weekly-23  <-- think this could be the problem :/

### Environment

Zed: v0.112.3 (preview)
OS: macOS 14.0.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

We all know how this is supposed to work :) I mean, superhappy with Zed in general but something is broken with this autocomplete implementation.. maxing out the CPU and chewing memory.

Please let me know how I can assist further.

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by kwando** [comment]
I think it is a little better on the stable channel, butI can easily get zed to chew up several GBs of memory after like 3 minutes use. CPUs also skyrocketing.
```
Zed: v0.111.6 (stable)
OS: macOS 14.0.0
Memory: 64 GiB
Architecture: aarch64
```

**Comment by ForLoveOfCats** [comment]
A fix for this has just gone out! The issue was that we were continuing to resolve documentation for stale or no-longer-visible completion entries as you continued to type, so if there were enough completions, and the server was slow enough, and the user was typing fast enough, they could build up significantly.

Why you were seeing it be better on the stable build we're unsure as it had the same behavior, I'm wondering what else, if anything, might be going on so I'd be curious to hear if you still experience high memory utilization after updating our latest update (preview or stable).

**Comment by kwando** [comment]
Thanks for looking into this! In some cases I got like 30K language server rpc messages before it was done (thank you node_modules).

Just give me a few moments and I'll see if I can break it again 😸 

It might just have been me thinking it was less broken on the stable channel, maybe I just tried it on a smaller project. I do not remember the exact circumstances. I wouldn't stay sleepless over that if were you.

**Comment by kwando** [comment]
geez, someone should revoke my computer license 🤦🏻  it is having the LSP debug panel open that makes Zed go bananas with CPU and RAM.

Anyways, initial testing on preview 0.114.0 looks very promising. I'm will be very happy to move back into Zed again after a brief hiatus in vscode. Keep up the good work!
