### ISSUE TITLE
Assistant panel does not prompt for API Key

### ISSUE THREAD

**Issue by MiAlhazmi** [zed-industries/community#2298]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When I first open the panel, Zed should ask me for an [OpenAI API key], as stated in the documentation. However, the panel is opened for me to type but it's not function.

### Environment

Zed: v0.113.0 (stable)
OS: macOS 14.0.0
Memory: 8 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1222" alt="Screenshot 2023-11-24 at 12 57 54 PM" src="https://github.com/zed-industries/community/assets/66153506/ff3a0886-d40d-47e0-88a0-24a26484aa20">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Huh, this is strange. Not sure what might be going on here. That being said, you can manually bring up the field to enter in the key by focusing on the assistant panel, opening the command palette (`cmd-shift-p`) and running `assistant: reset key`.

**Comment by MiAlhazmi** [comment]
That worked. Thank you!
