### ISSUE TITLE
Rename removes focus if trying to add a whitespace

### ISSUE THREAD

**Issue by porsager** [zed-industries/community#2308]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When renaming a file in the sidebar it's not possible to add a whitespace (it moves focus to the editor).

### Environment

Zed: v0.113.0 (preview)
OS: macOS 14.0.0
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Oh, that's not good at all! Thanks for the report @porsager!

**Comment by JosephTLyons** [comment]
This will be fixed in the next preview release - I'll try to get it out tomorrow.
