### ISSUE TITLE
Project panel doesn't move to right dock

### ISSUE THREAD

**Issue by ZombieHarvester** [zed-industries/community#2342]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Project panel stays in the left dock when sent to the right dock.

I've had it the right dock, after one of the updates it moved back to the left dock and ignores the setting in settings.json. Same behavior in both Stable and Preview

```
  "project_panel": {
    "dock": "right"
  },
```

<img width="579" alt="image" src="https://github.com/zed-industries/community/assets/923510/be3b6a01-a4d1-4d03-b877-fb11327585ee">

### Environment

Zed: v0.116.1 (stable)
OS: macOS 12.7.1
Memory: 16 GiB
Architecture: x86_64

Zed: v0.117.0 (Zed Preview)
OS: macOS 12.7.1
Memory: 16 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @ZombieHarvester, can you paste in your full `settings.json` file, if it doesn't have anything sensitive in it?

**Comment by ZombieHarvester** [comment]
Hey @JosephTLyons 

I started removing entries from the settings.json and the offending part was the ruby language server. One I removed it, every other setting went into effect and the doc moved to the right.

## offending entry

```
  {
    "lsp": {
      "solargraph": {
        "initialization_options": {
          "diagnostics": true,
          "formatting": true
        }
      }
    }
  }
```

## Full settings.json

// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "terminal": {
    "dock": "right"
  },
  "project_panel": {
    "dock": "right"
  },
  "telemetry": {
    "metrics": true
  },
  "theme": "Ayu Dark",
  "base_keymap": "SublimeText",
  "buffer_font_size": 17,
  "tab_size": 2,
  "format_on_save": "off",
  // "buffer_font_family": "JetBrains Mono",
  // "buffer_font_family": "Fira Code",
  "buffer_font_family": "Monaspace Neon",
  // The OpenType features to enable for text in the editor.
  "buffer_font_features": {
    // Disable ligatures:
    // "calt": false
  },
  {
    "lsp": {
      "solargraph": {
        "initialization_options": {
          "diagnostics": true,
          "formatting": true
        }
      }
    }
  }
}

**Comment by JosephTLyons** [comment]
Hey @ZombieHarvester, I think there might've been some extra `{` and `}`, try this snippet out:

```json
// Zed settings
//
// For information on how to configure Zed, see the Zed
// documentation: https://zed.dev/docs/configuring-zed
//
// To see all of Zed's default settings without changing your
// custom settings, run the `open default settings` command
// from the command palette or from `Zed` application menu.
{
  "terminal": {
    "dock": "right"
  },
  "project_panel": {
    "dock": "right"
  },
  "telemetry": {
    "metrics": true
  },
  "theme": "Ayu Dark",
  "base_keymap": "SublimeText",
  "buffer_font_size": 17,
  "tab_size": 2,
  "format_on_save": "off",
  // "buffer_font_family": "JetBrains Mono",
  // "buffer_font_family": "Fira Code",
  "buffer_font_family": "Monaspace Neon",
  // The OpenType features to enable for text in the editor.
  "buffer_font_features": {
    // Disable ligatures:
    // "calt": false
  },
  "lsp": {
    "solargraph": {
      "initialization_options": {
        "diagnostics": true,
        "formatting": true
      }
    }
  }
}
```

**Comment by ZombieHarvester** [comment]
Thanks a lot @JosephTLyons! Closing the issue
