### ISSUE TITLE
Vim mode escape do not work as expected - you need to type it twice

### ISSUE THREAD

**Issue by websmithcode** [zed-industries/community#2356]
## Check for existing issues
- [x] Completed

## Steps to reproduce the issue:
Go in visual block mode with shift + v
select some line with k or j
trying to escape vim mode with escape
it don't work you need to type escape twice to exist
The is the same issue with other kind of vim mode.

## Trouble with 
```JSON
{
  "context": "Editor",
  "bindings": {
      // "escape": "editor::Cancel",
      "..."
  }
}
```
From default keybindings config.
If I comment out this binding - it's working.

## Environment
Zed: v0.117.0 
OS: macOS 14.2.1 (Sonoma)
Memory: 16 GiB
Architecture: aarch64

## If applicable, add mockups / screenshots to help explain present your vision of the feature
Video showing the issue: https://share.cleanshot.com/bsCBLLKc

> Very weird! Thank you for following up.
> I'm going to close this for now, but if you get into this state again, let's take a look in that folder together.

_Originally posted by @ConradIrwin in https://github.com/zed-industries/community/issues/2127#issuecomment-1771198220_

**Comment by ConradIrwin** [comment]
@websmithcode do you have any custom keybindings bound to escape? It should work with the keybindings that ship with zed by default (as the vim binding takes priority over the default escape you call out here).

**Comment by websmithcode** [comment]
I think I understand what’s going on) 
I copied the default config to mine and changed it there.
In theory, it has even higher priority and should be used as a top layer for reassignment... 
Right?)

**Comment by ConradIrwin** [comment]
That seems likely; the way that keybindings are selected in ambiguous contexts is not super well defined (but it is guaranteed to be consistent).

going to close this for now, and suggest deleting the `"esc"` binding as you have done.
