### ISSUE TITLE
Arrow key text navigation doesn't work in GPUI 2

### ISSUE THREAD

**Issue by joeldrapper** [zed-industries/community#2362]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

- Open Zed
- Select a file
- Click to place cursor in the file
- Arrow keys do not navigate

### Environment

14.1.2 (23B2091)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by JosephTLyons** [comment]
Hey @joeldrapper, we've had a bunch of users identify issues with keys not working. It turns out, this only affects users who never added a custom keymap, and everyone on the team has custom bindings, so we missed it. We are working on a fix for this right now and will have a patch out ASAP.

**Comment by joeldrapper** [comment]
Looks like you fixed it in the last release.

**Comment by JosephTLyons** [comment]
Hey @joeldrapper, did you get a chance to try it? Does it work for you now?

**Comment by joeldrapper** [comment]
Yes, it's great!
