### ISSUE TITLE
New Zed version just shows a blank magenta window

### ISSUE THREAD

**Issue by joshuawarner32** [zed-industries/community#2366]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

* Download current zed version (0.118.1, according to the Info.plist)
* Move to /Applications
* Open Zed.app
* Behold; magenta screen

### Environment

(can't run a command palette action, since I can't see anything in the zed window!)

I'm on a M1 macbook air / 16GB ram / macos 13.4.1 (c) (22F770820d)

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="1440" alt="Screenshot 2024-01-04 at 15 19 55" src="https://github.com/zed-industries/community/assets/182686/3132a00c-7603-429d-8c63-629e016d58c0">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[Zed.log](https://github.com/zed-industries/community/files/13836322/Zed.log)

**Comment by maxbrunsfeld** [comment]
@joshuawarner32 Thanks for the report, and sorry for the truly bizarre experience. Does [Zed 0.117.0](https://zed.dev/api/releases/stable/0.117.0/Zed.dmg) have this problem for you?

**Comment by joshuawarner32** [comment]
I _think_ I had just gotten an update, so I assume I was previously on 0.117 (or maybe one more version back, but I've been keeping up pretty closely with the new releases).

Anyway... I just decided to try to simple thing of turn-it-off-and-turn-it-back-on-again (the computer, that is) - and... I can no longer repro.

I kinda suspect there may have been some corrupted state in the video driver or something. It's perhaps mildly interesting that no _other_ apps seemed to be misbehaving like this. Maybe zed is the only thing that touches whatever state was corrupted? Probably not important. I'll re-open if I can somehow find a repro.

Sorry for the noise, and thanks for making a cool editor. 😄
