### ISSUE TITLE
Logged out every time Zed Preview is closed

### ISSUE THREAD

**Issue by Moshyfawn** [zed-industries/community#2382]
### Check for existing issues

- [X] Completed

### Describe the feature that was lost

Zed Stable restores your GitHub auth sessions, unlike Zed Preview, which requires you to log in every time you open the IDE.

### If applicable, add screenshots of gpui-1 Zed to show the missing feature

https://github.com/zed-industries/community/assets/16290753/ae1c2f9b-84e7-44bb-9001-de7d12b2fe36

**Comment by Moshyfawn** [comment]
I haven't confirmed this yet, but it seems that Zed Preview didn't ask me to install Apple Keychain access, which led to the behaviour seen in this issue. After installing Zed Beta and allowing keychain access, Zed Preview is also able to log in on startup.

**Comment by JosephTLyons** [comment]
@Moshyfawn - yep! We tracked this down and put out a release that fixed this (although, I think we might've forgotten to put it in the release notes) - exactly as you say, Zed wasn't putting the info in Keychain.

**Comment by JosephTLyons** [comment]
Updated the [release notes for v0.119.8](https://zed.dev/releases/preview/0.119.8) to include this.
