### ISSUE TITLE
Autocompletion item is covered by completion details

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#2419]
### Check for existing issues

- [X] Completed

### Describe the regression

(Reported by a user in Discord)

### If necessary, add screenshots of gpui-1 Zed to show the missing feature

Preview

![image](https://github.com/zed-industries/community/assets/19867440/13deb143-4e3b-49b0-92af-4e688c8b29ec)

Stable

![image](https://github.com/zed-industries/community/assets/19867440/24c60b89-aecd-48c6-84fe-afc9796854a6)

**Comment by RemcoSmitsDev** [comment]
This might be related, the following items are on top of each other.

```
String
``` 
&
```
Extract into variable
``` 

<img width="236" alt="Screenshot 2024-01-17 at 15 39 01" src="https://github.com/zed-industries/community/assets/62463826/68b919d4-f762-4969-bd36-2f8d651ce5e3">

**Comment by ConradIrwin** [comment]
Thanks for reporting! This will be fixed in the preview release later today

**Comment by JosephTLyons** [comment]
This should be shipped in [v0.119.16-pre](https://zed.dev/releases/preview/0.119.16).
