### ISSUE TITLE
I can go back,but can't go forward

### ISSUE THREAD

**Issue by 0x2CA** [zed-industries/community#2428]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://github.com/zed-industries/community/assets/19868292/8dc5eba4-61d1-42ee-83a6-83d436b08b35

### Environment

Zed: v0.119.11 (Zed Preview)
OS: macOS 14.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by RemcoSmitsDev** [comment]
This is fixed in 0.119.12
