### ISSUE TITLE
Code folding UI support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#250]
**Is your feature request related to a problem? Please describe.**
It would be nice to able to fold / unfold lines of code via some button in the UI.

**Describe the solution you'd like**
Probably something similar to other editors, but having some button in the gutter, but any mechanism would work really.

**Comment by lukeed** [comment]
Ideally would pair with #667 so that you can fold blocks that aren't top-level.

Zed is already capable of this via `editor::Fold` and `editor::UnfoldLines`

**Comment by SilentGlasses** [comment]
For simplicity sake, can we bring this discussion into #667 and close this issue out? 

It's very confusing to have to navigate three issues for the same topic and devs end up with more menial work having to follow the discussion in multiple places.

**Comment by d12bb** [comment]
I just learned from this issue that Zed already is capable of folding, so a big +1 from me for making it more obvious. For syntax/indention-based folding, I really like the way Xcode does it, the clickable area spans the whole section which would get folded, that makes a much easier to click mouse target than one tiny arrow.

**Comment by JosephTLyons** [comment]
This should be available in v0.76.0.
