### ISSUE TITLE
Built-in settings/keymaps sync feature

### ISSUE THREAD

**Issue by zongUMR** [zed-industries/community#265]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think it will be great for zed to add a built-in settings/keymap sync. For sublime text users, we can download a [plugin](https://packagecontrol.io/packages/Sync%20Settings) and use it to sync the settings on the GitHub Gist. I think zed can also do it but with the built-in feature.

**Describe alternatives you've considered**
Upload, sync, and download the settings from the gist so we don't need to manually configure it everywhere.

**Screenshots**
If applicable, add mockups / screenshots to help explain present your vision of the feature.

**Comment by maraisr** [comment]
It already has a backing server powering the collaboration feature, and so the stitching to GitHub also already done. 

So for sure first class settings sync, would be sick! 

I use 2 machines, work and personal laptop, would be sick to have the setting synced, and possibly also a "workspace" specific settings too? 🤔

**Comment by zongUMR** [comment]
Emm. I don't understand why the sync will be sick. Sync the settings between the devices will be convenient for people who have more than one computer.

**Comment by JosephTLyons** [comment]
I decided to open a discussion post about what all we should include in a future settings sync feature:

- https://github.com/zed-industries/community/discussions/956

**Comment by zongUMR** [comment]
close it due to the discussion for it.
