### ISSUE TITLE
Git MVP integration (at least `git status` in the tree view)

### ISSUE THREAD

**Issue by fdionisi** [zed-industries/community#29]
**Is your feature request related to a problem? Please describe.**
I get that git integration is probably a massive epic to implement, but starting with some basic visual aid would be great to understand where a project stands (at least until #21).

**Describe the solution you'd like**
After creating or editing a file would be great to have some visual feedback in the tree view (i.e. as VS Code does), so that you know which file was added/edited (especially when opening a project on a new working day 😬).

<img width="286" alt="Screenshot 2022-06-09 at 22 07 59" src="https://user-images.githubusercontent.com/8927326/172944727-d64bad47-153e-4d88-b5f2-2f330773c428.png">

**Describe alternatives you've considered**
The other alternative I can think of is opening the terminal and entering `git status`, which would be fine if it was integrated into Zed.

**Comment by JosephTLyons** [comment]
Really missing being able to tell what lines have been added/changed/deleted.  I don't really need to know much else within the editor itself, but I think its valuable being able to see that, in addition to states of files, as mentioned in the original post.

**Comment by JosephTLyons** [comment]
While we haven't added any support to show changes files in the file tree, Zed now has a Git gutter in v0.59.0!  The team worked really hard on this - really excited to have this feature.

🎉

**Comment by fdionisi** [comment]
From a colleague of mine: _"what prevents me from fully switching to Zed is the ability to have comprehensive git diffs in the UI"_ (see screenshot). 

<img width="1184" alt="Screenshot 2022-12-16 at 20 15 11" src="https://user-images.githubusercontent.com/8927326/208172123-4950206e-a282-4c47-8204-3ad08ad65bfb.png">

**Comment by JosephTLyons** [comment]
> From a colleague of mine: _"what prevents me from fully switching to Zed is the ability to have comprehensive git diffs in the UI"_ (see screenshot). 
> 
> 
> 
> <img width="1184" alt="Screenshot 2022-12-16 at 20 15 11" src="https://user-images.githubusercontent.com/8927326/208172123-4950206e-a282-4c47-8204-3ad08ad65bfb.png">
> 
> 

We'll be working on more git features in the near future! :)

**Comment by tfantina** [comment]
I know there are about 100 things that are "top priorities" at this point. I'm using Zed about 90% of the time the other 10% I use something so I can see blame.

**Comment by 0x2CA** [comment]
Whether the svn is also integrated?

**Comment by krstp** [comment]
What often works for me with Sublime is `git diff HEAD^1 | sublime`, which does exactly what  @JosephTLyons shows. If piping from CLI could be supported then I guess SYNTAX HIGHLIGHTING on `git diff` should do the trick.

The same cannot be accomplished in ZED as it does not support piping from CLI.
BTW. The lack of piping is somewhat related to #1314 (CLI file opening) and - stretching it along the lines of file-operations- to  #1317 (drag'n'drop file).

**Comment by SilentGlasses** [comment]
Pulsar has some good git features that Zed could check out, like integrated git actions
<img width="394" alt="Screenshot" src="https://user-images.githubusercontent.com/22822565/231212792-d3f88600-94f7-421d-95e3-c2cedad74775.png">

**Comment by cktang88** [comment]
Can we also have git blame inline like in https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens#current-line-blame

**Comment by krstp** [comment]
Related: https://github.com/zed-industries/community/issues/1441#issuecomment-1517256981

**Comment by JosephTLyons** [comment]
We are working on this now!

**Comment by mikayla-maki** [comment]
This should be implemented by 0.87 or 0.88 :)

**Comment by laike9m** [comment]
Apologize for the question, but how do I open a git diff view? I didn't seem to find such commands.

**Comment by JosephTLyons** [comment]
> Apologize for the question, but how do I open a git diff view? I didn't seem to find such commands.

We don't have a git diff view at the moment.

**Comment by matthewgapp** [comment]
> > Apologize for the question, but how do I open a git diff view? I didn't seem to find such commands.
> 
> We don't have a git diff view at the moment, but it is on the TODO list.

Can you provide any detail on its relative priority and/or when we could expect the first version of the diff view?

**Comment by krstp** [comment]
Seriously, as as intermediate solution I would love to be able to pipe: `git diff | zed`. Then if Zed could have `diff` highlighting that would change a lot. Currently piping does not work 😞 
PS. I am mixing subjects now, but having `Makefile` and `Dockerfile` highlighting would help too... sure we can always use `shell` highlighting, but it is somewhat modest.

**Comment by laike9m** [comment]
@JosephTLyons Thanks. Is there a tracing issue that I can follow?

**Comment by JosephTLyons** [comment]
> @JosephTLyons Thanks. Is there a tracing issue that I can follow?

Here's a community issue that is starting to get some upvotes (👍).
