### ISSUE TITLE
Reveal in macOS Finder.app

### ISSUE THREAD

**Issue by exalted** [zed-industries/community#3]
I wish I could “right click” and “Reveal in Finder” any file

**Comment by JosephTLyons** [comment]
Additionally, having a command to reveal the file of the currently-focused editor in finder would be awesome too.

**Comment by petros** [comment]
This will go out in an upcoming release. We have implemented a "Reveal in Finder" option for the items of the project panel.

> Additionally, having a command to reveal the file of the currently-focused editor in finder would be awesome too.

This is also a great idea, which we could look into at some point.

**Comment by exalted** [comment]
🙇 Thanks!

**Comment by jansol** [comment]
Might also be nice to have this in the editor tab context menu for files outside the workspace (e.g. the Zed config file)
