### ISSUE TITLE
GitHub Copilot Support

### ISSUE THREAD

**Issue by thepolarbear0818** [zed-industries/community#301]
Adding in GitHub Copilot support

**Comment by und3fined** [comment]
@thepolarbear0818 I think it's hard go to with zed.

Microsoft acquires GitHub, Microsft born VSCode. VSCode and Zed can be rivals 😂

**Comment by corysm1th** [comment]
Copilot works with both vs code and vim. There is an open feature request to build an extension system. It might be possible to satisfy the needed parts of the interface to use one of the existing plugins from the other editors.

**Comment by sualehasif** [comment]
This is so important. It is impossible to use without it :( It would be great if you could just open up the LSPprotocol and we could connect copilot ourself.

**Comment by lazovicff** [comment]
Github Copilot is becoming more relevant. Been using Zed for the past few months, but this feature would be crucial for me and my team in the near future

**Comment by moshe-blox** [comment]
Zed's target audience is people who like to try new things, and those people are likely to have already tried Copilot and are now addicted 🤭

LLM-assisted coding is slowly becoming the standard. Supporting GitHub Copilot (and it's future competitors) should be a top priority.

**Comment by zippoxer** [comment]
ed's target audience is people who like to try new things, and those people are likely to have already tried Copilot and are now addicted 🤭

LLM-assisted coding is slowly becoming the standard. Supporting GitHub Copilot (and it's future competitors) should be a top priority.

I do love everything else about Zed though ❤️

**Comment by alanhamlett** [comment]
This depends on #388.

**Comment by LeeeSe** [comment]
Please consider add "codeium" 
Same as Copilot but free for personal!

**Comment by pms1969** [comment]
I already view Zed as a productivity gain when writiing Rust.  Copilot is another one of those things that steepens the productivity curve. Me personally, I'd be super focused on this integration. Not having it will be a reason for some not to use it, having it will improve the experience for those who use such tools and like Zed.
I'm very excited for the future of Zed.  I've tried a few editors of late in the hope I can move off of VSCode, and Zed is by far the best option at present (at least for Mac's). You're doing a wonderful job, and I wish you all the best in future. Thanks for all your hard work.

**Comment by JosephTLyons** [comment]
Hey all, I just wanted to mention that we are prioritizing adding Copilot support to Zed.

**Comment by exalted** [comment]
LOL. Now there's also [GitHub Copilot X](https://github.com/features/preview/copilot-x).

**Comment by iolsen** [comment]
👋 Hey folks I'm one of the engineering managers working on Copilot at GitHub, and I'm really excited to see this happen! Daniel (@dipree) is a PM on the GitHub Copilot team I wanted to introduce, as he's also interested in helping out.

**Comment by cktang88** [comment]
Just out of curiosity, would the timeline for Copilot support look like a few months or more like towards end of 2023?

**Comment by JosephTLyons** [comment]
> Just out of curiosity, would the timeline for Copilot support look like a few months or more like towards end of 2023?

If all goes smoothly, likely in the realm of weeks.

**Comment by Ulisses1478** [comment]
Good news that zed is still very active, this is the only main flaw I can't sacrifice to use zed 100% as my only code editor

**Comment by mikayla-maki** [comment]
Released today :)

**Comment by JosephTLyons** [comment]
Congrats to the team members that worked on this @mikayla-maki @as-cii - feels great to close out the highest-ranked user issue!

**Comment by vuon9** [comment]
Thanks for the great work!!
