### ISSUE TITLE
Configurable line height

### ISSUE THREAD

**Issue by ijzerbroot** [zed-industries/community#304]
Hello!

It appears the line height/spacing is currently not configurable (or I missed it). There's a bit too much spacing for my tastes.
In case it's indeed not yet implemented, could you consider this ?

**Comment by johnm** [comment]
FWIW, this may seem like a little thing but tweaking this along with typefaces can make a big difference for some folks with some visual issues.

**Comment by telmogoncalves** [comment]
Any plans to get this available?

**Comment by nicolasparada** [comment]
I would really a appreciate to have this option. Everything is too cramped to really use zed everyday.

**Comment by pim** [comment]
I'd really appreciate having this option too!

**Comment by shariffff** [comment]
+1

**Comment by spaceexperiment** [comment]
Would love for this to be implemented as well, currenly the editor line consumes a bit too much space.

**Comment by krstp** [comment]
Not only the line height, but probably something like this would serve well:
```
    "line_padding_bottom": -2,
    "line_padding_top": -2,
```
which from
![Screenshot 2023-04-05 at 9 29 20 PM](https://user-images.githubusercontent.com/4711498/230257262-909cb904-a0c4-4296-a726-4ac10e42d96b.png)
goes to
![Screenshot 2023-04-05 at 9 29 36 PM](https://user-images.githubusercontent.com/4711498/230257275-d8bbe6ac-758f-4c38-956e-a0cf8b858af2.png)

**Comment by krstp** [comment]
This option is really the main blocker that keeps me away from Zed :(  I totally love Zed, but that huge spacing for a holly ghost between each line really makes almost everyday go back to Sublime to sort code-stuff out.

**Comment by liebkne** [comment]
@krstp Same experience :)

**Comment by krstp** [comment]
I see in latest update the line-spacing has been sorted out for the terminal window 🤝 , but not for the editor itself :( maybe I am mistaken, but the way it seems to me it should be somewhat the same logic behind it (or at least from design standpoint I would assume this is the way it should be). Thanks again team for those updates.

**Comment by liebkne** [comment]
@krstp Much better with `"standard"` now! Thank you!

**Comment by spaceexperiment** [comment]
wait, so they just implemented it for terminal and not the editor?

**Comment by telmogoncalves** [comment]
@spaceexperiment yeah, looks like it.

**Comment by daguitosama** [comment]
Hi there Folks, looks like some people want to get tidy, and others like me want to get loose with the line height, I think this is a very special setting for the user. In my case, adding more height to the line gives more room to breath, and more room to look for the detail. I know there is a lot of things going on on the Todos, but this one is really a bummer, maybe not so hard to get it goin.

This is a sample of how I roll with VS, so far i have been enjoying using and learning Zed, it would be really nice if I can keep my code as confortable as posible, Line Height is big factor.

<img width="934" alt="Screenshot 2023-06-02 at 00 14 34" src="https://github.com/zed-industries/community/assets/34744883/0d490b3d-3839-4077-9a6d-bcb0507e252c">

**Comment by mikayla-maki** [comment]
> it would be useful to have a separate setting for this in the terminal as well, sometime I run interactive CLI tools that use box drawing and this does not look good right now: <img alt="image" width="106" src="https://user-images.githubusercontent.com/891/248912707-24873cef-4ef9-411d-83d5-f6a19943375f.png">

This exists! Try:

```json
// Other settings
"terminal": {
  "line_height": "standard"
}
```

**Comment by telmogoncalves** [comment]
How is this still not an option?

**Comment by cellobestime** [comment]
Any plans to get this available? The fancy things, such as AI assistants, seem to have a higher priority than the top-ranking issues...

**Comment by lovenic** [comment]
`line_height` is the only thing that keeps me from using Zed. could you please add it? 🙏

**Comment by daguitosama** [comment]
Came on guys, at this point is *silly* to not hook up the internal `line_height` param of the renderer to a  parsed value from the config. 😂

**Comment by krstp** [comment]
Seriously, I am generally only waiting for this line_height to switch to Zed :) TBH, I would have thought features like that take priority over Copilot etc., but ¯\_(ツ)_/¯ Either way, this feature would be highly welcomed(!).

**Comment by mikayla-maki** [comment]
Should be released by 0.97

**Comment by krstp** [comment]
Many thanks for making Zed Preview accessible to the general public!
On this note, there is `0.96.0` version that introduces `buffer_line_height`, however it seems it only accepts `null` as the value. Any other numeric value results in incorrectly read config `json` file. FYI.

**Comment by mkismy** [comment]
@krstp 
The error tooltip indicates that valid values are either `comfortable` or `standard` and not a number.  `comfortable` seems to be the default value and `standard` to be narrow.

@mikayla-maki 
It definitely is a step forward for those who want a narrow line height but there's still lack of "comfort". 
I am also the person who want the lines to be as comfortable as possible like daguitosama said in https://github.com/zed-industries/community/issues/304#issuecomment-1573125105

I can understand your decision of not allowing the value numeric but can you at least make it more comfortable for `comfortable`?

FYI this is my line height settings in VSCode and Sublime:

|VSCode|Sublime|
|:--|:--|
|<img width="435" alt="image" src="https://github.com/zed-industries/community/assets/8445575/aa190170-e9b6-4003-80ce-c63d432457ee">|<img width="370" alt="image" src="https://github.com/zed-industries/community/assets/8445575/65dd938b-f78a-42ce-ae8c-ea5365edef5b">|

**Comment by krstp** [comment]
This is wonderful, really changes the experience. Thanks for that. Any option we could get `0.9` height? Currently it will default to `1.0`. Thanks.
