### ISSUE TITLE
Show whitespace/invisibles

### ISSUE THREAD

**Issue by Daeraxa** [zed-industries/community#308]
It would be nice if Zed could display whitespace characters/invisibles. 
I find this really useful when editing documentation and reviewing certain types of log files so is often left on.

Atom has settings for showing whitespace characters/invisibles (Editor > Invisibles) where visible types of whitespace can be identified. This is also present in other editors (Notepad++, VSCode).

I like the amount of flexibility provided by Atom to change the character displayed for each whitespace "type" but personally I've never changed it from the default.
If implemented it would be nice to toggle from the command palette rather than setting in the options, again like in Atom `Window: Toggle invisibles`

![image](https://user-images.githubusercontent.com/58074586/179065112-fb3460e6-8dbf-4597-8c75-f5908bb74b96.png)
![image](https://user-images.githubusercontent.com/58074586/179065287-44edbfad-17af-4322-ae88-21832c021c81.png)

**Comment by cktang88** [comment]
Yes especially in Python or other whitespace languages, being able to see tabs vs spaces is very important

**Comment by JosephTLyons** [comment]
We are landing some support for this in v0.86.0.  I'm going to close this for now.  If there are additional requests for more additions after, feel free to open up a new issue.

**Comment by potomak** [comment]
I tried to add this setting on a language override, but it doesn't work.

My `settings.json`:

```
{
  "telemetry": {
    "metrics": false
  },
  "buffer_font_size": 15,
  "language_overrides": {
    "Markdown": {
      "tab_size": 2,
      "show_whitespaces": "all"
    }
  }
}

```

**Comment by SomeoneToIgnore** [comment]
It's a global, editor setting that's supposed to be in the root of the settings, something like this:

```
{
    "features": {
        "copilot": true
    },
    "theme": "Ayu Mirage",
    "format_on_save": "on",
    "show_whitespaces": "all",
    "soft_wrap": "editor_width",
    "tab_size": 4
}
```

**Comment by potomak** [comment]
Yes, I tried it as a global setting and it works as expected there. This was just a feedback in case this is also supposed to work as a language setting. Example: I care about white spaces in Python and Markdown, but not elsewhere.

I would also like to report that it would be useful to surface configuration errors, like settings not supported by the schema.
