### ISSUE TITLE
Nushell Script Support

### ISSUE THREAD

**Issue by redoxeon** [zed-industries/community#331]
**Is your feature request related to a problem? Please describe.**
No syntax highlighting for Nushell script files

**Describe the solution you'd like**
Nushell script syntax highlighting and general language support (see [nushell.sh](https://www.nushell.sh/))

**Describe alternatives you've considered**
For now just dealing or just using another editor.

**Comment by JosephTLyons** [comment]
Mikayla landed syntax highlighting for `.nu` files last week and it should be in the new preview release going out later on today (v0.104.0). We haven't added any language server support - feel free to open a new issue to track that request if you'd like.
