### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by aiakared** [zed-industries/community#335]
~~Vue has an official language server [here](https://github.com/vuejs/vetur/tree/master/server).~~

Update: it seems like Volar was made into a framework agnostic language framework(?). The official Vue language tools are in [vuejs/language-tools](https://github.com/vuejs/language-tools) with the LSP in [packages/vue-language-server](https://github.com/vuejs/language-tools/tree/master/packages/vue-language-server).

**Comment by aleksrutins** [comment]
I think [Volar](https://github.com/johnsoncodehk/volar) would probably a better choice; see https://github.com/johnsoncodehk/volar/discussions/583.

**Comment by Zenkylo** [comment]
Can anyone elaborate or point to how to set up a language server, in this case for Vue? I've gone through the Volar docs and it's still unclear. Would love to get this going but almost all my projects are Vue.

**Comment by ElYaiko** [comment]
Any chance of using Volar?

**Comment by d1y** [comment]
In the constant expectation, I love and hate vscode, but zed is a fun editor😁

**Comment by vallemar** [comment]
+1

**Comment by emilianomaccaferri** [comment]
+1

**Comment by cisolarix** [comment]
+1

**Comment by aiakared** [comment]
> I think [Volar](https://github.com/johnsoncodehk/volar) would probably a better choice; see [vuejs/language-tools#583](https://github.com/vuejs/language-tools/discussions/583).

> Any chance of using Volar?

> Same looking for a way to use Volar.


Updated the original issue with what seems to be the latest and recommended Vue tooling? To be honest I'm not 100% sure because it seems to have changed a bit and this isn't my area of expertise, if anyone knows anything more please feel free to correct me!

And as a side note if you're looking to bump this issue please react with a 👍 on the original instead of a +1 comment. The reaction pushes it up in the top ranking issues which gives it more visibility :) (and doesn't clutter my email inbox lol)

**Comment by icarusgk** [comment]
Yes, Volar is the latest and recommended Vue tooling! 😄 
This is the current VS Code extension: https://marketplace.visualstudio.com/items?itemName=Vue.volar 

More on the [framework-agnostic](https://blog.vuejs.org/posts/volar-a-new-beginning) note

**Comment by reynardleeyy** [comment]
Hope this is soon!!!

**Comment by rafiahmedd** [comment]
+1

**Comment by nkb-bd** [comment]
+1

**Comment by boring-dragon** [comment]
+1

**Comment by StefKors** [comment]
+1

**Comment by jakubziemba** [comment]
+1

**Comment by ali322** [comment]
+1, any updated?

**Comment by JosephTLyons** [comment]
We currently have a few members of the team on a subteam that is working on improving web dev support within Zed and we are talking about baking Vue support in.  I'll update again when I have more info on when this might be happening.

**Comment by icarusgk** [comment]
Thank you for the update! 😄

**Comment by varjmes** [comment]
> We currently have a few members of the team on a subteam that is working on improving web dev support within Zed and we are talking about baking Vue support in. I'll update again when I have more info on when this might be happening.

Nice! Is there anywhere we can see what this subteam is working on wrt to improved web dev support in general?

**Comment by ssly** [comment]
> We currently have a few members of the team on a subteam that is working on improving web dev support within Zed and we are talking about baking Vue support in. I'll update again when I have more info on when this might be happening.

Hello, the front-end language vue is a very popular programming language in China. I hope it can be supported as soon as possible. If you consider that the browser is popular among the huge developers in China

**Comment by augustjourney** [comment]
+1

**Comment by RomainLanz** [comment]
Can this issue be locked @JosephTLyons? 
I see no point in people bumping it when there was a proper answer on your side.
**All we have to do is wait.**

**Comment by ssly** [comment]
It has been a week since the last suggestion to join vue. There seems to be no reply or situation. In today's update, I still don't see support for vue. Can I understand that this editor is not intended to be provided to front-end development engineers? What to use? As a popular front-end framework with more stars than React, so many versions have not yet been urgently supported. This editor is really disappointing. Can it be compared with vscode and sublime text for its slow support for Vue syntax?

**Comment by so1ve** [comment]
I'd say zed should **NOT** provide vue support by itself. Vue team has an official language server implementation (https://github.com/vuejs/language-tools), which is widely used, and recommended by vue team. Implementing another vue language server in zed might lead to much more work and may not catch-up some newly added features. For me, I think the best way to support vue is provide a plugin interface (already discussed in another issue) and allow it providing lsp support. A limited plugin interface is enough, we can leave features like window customizations alone at first, but LSP support should be prioritized - so that many languages can be supported by the community

**Comment by aiakared** [comment]
> I'd say zed should **NOT** provide vue support by itself. Vue team has an official language server implementation (https://github.com/vuejs/language-tools), which is widely used, and recommended by vue team. Implementing another vue language server in zed might lead to much more work and may not catch-up some newly added features. For me, I think the best way to support vue is providing a plugin interface (already discussed in another issue) and allow it providing lsp support. A limited plugin interface is enough, we can leave features like window customizations alone at first, but LSP support should be prioritized - so that many languages can be supported by the community.

I don't think the Zed team has the resources nor the intent to roll their own language server from scratch for every supported language. As far as I'm aware they already use existing language servers for all supported languages and ask for existing ones when you are creating a new language support ticket. @JosephTLyons or another team member can correct me if I'm wrong (which I very well might be), but by "baking Vue support in" I think they mean adding native syntax highlighting via Tree-sitter and automatic downloading & integration of the latest version of the existing Vue language server. I agree minimal support for plugins for this purpose would help immensely and should be a priority, but that isn't the purpose of this specific issue.


> It has been a week since the last suggestion to join vue. There seems to be no reply or situation. In today's update, I still don't see support for vue. Can I understand that this editor is not intended to be provided to front-end development engineers? What to use? As a popular front-end framework with more stars than React, so many versions have not yet been urgently supported. This editor is really disappointing. Can it be compared with vscode and sublime text for its slow support for Vue syntax?

Please don't harass or berate the Zed team for support, it won't help with getting support any faster. Creating an entire text editor from scratch with the level of quality Zed is aiming for is a herculean task and I'm sure they have their hands full with many other more pressing issues. If you want to show support for this issue please react to the original issue with a 👍.

> Can this issue be locked @JosephTLyons? I see no point in people bumping it when there was a proper answer on your side. **All we have to do is wait.**

I would've locked this issue a while ago if I could. While I appreciate all the support for the issue and the helpful comments informing me and the Zed team about the state of Vue tooling and how best to support it, I'm honestly tired of getting "+1" comment notifications.

Thank you everyone above for showing interest in this issue, I'm sure the Zed team is hard at work trying to get support for Vue and general language plugins released ASAP. All we can do now is wait for an update and show them our support in the meantime ❤️

**Comment by JosephTLyons** [comment]
> I don't think the Zed team has the resources nor the intent to roll their own language server from scratch for every supported language. As far as I'm aware they already use existing language servers for all supported languages and ask for existing ones when you are creating a new language support ticket. @JosephTLyons or another team member can correct me if I'm wrong (which I very well might be), but by "baking Vue support in" I think they mean adding native syntax highlighting via Tree-sitter and automatic downloading & integration of the latest version of the existing Vue language server. I agree minimal support for plugins for this purpose would help immensely and should be a priority, but that isn't the purpose of this specific issue.

Yes, this is correct.  We are not building any language servers from scratch, we simply have an internal mechanism that downloads and updates existing ones.  At some point, we will have a plugin system that will handle this.  But for now, we are racing to get everything in place for us to go open source, so users can jump in and help out with development.

> Please don't harass or berate the Zed team for support, it won't help with getting support any faster. Creating an entire text editor from scratch with the level of quality Zed is aiming for is a herculean task and I'm sure they have their hands full with many other more pressing issues. If you want to show support for this issue please react to the original issue with a 👍.

Thank you, the team working on web dev stuff took a detour to work on some performance related issues, but I believe the goal is to get Vue in after that.  Keeping the community up to date with a fast-changing schedule changes is always challenging, and nothing is ever set in stone with a project this massive, but we know Vue is important and we are still aiming to add it directly.

> I would've locked this issue a while ago if I could. While I appreciate all the support for the issue and the helpful comments informing me and the Zed team about the state of Vue tooling and how best to support it, I'm honestly tired of getting "+1" comment notifications.

I could lock the issue, but it would prevent other users from upvoting.  Maybe that's ok here, since in theory, we will be adding Vue soon, but I also want to leave room for the idea that it could be pushed back again, if something else urgent comes up.

**Comment by JosephTLyons** [comment]
Piotr posted about his work on Vue this week:

https://zed.dev/blog/zed-weekly-22#piotr

**Comment by admench** [comment]
> Piotr posted about his work on Vue this week:
> 
> https://zed.dev/blog/zed-weekly-22#piotr

This is fantastic. I'm loving using Zed, and as a Front End web developer, if you can integrate Vue's volar language framework into Zed, this will be excellent news. Keep up the great work 👍🏼

**Comment by aiakared** [comment]
Vue is supported now in 0.109.1 🥳

https://zed.dev/releases/stable#zed-0.109.1
