### ISSUE TITLE
Action to "restart" Zed

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#36]
I'm not sure how feasible it is, but having an action that closes Zed and reopens it would be nice.  It could be displayed somehow after an update, so the user wouldn't have to manually close and open Zed, and it could potentially be registered as a Command Palette action, if there would ever be a reason an individual would want to restart Zed.

**Comment by maxbrunsfeld** [comment]
* Clicking "Restart to update Zed" should restart Zed
* Clicking "Upgrade to collaborate" should initiate a check for updates

**Comment by mikayla-maki** [comment]
This will be out in a few releases
