### ISSUE TITLE
Switch window feature

### ISSUE THREAD

**Issue by mgiachetti** [zed-industries/community#362]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I always have a lot of windows with different projects open, finding the correct window is slow.

### Describe the solution you'd like

I'd love to have something like Switch Window in VSCode when you press the shortcut and a search bar appears with opened windows.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/1557575/179981879-2e542f11-57c2-49e2-a65f-d6bd6ae043c7.png">

**Comment by JosephTLyons** [comment]
We now have a Recent Projects picker that is deploy via `opt-cmd-o`.  This is used for opening projects that were recently opened, but it also works for focusing on an already-opened window.  I think this cover the needs here; the only real difference is that the Recent Projects picker will show than just the currently open windows.

**Comment by mgiachetti** [comment]
Even better. Thats awesome!

**Comment by JosephTLyons** [comment]
> Even better. Thats awesome!

I think we may put some sort of marker or symbol next to currently-opened projects in the recent projects picker.  Also, we may sort those first in the list.  Just a couple ideas...

**Comment by mikayla-maki** [comment]
As this has been partially implemented, I'm going to close this one out in favor of Joseph's other issue.
