### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by Daeraxa** [zed-industries/community#366]
### Check for existing issues

- [X] Completed

### Language

Lua

### Tree Sitter parser link

https://github.com/Azganoth/tree-sitter-lua

### Language server link

https://github.com/sumneko/lua-language-server

### Misc notes

Would be useful to include, a lot of things have config files and extensions written in Lua.

**Comment by JosephTLyons** [comment]
Tree Sitter Link: https://github.com/Azganoth/tree-sitter-lua

**Comment by JosephTLyons** [comment]
Just received my [Playdate](https://play.date) in the mail and now I'm not stoked to use VS Code.  Another vote for Lua here! 😅

**Comment by gaetgu** [comment]
I want to put in here that I would also love lua support! I use it for scripting several of my programming projects, and being able to do it in zed instead of VSC would be great :)

**Comment by Kethku** [comment]
Lua support is merged into main and will be released in the next version or two

**Comment by gingerbeardman** [comment]
@JosephTLyons another Playdate developer here! have you managed to get autocompletition/hints to pick up the Playdate function definitions? Maybe using https://github.com/notpeter/playdate-luacats or https://github.com/notpeter/playdate-docdef
