### ISSUE TITLE
Sign out of Zed?

### ISSUE THREAD

**Issue by spaceybit** [zed-industries/community#372]
I signed in to Zed from my personal GitHub account, but I want to switch to my work GitHub account (both GitHub accounts are in the Zed alpha). However, I don't see an option anywhere to sign out.

I tried reinstalling zed and that didn't help. I also checked the ~/.zed but that doesn't seem to have the user context details.

Could someone help me sign out, please?

**Comment by nathansobo** [comment]
It's a missing feature, but in the short term you can delete the keychain item for Zed in the "Keychain Access" application.

**Comment by spaceybit** [comment]
This worked, Thanks a lot for the help @nathansobo!

**Comment by hovsater** [comment]
This is now possible in the latest version of Zed. 🙂

**Comment by senev3141** [comment]
> This is now possible in the latest version of Zed. 🙂

Hm, I'm running the latest version Zed 0.86.1 and had to manually remove the keychain item for Zed, there is no feature allowing to switch accounts

**Comment by hovsater** [comment]
You're right. I misspoke on that part. The ability to sign out was added back when I wrote that comment. The ability to switch accounts does not yet exist. As others have pointed out, the "solution" for now is to remove Zed from the Keychain.
