### ISSUE TITLE
Failed to deserialize langauge server latest release information

### ISSUE THREAD

**Issue by tylerFowler** [zed-industries/community#377]
### Check for existing issues

- [X] Completed

### Describe the bug

Received when opening a Go file from a fresh Zed installation:

```
Language server error: Go

error deserializing latest release

Caused by:
    missing field `name` at line 1 column 277
```

Let me know if there's a workaround in the short term.

### To reproduce

Open a Go file (with no Go language server already installed).

### Expected behavior

Expected to automatically download the Go language server

### Environment

Zed 0.48.1 – /Applications/Zed.app 
macOS 12.4 
architecture x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

18:11:38 [ERROR] no cached binary
18:11:38 [ERROR] error deserializing latest release

**Comment by JosephTLyons** [comment]
This is not the convention we'd normally go with, but there's a newer issue that has a handful of upvotes, so Im going to close this one in favor of the one with the upvotes.  Normally, we'd catch the newer duplicate before it had any votes, but it slipped through the cracks and users upvoted it:

- https://github.com/zed-industries/community/issues/989

**Comment by tylerFowler** [comment]
Ah sorry, forgot to close this one when I found the main thread.

**Comment by JosephTLyons** [comment]
No worries - what I meant was, your issue is the one we'd normally keep open and close others as duplicates, but because the duplicate that slipped through received more upvotes, I went the opposite direction here.
