### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/community#406]
### Check for existing issues

- [X] Completed

### Language

PHP

### Tree Sitter parser link

https://github.com/tree-sitter/tree-sitter-php

**Comment by bode-fun** [comment]
Regarding the LSP: This is basically the goto LSP for PHP https://intelephense.com/
It's freemium and closed source but available here: https://www.npmjs.com/package/intelephense

The reference implementation for VSCode is available here https://github.com/bmewburn/vscode-intelephense/tree/master

Another candidate is the LSP by felix becker. It's open source, but it hasn't been updated in 5 years. Se source is available under https://github.com/felixfbecker/php-language-server

Would love to see PHP language support since it is still one of the core technologies of todays web.

**Comment by turegjorup** [comment]
Other LSP options are https://phpactor.readthedocs.io/en/master/usage/language-server.html and https://serenata.gitlab.io/

**Comment by niladam** [comment]
I'm sorry for spamming this, but i'm also really interested in PHP support. I think the number of reactions doesn't show this issues' importance and figured i just added a message to it.

Think of this as a +1 :)

**Comment by tshazar** [comment]
I want to move to zed for at least some basic testing but it is missing a lot at the moment.  Much I can get along w/o however lack of at least basic php support or a plugin interface to roll my own tools does not allow me to stay for long.  Looks like I am jumping back into vim for another 3-6 months, I will peek in from time to time.

**Comment by hectordommo** [comment]
+1 for PHP support, It was actually very surprising to realize there was no support for php out of the gate

**Comment by xmarkclx** [comment]
I'm shocked there's actually no PHP support. :O

**Comment by muuvmuuv** [comment]
Oh yes, support for Laraval would be wonderful. Just to add my bit, I have used intelephense since the beginning and it's just perfect.

Maybe also built-in support for https://github.com/phpstan/phpstan/? This would also enhance static analysis of PHP code and especially Laravel applications.

**Comment by 06tech** [comment]
bump

**Comment by tchartron** [comment]
Looking forward to using Zed once php is supported ! 
Long time Sublime Text user here, switched to vscodium some months ago, i would be pleased to get that speed feeling back 😜

**Comment by hovsater** [comment]
I just want to remind people that leaving comments such as `+1` or `bump` will just cause us to lock the thread. We understand that there's an interest in PHP support (like many other languages) and the best way to show interest is up add react with an 👍 on the original issue. Bumping the thread will not make us work faster.

Whenever there's news to share, I'll be the first one to say so. 🙂

**Comment by 06tech** [comment]
Many apologies - I did bump this thread thinking it had been overlooked. I will await your news regarding PHP support!

**Comment by osiewicz** [comment]
I am working on this right now, already got syntax highlighting going. :)
![image](https://github.com/zed-industries/community/assets/24362066/7401da4c-f2c8-4f81-aa8b-842eba60bc8e)

**Comment by rafiahmedd** [comment]
@osiewicz please let me know if I can contribute to this anyway.

**Comment by osiewicz** [comment]
This just got merged; Stay tuned for tomorrow's Preview release (and next week's stable) y'all. :)

**Comment by xpader** [comment]
> This just got merged; Stay tuned for tomorrow's Preview release (and next week's stable) y'all. :)

How do we configure php intelephense? I need a place to configure my licence keys to it.

**Comment by mikayla-maki** [comment]
> I have a little question, how do we configure php intelephense? I need a place to configure my licence keys to it.

[Looks like this is done by placing a magic file in a specific spot...](https://github.com/bmewburn/vscode-intelephense/blob/master/src/extension.ts#L276-L320)

cc: @osiewicz

**Comment by sunilshenoy** [comment]
There used to have the location mentioned in one of support documents, but looks like Support now points to Github issues.

```Currently, the best way to set the license key is to save it to $HOME/intelephense/licence.txt.```

https://github.com/bmewburn/vscode-intelephense/issues/2592

**Comment by mikayla-maki** [comment]
Even better, thank you @sunilshenoy !

**Comment by xpader** [comment]
There's a very important problem, zed doesn't recognize variable start with symbol `$` when typing, no suggestion list popup.

**Comment by sunilshenoy** [comment]
@xpader there is no need for suggestion list in this case. You can create a license.txt document and paste you license key in it.

E.g
<img width="440" alt="image" src="https://github.com/zed-industries/community/assets/443598/8cc15dfe-6556-4121-816a-0c3954cc4014">

**Comment by RemcoSmitsDev** [comment]
> @xpader there is no need for suggestion list in this case. You can create a license.txt document and paste you license key in it.
> 
> E.g <img alt="image" width="440" src="https://user-images.githubusercontent.com/443598/256773907-8cc15dfe-6556-4121-816a-0c3954cc4014.png">

Does this actually change something for you? I still miss the premium options..

**Comment by xpader** [comment]
@RemcoSmitsDev I didn't try again, because Zed can't even prompt PHP variables normally.

**Comment by RemcoSmitsDev** [comment]
> @RemcoSmitsDev I didn't try again, because Zed can't even prompt PHP variables normally, I think that's because php variable name not start with the letter, it's start with a symbol `$`, Zed doesn't take this into account.

Ahh oke, I created a [issue](https://github.com/zed-industries/community/issues/1820) for this problem. Can you give it a try for me so I know if other people have the same issue that the premium options do not work after creating the license.txt

**Comment by xpader** [comment]
@RemcoSmitsDev I tried put my license key into path `$HOME/intelephense/licence.txt`, real path is `/Users/myusername/intelephense/licence.txt` and restart Zed, it's not work, php support in zed still no premium features.

**Comment by RemcoSmitsDev** [comment]
@xpader Thanks for testing it for me!

I assume they will look into this, but keep in mind PHP support is not their main focus. So give them some time to look into this and they will deliver.

**Comment by osiewicz** [comment]
Hey,
Yeah, as @RemcoSmitsDev said, I will get back to it as soon as I can (which should be once new search UI ships in the following Preview); in the meantime, I wholeheartedly appreciate issues on the matter though!

**Comment by gldtn** [comment]
@osiewicz any updates on this?

**Comment by osiewicz** [comment]
Not yet I'm afraid. :/

**Comment by joefitzgerald** [comment]
https://intelephense.com/faq.html notes that the file must be named `licence.txt`, not `license.txt` (note the `c`, rather than the `s`; this is British spelling vs American spelling).
