### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by imjordanxd** [zed-industries/community#410]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Searching for text within a certain directory

### Describe the solution you'd like

A global search similar to VSCode would be awesome which includes excluding, including directories etc.

**Comment by peterkos** [comment]
Additionally -- sublime has a togglebale option to respect the `.gitignore` -- this would be _fantastic_ for auto excluding `target/` or `node_modules` for instance

**Comment by JosephTLyons** [comment]
We are landing some support for this in v0.86.0. I'm going to close this for now. If there are additional requests for more additions after, feel free to open up a new issue.
