### ISSUE TITLE
Clicking the "Please update Zed to collaborate" section should take an action

### ISSUE THREAD

**Issue by williammartin** [zed-industries/community#420]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

The message "Please update Zed to collaborate" looks like a clickable button, and I expected it to take me to the page where I could download the latest version (or take some other action that resulted in an update occurring).

### Describe the solution you'd like

The "Please update Zed to collaborate" section becomes clickable and takes me to the downloads page, or the latest release, or actually starts performing an update.

**Comment by iamnbutler** [comment]
This should restart Zed ideally, but we are blocked on automatically reloading the workspace configuration when Zed is reopened. We'll likely tackle this once that is done!

**Comment by mikayla-maki** [comment]
Blocks on: https://github.com/zed-industries/feedback/issues/430

**Comment by williammartin** [comment]
Yeh that sounds like an ideal scenario. I do think there is immediate value in opening https://zed.dev/releases when clicked but I understand that it might not be high enough priority compared to your other work.

Cheers!

**Comment by mikayla-maki** [comment]
Good point, I'll see if that can be done 👀

**Comment by mikayla-maki** [comment]
Actually, I think I need to hold back on this for consistency with how all of our other 'Update Zed' behavior works.

**Comment by JosephTLyons** [comment]
I think this is now implemented in Zed - going to close this issue now.
