### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/community#432]
### Check for existing issues

- [x] Completed

### Language

Svelte

### Tree Sitter parser link

https://github.com/Himujjal/tree-sitter-svelte

### Language server link

https://github.com/sveltejs/language-tools

Specifically: https://github.com/sveltejs/language-tools/tree/master/packages/language-server

**Comment by maraisr** [comment]
Oh my gosh yes!!! Not even sure why I didn't raise this sooner! 

That being said, svelte has an official lsp, and did notice in one of the latest releases of Zed there is a new `lsp` settings option. Wonder if there's a way to configure lsp, perhaps we can get some docs on this?

**Comment by TheFoolishPupil** [comment]
Haha yeah I too was a little shocked to see that it hadn't been requested yet. I haven't looked at the latest release notes yet, I'll give em' a peek.

**Comment by TheFoolishPupil** [comment]
Is https://github.com/zed-industries/feedback/issues/341 what you are referring to @maraisr? If so I think this is just added support for providing initialization options to existing language servers, not support for user-defined ones.

**Comment by endigma** [comment]
So is the svelte lsp usable with Zed? I'm not very versed on LSP in general so I'm not sure how to enable it or if it needs to be enabled

**Comment by JosephTLyons** [comment]
> So is the svelte lsp usable with Zed? I'm not very versed on LSP in general so I'm not sure how to enable it or if it needs to be enabled

Unfortunately, users can't choose what language servers they want to use with Zed - they are currently baked in.  In the future, we want to give users a flexible system that allows for them to choose their preferred language servers and such.

**Comment by wtfiscrq** [comment]
@JosephTLyons, sorry for the off-topic, but is there any issue/roadmap item to track being able to add custom languages and LSPs?

**Comment by MatthiasGrandl** [comment]
👀

**Comment by mikayla-maki** [comment]
This should be out by 0.97

**Comment by guttenbergovitz** [comment]
0.96.2... counting... counting... 😺
