### ISSUE TITLE
Show full path on hover

### ISSUE THREAD

**Issue by ForLoveOfCats** [zed-industries/community#465]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

There are many cases when you may want to reference the full path of a file, especially when a go-to-definition jumps you out of the project you are editing.

### Describe the solution you'd like

One or more UI elements like the file tab should display the complete path to the file on hover, potentially even with a "Copy Path to Clipboard" entry in a right click context menu.

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

**Comment by johnm** [comment]
Definitely need the copy to clipboard feature!

**Comment by tfantina** [comment]
I've always loved the way Atom did it where you could click the file path in the gutter and it would copy it,  shift + click would copy the subpath.

**Comment by hovsater** [comment]
This should all be possible now. Hovering a tab shows the absolute path to the file. The Command Palette now contains two actions, `editor: copy path` and `editor: copy relative path`. These can also be accessed by right clicking the file in the Project Panel.
