### ISSUE TITLE
Pasting is inconsistent on where it gets placed in text

### ISSUE THREAD

**Issue by Programatic** [zed-industries/community#469]
### Check for existing issues

- [X] Completed

### Describe the bug

As shown in the attached video, where the pasted text is inconsistent. It should be placed where the cursor in edit mode was positioned (or right after the current highlighted section in visual mode IIRC).

### To reproduce

https://user-images.githubusercontent.com/41210901/186523178-b3a98363-f4eb-4bc9-90b7-ea659b27f7a7.mp4

### Expected behavior

The clipboard should be pasting into the same spot

### Environment

Zed 0.52.0 – /Applications/Zed.app \nmacOS 12.4 \narchitecture x86_64

**Comment by noib3** [comment]
@Programatic  In the video you posted are you using `p` or `Cmd-v` to paste in normal mode?

**Comment by Programatic** [comment]
@noib3 I am using `p` but it appears that `Cmd-v` has the same behavior based on some quick thinking.

**Comment by Programatic** [comment]
It looks like this occurs when I am copying from chrome. When I use `p` (as I originally was using), it pastes like `Cmd - v` in your clip, while if I copy from within Zed, it pastes it correctly.

**Comment by noib3** [comment]
Can confirm, both `Cmd-v` and `p` act like `P` when pasting text copied from an other program.

**Comment by Kethku** [comment]
Thats a useful hint. I think I know whats going on

**Comment by ConradIrwin** [comment]
This should be fixed as of v0.101, let me know if you see differently!
