### ISSUE TITLE
Jump by paragraph

### ISSUE THREAD

**Issue by ForLoveOfCats** [zed-industries/community#472]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Vertical cursor motion by paragraph is a great help when navigating by keyboard, currently Zed lacks any sort of motion. See related issue for this feature in Vim mode https://github.com/zed-industries/feedback/issues/470

### Describe the solution you'd like

A modifier which when held makes the up/down arrow keys jump by paragraph

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

**Comment by johnm** [comment]
Is this just by empty lines? Or are you thinking of this as language/mode/syntactic-unit specific?

**Comment by ForLoveOfCats** [comment]
I would typically envision blank line based but I do know that JetBrains has some interesting syntactic level item motions that could probably do with tree-sitter

**Comment by MoritzKn** [comment]
This is super useful! Unfortunately, not many people use (or know about it) this but every time I use this in pair programming people what to use this too

**Comment by alejandrovrojas** [comment]
This issue is solved: https://github.com/zed-industries/community/issues/470

**Comment by ForLoveOfCats** [comment]
Whoops yeah we added this a while back for non-vim interaction
