### ISSUE TITLE
Wrap guide

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#48]
I would love to have wrap guide support in Zed.  Some things to consider upfront would be the ability to have multiple wrap guides and maybe the ability to set wrap guides per language.  I imagine for the settings, there could be a global array of values for wrap guides, then language-specific arrays to override.

**Comment by jonathanj** [comment]
A bunch of other issues related to vertical rulers and wrap guides lead here, but this ticket was closed last year. The [docs site](https://docs.zed.dev/configuration/configuring-zed) doesn't seem to make any mention of wrap guides, but if you attempt to create a config key in `settings.json` called `wrap_guides` autocomplete indicates it exists, and accepts an array of numbers like VS Code.

Might be worth adding to the documentation?

**Comment by mikayla-maki** [comment]
Ahh, yes, apologies. I should have added a comment explaining it. Yes! Zed has had wrap guides since last summer and you can define an array of line offsets to add to your editor. If you have soft wrap enabled, there will also be an additional line added indicating the soft wrap cutoff width.
