### ISSUE TITLE
Terminal mouse selections sometimes incorrectly omit the first clicked character

### ISSUE THREAD

**Issue by maxbrunsfeld** [zed-industries/community#528]
### Check for existing issues

- [X] Completed

### Describe the bug

Sometimes, when clicking and dragging to select text in the terminal, the first character that I'm trying to select is incorrectly excluded from the selection.

### To reproduce

1. Click and start dragging with the mouse in the middle of a character, but toward the left edge.
2. Drag the mouse to the right to select some text
3. :boom: The first character isn't selected, even though the drag started near the left edge of that character

### Expected behavior

If the drag started on the left half of a character, that character should be included in the selection

### Environment

Zed 0.54.1 – /Applications/Zed.app
macOS 12.4
architecture arm64

**Comment by aybabtme** [comment]
I'm really struggling with this, it's quite annoying. Sometimes the selection grabs one more character, or sometimes it skips one. And then it also seems to be flaky when I release the mouse. Combined with the fact that I can't "double-click first word" + Shift + "double-click last word" to select text, it makes for a very frustrating experience.

https://user-images.githubusercontent.com/1189716/228391685-144985e8-8f16-40e1-9f76-c16be69c7006.mov

**Comment by mikayla-maki** [comment]
I believe this issue may have been fixed, I can't seem to reproduce it on our latest distributed build. Please comment if this is observed again.

**Comment by aybabtme** [comment]
I just tried with 0.82.8 and the behavior remains.

**Comment by mikayla-maki** [comment]
Ahh, I see the issue now. Sorry for the false hope :)

**Comment by mikayla-maki** [comment]
This has now been fixed and will be available in a few weeks. Once a drag has been initiated the character under cursor should always be included.

**Comment by mikayla-maki** [comment]
After some experimentation, this seems to match behavior internal to the version of alacritty that we're using:

https://user-images.githubusercontent.com/2280405/233751897-0e8ad596-245e-412c-9958-1b066ff52271.mov

And therefore will not be fixed for a while.

**Comment by aybabtme** [comment]
I use Alacritty as a standalone terminal and don't see the same behavior. I tried with today's latest version of Zed and the problem persist.
