### ISSUE TITLE
When dock is open and focused, files in the project panel are added to it instead of the center pane

### ISSUE THREAD

**Issue by mikayla-maki** [zed-industries/community#533]
### Check for existing issues

- [X] Completed

### Describe the bug

From @jack on the discord:

When I pop open the terminal with shift+esc then open a new file (double clicking on the files listed on the left) the file opens in the terminal window rather than the "main" one, which feels off.

https://user-images.githubusercontent.com/2280405/192606566-41d16dad-fc48-4518-a169-9ec718ff71e5.mov

### To reproduce

1. open a bottom or right dock with shift-escape
2. Click on a file in the project panel
3. Observe that the file has been opened in the dock

### Expected behavior

The file should have been opened in the center pane.

### Environment

N/A

**Comment by eth0net** [comment]
This feels right to me, and I make use of it. But I agree that to some it may seem wrong if you think of it as a 'terminal dock' instead of just a general dock for panes.

Perhaps it could be configurable, maybe an `open_in_dock` setting?

**Comment by mikayla-maki** [comment]
Yeah... the problem is with expectations and focus I think. Like, I think my bug report here is incorrect and a better flow would be something like `right click 'open in dock' / 'open in center'` or some such. Uncertain. It did feel weird when I ran into this though, I wonder if there's a deeper issue we can uncover.

**Comment by TerminalFi** [comment]
This is what I ran into today and I personally think it is a bad UX. Generally when opening a terminal, one would want to maintain a certain level of focus, take debuting code, it you prompt a terminal and then start debugging code, unless you are constantly ensuring you click out into the other pane, you continuously lose focus as you adjust your code. It’s no longer a seem less experience of modifying code and seeing immediate results. 

Much like the concept Zed embraces of instant drawing to screen each display refresh, editing code and seeing results requires an extra step of refocusing the terminal. Impacting productivity

**Comment by TerminalFi** [comment]
The idea of a bottom panel which you can manually add and remove buffers to while supporting setting to allow terminal, diagnostics, logs to be dedicate to that location.

**Comment by mikayla-maki** [comment]
> unless you are constantly ensuring you click out into the other pane

Ahhh yeah, I see what you mean here. I think auto-opening some 'types' of of items in the dock vs. in the center is good UX

**Comment by eth0net** [comment]
I'm happy to be the odd one out here, if that's the case 😄 if more people find it natural the other way then it's the better default!

I'd be okay with the default behaviour changing, but I'd like to still have the option to place files in the dock by hand, and maybe a right click option as suggested! 

Maybe use the dock automatically for complementary views such as terminals, debug, linting, git logs etc. But allow users to pin additional views (like files) there too.

Further down the line, maybe it could be made configurable to always open matching files or certain plugin/feature panes there, based on user configuration? 👀

**Comment by covt** [comment]
> This feels right to me, and I make use of it. But I agree that to some it may seem wrong if you think of it as a 'terminal dock' instead of just a general dock for panes.
> 
> Perhaps it could be configurable, maybe an `open_in_dock` setting?

I do think that a QoL setting that's optional would make sense. I see many use cases where having documents in the dock would make sense, but for a majority of cases personally, I like having my shell and my working documents isolated. Using a shell specific split would be ideal. 

Perhaps we're talking about it in the wrong way though, and rather than changing how the dock works, a "shell drawer" could be added instead?

**Comment by Kethku** [comment]
I ended up not adding an open_in_dock setting, but `cmd-escape` now adds and removes items to/from the dock, so its very easy to open something, and immediately move it where it needs to go. Imho this better matches expectations,  and encourages using the dock for persistent/reference material without being unintuitive.

This should show up in the public release in a couple versions.
