### ISSUE TITLE
Open file at the specific line

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/community#557]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

I almost exclusively open files through the `Cmd+P` search and most of the time I need to scroll or do `Ctrl+G` to get to the line I'm looking for.

### Describe the solution you'd like

Could we get something like automatic line focus if the file search query ends in `L256` or similar?

### If applicable, add mockups / screenshots to help present your vision of the feature

1. Ctrl+P to open file search
2. Type "foo.rsL256"
3. Zed will open line 256 when the file is selected
4. Bonus feature - search doesn't show files that are shorter than the line specified

**Comment by JosephTLyons** [comment]
This is an interesting idea.  Does this workflow exist in other editors?

**Comment by rkusa** [comment]
It does exist in VSCode. The format there is: `file_name:123`, or `file_name:123:45` if you also want to specify the column.

**Comment by JosephTLyons** [comment]
> > Does this workflow exist in other editors?
> 
> It does exist in VSCode. The format there is: `file_name:123`, or `file_name:123:45` if you also want to specify the column too.

Ahh, very cool!  That does seem like a nice little workflow improvement.

**Comment by mikayla-maki** [comment]
Might be nice to use the same data source as the outline and fuzzy match on identifiers? e.g. file_name:Struct::foo. Would probably be nice to have autocompletion in the command palette for that tho 😅

**Comment by stjepangolemac** [comment]
Ah I didn't know VSCode has something like this 👍

**Comment by JosephTLyons** [comment]
The ability to open a file at specific line / column should be landing soon.

**Comment by JosephTLyons** [comment]
Closing this out, as it will be available in v0.87.0.
