### ISSUE TITLE
Link filepath:line:column in Terminal

### ISSUE THREAD

**Issue by rkusa** [zed-industries/community#560]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

A lot of terminal commands print out file paths and locations (e.g. `cargo clippy`).
Example: `src/lib.rs:71:42` for file `src/lib.rs`, line number 71, and column 42.

 It is quite cumbersome to manually navigate to this file and location in that file.

### Describe the solution you'd like

It would be useful if such file paths are clickable in the terminal. Once clicked, the editor would open that file and navigate to the specified location (line number and column).

The solution is similar to #467 (that was about clickable URLs) but for file paths, and might have some overlap with #557, which is about opening a specific location from CMD+P (potentially using the same pattern of `:LINE_NUMBER:COLUMN`).

### If applicable, add mockups / screenshots to help present your vision of the feature

Example from VSCode:

https://user-images.githubusercontent.com/409021/194825433-e4b59dcb-88e8-43cd-b622-8386d42c557d.mov

**Comment by SomeoneToIgnore** [comment]
A few related notes to add:
* VSCode also supports `src/lib.rs:71:42` format in open file dialogue, while Zed does not. That speeds up opening files drastically.

* besides terminal output, there are other cases where path detection could be useful: for example, backtrace analysis.
Allowing to paste a random log/backtrace and have it contain links to navigate to local project files would be amazing.

**Comment by aybabtme** [comment]
Another note:
- VSCode also allows "Cmd+click" clicking on `path/file.ext:line:col` in the terminal, or any text buffer.
- This is extremely useful when working with linters, compilers. i.e. the Go tools print out lines with problems and I tend to "Cmd+click" on them quickly to navigate.

**Comment by nippotam** [comment]
Perfect ! When it will be available?

**Comment by SomeoneToIgnore** [comment]
This comes with the 0.96.0 version.
