### ISSUE TITLE
Text Manipulation Commands

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#57]
Some editors come with these features built-in and some editors leave these to packages.. not sure what Zed should do here.  Maybe they should be packages when there is a package system or maybe they could be built-in.  Just tossing it out there - I use some of these a ton daily.

- https://github.com/zed-industries/community/issues/658
- [Toggle case](https://github.com/zed-industries/community/issues/1011): `aaa_bbb` -> `AAA_BBB`, and vice versa (use JetBrains editors to study how this works in various cases)
- Reverse selected lines

---

Additional text manipulation commands

- https://github.com/zed-industries/community/issues/1821
- Randomize selected lines
- https://github.com/zed-industries/community/issues/1369

**Comment by exalted** [comment]
Absolutely 👍 this! I cannot speak for a plugin/ext VS built-in, but whatever it is, it shouldn't compromise Zed's performance.

**Comment by Yevgnen** [comment]
Some more: 

- transpose word/symbol
- align lines by regex/string
- wrap/unwrap text

**Comment by JosephTLyons** [comment]
A PR just landed that adds in:

- `sort lines case sensitive`
- `sort lines case insensitive`
- `reverse lines`
- `shuffle lines`

These will be available in v0.97. I'm going to close out this meta issue: For the remaining text manipulation commands, please directly upvote the original issues:

- https://github.com/zed-industries/community/issues/1011
- https://github.com/zed-industries/community/issues/1821
- https://github.com/zed-industries/community/issues/1369

**Comment by JosephTLyons** [comment]
> Some more:
> 
> * transpose word/symbol
> * align lines by regex/string
> * wrap/unwrap text

Feel free to make individual issues for these, so we can gauge interest in each one individually. :)
