### ISSUE TITLE
`alt-f` and `alt-b` not working as expected when using `"option_as_meta": true`

### ISSUE THREAD

**Issue by cjpearce** [zed-industries/community#596]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Set `"option_as_meta"` setting to `true`
2. Open a terminal window
3. Enter text with multiple words
4. Try to navigate forward/backward with `alt-f`/`alt-b`

Actual result:
"special" characters appear in the terminal at the cursor position as if `"option_as_meta"` was not working at all

### Expected behavior

Using `"option_as_meta"` should enable using emacs navigation shortcuts such as `alt-f` and `alt-b`

I don't have much experience with the implementation details behind this but it appears to me like the `"option_as_meta"` configuration is simply not working properly. In all other terminals I've used, enabling a setting similar to `"option_as_meta"` is enough to get the desired navigation shortcuts.

### Environment

```
Zed 0.60.4 – /Applications/Zed.app
macOS 12.6
architecture arm64
```

**Comment by mikayla-maki** [comment]
Hi! I just tested this and it seems to work correctly. Can you confirm whether you're still experiencing the issue?

**Comment by cjpearce** [comment]
Apologies I'm trying Zed again and found it worked this time. I think that last time I was not adding the terminal settings under an entry `"terminal"`.

I think my previous settings would have looked like this:
```
{
    "buffer_font_size": 15,
    "option_as_meta": true
}
```

Rather than this:
```
{
    "buffer_font_size": 15,
    "terminal": {
        "option_as_meta": true
    }
}
```

Because I had been looking for that specific setting rather than reading the whole page from the top, I hadn't realised from the context around the description of `option_as_meta` that those settings had to be nested as above. Possibly this could be clearer in the documentation, but I suspect it might just be on me for not reading carefully. I can now see after reading the page that the https://zed.dev/docs/configuration/configuring-zed#available-settings section shows a `"terminal"` object and refers to the section lower in the page. That's probably the part I missed.

**Comment by cjpearce** [comment]
Thanks for taking the time to try it. Hopefully next time I report something it will lead somewhere more useful!

**Comment by mikayla-maki** [comment]
Thank you for checking in @cjpearce ! We'll fix that doc formatting, it is really confusing now that you mention it!
