### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by jawnyawns** [zed-industries/community#598]
### Check for existing issues

- [X] Completed

### Language

Elm

### Tree Sitter parser link

https://github.com/elm-tooling/tree-sitter-elm

### Language server link

https://github.com/elm-tooling/elm-language-server

### Misc notes

Lots of us (me!) use [Elm](https://elm-lang.org/) to build web apps. Would also appreciate format on save using the community accepted [elm-format](https://github.com/avh4/elm-format).

**Comment by z5h** [comment]
I'd love this too.

But also, I see that only "supported" languages can have language overrides. 
Can we not have language overrides for any language? Just let us choose a file extension(s), language server, etc.

**Comment by hovsater** [comment]
I'm already using Zed at work (and I love it!) and would love to use Zed while developing my side project as well (a Typeracer clone written in Elm). However, given I'm on [Lamdera](https://www.lamdera.com/), I would still need #585 to be done first since I need that in order to change the `elmPath` to the Lamdera binary instead. 🙂

**Comment by wolfadex** [comment]
Would love to switch away from VSCode at work as we a monorepo with:
| Language | Lines of Code (rough `cloc` estimate) |
| --- | --- |
| TypeScript | 2,132,231 |
| Elm | 612,188 |

Plus configs and more.

VSCode & IntelliJ start to chug pretty quickly. We also do lots of pairing, having a collaborative editor for our whole code base would be great!

**Comment by absynce** [comment]
Thanks for working on this @mikayla-maki! 🙌 I'm super excited to see this progressing.

I have a couple of questions since this is only partial support:
1. What's included in Elm support without LSP? Tree sitter? Syntax highlighting?
2. Is this available in Zed 0.95.3, a preview release, or coming soon?

**Comment by wolfadex** [comment]
@absynce there's some details in the [preview release of 0.97](https://zed.dev/releases/preview)

**Comment by JosephTLyons** [comment]
> Thanks for working on this @mikayla-maki! 🙌 I'm super excited to see this progressing.
> 
> I have a couple of questions since this is only partial support:
> 
> 1. What's included in Elm support without LSP? Tree sitter? Syntax highlighting?
> 2. Is this available in Zed 0.95.3, a preview release, or coming soon?

You'll get syntax highlighting, auto indent, code folding, etc. Since this iteration doesn't include a language server, you won't get things like autocompletions, symbol rename, jump to def, etc.

**Comment by absynce** [comment]
Thanks for the explanation! I just updated to the latest preview. 😍 Beautiful. So excited for this.

For other Elm folks who might be following this, I set up `elm-format` with these settings:

```
  "language_overrides": {
    "Elm": {
      "format_on_save": {
        "external": {
          "command": "elm-format",
          "arguments": [
            "--stdin"
          ]
        }
      }
    }
  }
```

I have elm-format installed via npm instead of globally, so mine is actually like this:

```
          "command": "node_modules/.bin/elm-format",
```

**Comment by mloughran** [comment]
In you configure it like this, you can enable / disabled format on save independently from configuring the formatter (I was surprised that adding the config within `format_on_save` worked given [the docs](https://docs.zed.dev/configuration/configuring-zed#format-on-save):

```json
"Elm": {
  "format_on_save": "on",
  "formatter": {
    "external": {
      "command": "elm-format",
      "arguments": [
        "--stdin"
      ]
    }
  }
},
```
