### ISSUE TITLE
Ctrl-Tab to switch between tabs/files

### ISSUE THREAD

**Issue by exalted** [zed-industries/community#6]
I wish `Ctrl-Tab` would let me switch between open tabs/files

**Comment by iamnbutler** [comment]
> I wish `Ctrl-Tab` would let me switch between open tabs/files

How does this interact with splits? I assume it would. just cycle between the tabs in that split?

**Comment by exalted** [comment]
@iamnbutler I didn't know about splits to start with 🙃 Nevertheless, I guess "cycling between the tabs in current split, by default" would be a reasonable default. What do you think?

**Comment by JosephTLyons** [comment]
I agree that it would be nice to have this functionality, I would also like there to be a way to reverse the direction of the cycling, with an additional modifier key, or have the command to cycle involve the left and right arrow keys in some way, which already sort of aligns with how other commands work (splitting panes and changing focus to different panes).

**Comment by imron** [comment]
Don't forget to add `Ctrl+^` for the equivalent behaviour when in vim_mode 👍

**Comment by adamsoutar** [comment]
+1 for changing tabs with `Cmd` + number.

Also, almost all tabbed apps like Safari, Chrome, VS Code and Atom also support `Cmd` + `Option` + `Left` and `Cmd` + `Option` + `Right` for tab cycling.

That seems to be the standard thing to do, and is a bit of a must-have for me in Zed.

**Comment by JosephTLyons** [comment]
> +1 for changing tabs with `Cmd` + number (Oh, and skipping straight to the far-right one with `Cmd` + `9`)
> 
> Also, almost all tabbed apps like Safari, Chrome, VS Code and Atom also support `Cmd` + `Option` + `Left` and `Cmd` + `Option` + `Right` for tab cycling.
> 
> That seems to be the standard thing to do, and is a bit of a must-have for me in Zed.

I didn't know Safari used `cmd-opt-left/right`, I've always used `cmd-shift-left/right`; just checked and both commands work to cycle tabs - interesting.

**Comment by HanEmile** [comment]
Another thing for vim mode: gt and gT for switching to the next and previous tabs.

**Comment by therealpaulgg** [comment]
I use this extensively in VS Code and other IDEs and probably won't use Zed a lot until it gets added.

**Comment by PJUllrich** [comment]
Maybe this ticket is about changing the default behavior, but you can set this up already by putting this into your `keymap.json`:

```
[
    {
        "bindings": {
            "ctrl-shift-tab": "pane::ActivatePrevItem",
            "ctrl-tab": "pane::ActivateNextItem"
        }
    }
]
```

**Comment by therealpaulgg** [comment]
> Maybe this ticket is about changing the default behavior, but you can set this up already by putting this into your `keymap.json`:
> 
> ```
> [
>     {
>         "bindings": {
>             "ctrl-shift-tab": "pane::ActivatePrevItem",
>             "ctrl-tab": "pane::ActivateNextItem"
>         }
>     }
> ]
> ```

This is definitely helpful but not quite what I was looking for. In vscode for example (also IntelliJ), pressing CTRL+TAB brings up this sort of interface:
![image](https://user-images.githubusercontent.com/21159486/226018683-6f4e3840-1940-4e13-8b33-75a4fdc6d8b5.png)
It is sort of like Windows' alt+tab where the most recently used code windows are higher in the list.

The keybind change just cycles through the tabs from left to right.

I don't know if this issue was created with this 'switcher' idea in mind, or if the intent was simply to easily switch tabs with ctrl-tab. Maybe a new issue should be created for this? I also realize not everyone may prefer this switcher interface.

**Comment by exalted** [comment]
> I don't know if this issue was created with this 'switcher' idea in mind, or if the intent was simply to easily switch tabs with ctrl-tab. Maybe a new issue should be created for this? I also realize not everyone may prefer this switcher interface.

When I created this issue, I wasn't thinking about any additional UI elements. So, https://github.com/zed-industries/community/issues/6#issuecomment-1473828585 definitely solved my "issue".

I think you may consider creating a new feature request, where this can be discussed deeply. What do you think?

**Comment by therealpaulgg** [comment]
Yes I think that would be best, I'll get around to it soon.

**Comment by hovsater** [comment]
@exalted are you fine with me closing this then?

**Comment by sheikalthaf** [comment]
@hovsater @exalted this is totally differs from what VSCode does,

this is simply switching between forward and backward files, not between recently opened files. 
I hope we should give users option to switch between recently opened files similar to VSCode.

Anyway i'll open another issue regarding this request

**Comment by hovsater** [comment]
@sheikalthaf feel free to open an issue describing the feature you had in mind. 🙂 We closed this one as @exalted's original request was solved.

**Comment by sheikalthaf** [comment]
@hovsater #1489 created the feature request. FYI
