### ISSUE TITLE
Autocomplete menu navigation in opposite direction

### ISSUE THREAD

**Issue by frenchbread** [zed-industries/community#632]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

When autocomplete menu with options pops up, it's not possible to navigate in reverse direction (e.g. with `up` key). Useful if the needed option happens to be last in the list.

### Describe the solution you'd like

Upon autocomplete menu shows up, it's possible to navigate through options both ways - with `up` & `down` keys.

### If applicable, add mockups / screenshots to help present your vision of the feature

![zed_feature_req](https://user-images.githubusercontent.com/2122679/198114872-5f14c405-1d23-4b4c-9a70-df7ca8c61354.gif)

**Comment by mikayla-maki** [comment]
Hi frenchbread, thanks for the bug report. Can you provide more information on this? I just tried to navigate up and down in the menu that pops up with `cmd-space`, and it seemed to work. What are you experiencing?

**Comment by iamnbutler** [comment]
I assume the feedback is that you want the menu to wrap, correct? Like from the first time you can press up and now the last item will be selected?

**Comment by frenchbread** [comment]
Thanks for response!

> Hi frenchbread, thanks for the bug report. Can you provide more information on this? I just tried to navigate up and down in the menu that pops up with cmd-space, and it seemed to work. What are you experiencing?

> I assume the feedback is that you want the menu to wrap, correct? Like from the first time you can press up and now the last item will be selected?

@mikayla-maki I am not familiar with all the keybinds, however `cmd-space` does not switch options for me.

@iamnbutler yes, correct. Not sure if it's intended approach to do it "singe directional", but sometimes could be useful.

**Comment by mikayla-maki** [comment]
Sorry, I meant to write `ctrl-space`! Thanks for the explanation on the wrapping behavior :)

**Comment by frenchbread** [comment]
@mikayla-maki yeah, no worries, the issue is not related to popping up the suggestions window, but rather navigating though it using nav keys e.g. `up` & `down`. In the use-case provided in the description the suggestions menu is triggered using `.` symbol.

**Comment by JosephTLyons** [comment]
This should go out in next preview (v0.110.0) this week.
