### ISSUE TITLE
Code folding icon lacks strong visual indicator

### ISSUE THREAD

**Issue by TerminalFi** [zed-industries/community#657]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

The current code folding indicator is too minimal and is hard to identify quickly when viewing code. As you can see below, the `...` is rather tiny and blends

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/32599364/199966535-f08551bb-43cb-47a3-a690-3bd9611bf063.png">

### Describe the solution you'd like

The solution should be easily identifiable while browsing the code. perhaps an icon of sorts

**Comment by JosephTLyons** [comment]
@iamnbutler - Do we have anything new mocked up for this?

**Comment by lukeed** [comment]
I'm on 0.65.2 and have no indicator – just the ellipsis on the right, but it's not interactive. I'm only able to fold/unfold via the <kbd>Opt</kbd><kbd>Cmd</kbd><kbd>[</kbd> and <kbd>Opt</kbd><kbd>Cmd</kbd><kbd>]</kbd> keybinds. I'm using One Dark theme.

<img width="381" alt="Screen Shot 2022-12-01 at 11 27 25 AM" src="https://user-images.githubusercontent.com/5855893/205142168-c51c66e1-f41f-4e1c-ad6e-3da5407cb6ee.png">

**Comment by aexvir** [comment]
agree on the code ribbon from xcode, I prefer having a larger surface where I can click to fold code, as I don't usually use the mouse, but when I do I don't have as much accuracy 😄️

**Comment by SilentGlasses** [comment]
For simplicity sake, can we bring this discussion into #667 and close this issue out? 

It's very confusing to have to navigate three issues for the same topic and devs end up with more menial work having to follow the discussion in multiple places.

**Comment by SilentGlasses** [comment]
Is that a plugin that you are using that causes that? I am using the Visual Studio Code editor and I do not have those fancy shadings and indicators out of the box.  If yes, can you share what plugin that is?

**Comment by TerminalFi** [comment]
I believe these are two different issues, devs can close out as needed. No need to speak for them. This is specifically about the ellipsis which they use, where as the other is code fold levels and indicators. ;)

**Comment by JosephTLyons** [comment]
Our next release will have code folding buttons in the gutter.  It also turns the `...` into a clickable button.   I think that this will become the obvious indicator that users are wanting, so I'm closing this out.
