### ISSUE TITLE
Sort Lines

### ISSUE THREAD

**Issue by fuzenco** [zed-industries/community#658]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

No.

### Describe the solution you'd like

The ability to select multiple lines and perform an alphabetical Sort function on them by using the Command+P menu.

**Comment by exalted** [comment]
My two cents: I am not entirely sure if I'd also want to be able to have different sorting algorithms somehow (e.g., case-sensitive or insensitive, numbers first VS letters, special characters, similarly accented chars to behave as one, «e.g., ôöòóœø,» etc.)

**Comment by JosephTLyons** [comment]
A PR just landed that adds in:

- `sort lines case sensitive`
- `sort lines case insensitive`
- `reverse lines`
- `shuffle lines`

These will be available in v0.97

**Comment by fuzenco** [comment]
Thank you team!

**Comment by acusti** [comment]
i just downloaded the latest [preview release](https://zed.dev/releases/preview) to try this out and it works a treat! i added `F5` as the keyboard shortcut for `sort lines case insensitive` to match how i used to have it setup in atom and it’s a delight. `keymap.json`:

```json
[
  {
    "context": "Editor",
    "bindings": {
      "f5": "editor::SortLinesCaseInsensitive"
    }
  }
]
```

**Comment by JosephTLyons** [comment]
> i just downloaded the latest [preview release](https://zed.dev/releases/preview) to try this out and it works a treat! i added `F5` as the keyboard shortcut for `sort lines case insensitive` to match how i used to have it setup in atom and it’s a delight. `keymap.json`:
> 
> 
> 
> ```json
> 
> [
> 
>   {
> 
>     "context": "Editor",
> 
>     "bindings": {
> 
>       "f5": "editor::SortLinesCaseInsensitive"
> 
>     }
> 
>   }
> 
> ]
> 
> ```

Yay! Super stoked to hear that.  I've been wanting these since the alpha days myself!

**Comment by fuzenco** [comment]
Preview is amazing. With sorting working, there’s no reason to keep my other editors. Great job team.
