### ISSUE TITLE
auto-close quotes broken on strings

### ISSUE THREAD

**Issue by shot-codes** [zed-industries/community#684]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

if I try to change the string definition by backspacing after already closing it, a whole new string is spawned when attempting to close it again. 

https://user-images.githubusercontent.com/43202406/201453073-c66e64d2-6574-4f4d-9e0e-d12b2d48c8dd.mov

### Expected behavior

When I go to close the string for the second time, it should simply close with one quote, not two.

### Environment

Zed 0.63.4 – /Applications/Zed.app 
macOS 12.6 
architecture x86_64

**Comment by JosephTLyons** [comment]
Thanks for the feedback @s-h-o-t.  I run into this one pretty frequently - I'll relay it to the team.

**Comment by maxbrunsfeld** [comment]
We may want to change our approach to auto-closing brackets to be *more* based on the syntax tree, so that we decide whether or not to auto-close brackets by parsing the buffer with the single bracket and checking if an error was created.

**Comment by shot-codes** [comment]
There seems to have been a regression here. I now get an erroneous closing quotation without the deletions, just from trying to close the string with my keyboard. With no way to turn off autoclosing entirely, I unfortunately can't use zed with this issue, it's too disruptive. Any help would be much appreciated :)

https://user-images.githubusercontent.com/43202406/219986064-6add418b-45e0-46b1-a061-d02740d92e6d.mov

**Comment by maxbrunsfeld** [comment]
Yeah, apologies for that regression. The fix will ship in Zed 0.75.

**Comment by maxbrunsfeld** [comment]
Actually, we're fast tracking that regression fix for Zed 0.74, which ships tomorrow.

**Comment by madeinouweland** [comment]
The bug also occurs when a literal is surrounded by quotes

type 
```
print(Hallo)
```
Then add a quote before Hello
```
print("Hallo)
```
Then after Hello. This is the result:
```
print("Hallo"")
```

Zed: v0.76.1 (stable)
OS: macOS 13.2.1
Memory: 16 GiB
Architecture: x86_64

**Comment by andremacola** [comment]
Another related problem is autoclose double and single quotes is unusable in US International keyboard configurations.
