### ISSUE TITLE
Project-specific settings for including / excluding directories and files

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#70]
Depending the project, there is quite a bit of noise in some of my file searches.  I would like to be able to exclude some directories (virtual environment directories, npm module directories, etc.) from being searched through when using `command+p` to find a file, to remove as much noise as possible.  I'm guessing this implies some sort of project settings?  I think it could just be as simple as a hidden json file, that gets committed with your project, that excludes items via patterns:

A small example might be:

```json
{
    "excluded_patterns": [
        "<some-path-prefix-starting-from-project-root>/some_specific_file.py"
        "<some-path-prefix-starting-from-project-root>/some_specific_director/*",
        "*.scss"
    ],
}
```

Some open-ended questions about this:

1. When a directory is added to an exclusion list in a project setting file, what all is affected?
    - Does it affect what shows up in the file browser on the left?
    - Does it affect searches?
    - Does it affect searching for files?
    - etc.
 
    Or are all of those separate project settings?

**Comment by zcaceres** [comment]
Same problem in my Typescript projects. .gitignore'd directories still are included in cmd+p call. For projects with big `node_modules` this makes the file search almost unusable.

**Comment by JosephTLyons** [comment]
Something else to consider: Maybe there is a global set of excluded patterns in the normal settings, things that are always in the same location and always excluded no matter the project, then additional per-project settings to customize the excluded items further.

**Comment by nathansobo** [comment]
Going to prioritize this to start building in the weeks.

**Comment by exalted** [comment]
I hope as part of this effort there will be also support for user-specific (aka SCM-ignored) VS team-shared (committed to SCM) settings files.

Example:

* `~/.zed/settings.json` would contain user-only settings and apply to everything edited with Zed
* `~/foo-project/.zed/settings.json` would be included in SCM and shared across all members of the foo-project
* `~/bar-project/.zed/usersettings.json` would NOT be included in SCM therefore only apply to bar project and for the local user only.

**Comment by hueys** [comment]
It would be nice to be able to ignore files and directories in the Project Panel (file tree) similarly either on a global or per-project basis.

**Comment by WindSoilder** [comment]
For python projects, different project may use different formatter, or different code style, it would be nice to support configure these information each project, and if the setting is not found, fallback to user level setting

**Comment by jasikpark** [comment]
++ since `cargo-fuzz` workspaces aren't picked up automatically by `rust-analyzer`, so like in VSCode, I need to tell `rust-analyzer` to look at `/$CRATE/fuzz/Cargo.toml` manually.

ex: https://github.com/kaleidawave/ezno/tree/main/parser/fuzz

**Comment by abey79** [comment]
> For python projects, different project may use different formatter, or different code style, it would be nice to support configure these information each project, and if the setting is not found, fallback to user level setting

Exactly. Like many, I can't live without "Black on save" for my python projects. However, I can't allow that to happen when working a third-party project which doesn't use Black, as I occasionally do. Without per-project settings, this would be rather cumbersome to deal with.

**Comment by 5twrt** [comment]
I'd like the ability to configure formatters at a project-level and default to the local installations of that formatter.

Another feature from VSCode, which I found useful, was `explorer.excludeGitIgnore`. This hid files in the file tree that were included in the projects `.gitignore` file. Most of the time I wasn't referencing these files, so it was fine to hide them.

**Comment by exalted** [comment]
I think the title of this issue may be misleading, because project-specific settings file support has been just [shipped](https://docs.zed.dev/configuration/configuring-zed#folder-specific-settings) in `v0.90.1`, whereas this issue is mostly requesting to add a new setting which excludes files.

**Comment by JosephTLyons** [comment]
> I think the title of this issue may be misleading, because project-specific settings file support has been just [shipped](https://docs.zed.dev/configuration/configuring-zed#folder-specific-settings) in `v0.90.1`, whereas this issue is mostly requesting to add a new setting which excludes files.

Yeah, you are right.  The hard part now is, do we adjust the body to match the title, and close it out (losing the upvotes), and open a new issue, or rename it and keep it open?

**Comment by jezikk** [comment]
VSCode default patterns:

**/.git
**/.svn
**/.hg
**/CVS
**/.DS_Store
**/Thumbs.db
