### ISSUE TITLE
Language server related messages persist

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#723]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed messages about updating or trying to download language servers persist and never go away on my end.  Closing and opening Zed doesn't fix the problem, as it resurfaces after awhile.  Sometimes its about C++ and other times it's about Go.  If you look at the screenshot below, this is what shows on all of my instances, all of the time.

### Expected behavior

-

### Environment

Zed 0.65.2 – /Applications/Zed Preview.app
macOS 13.0.1
architecture arm64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

<img width="413" alt="SCR-20221121-i7u" src="https://user-images.githubusercontent.com/19867440/203128540-ac5e72b5-07a1-443e-aed9-3a165ce90d9d.png">

**Comment by JosephTLyons** [comment]
Here's a session where it's happening with the Python language server.  This is on v0.66.0.

<img width="507" alt="SCR-20221127-3u5" src="https://user-images.githubusercontent.com/19867440/204124616-3639efbf-2765-45b0-9e8c-90b5e13263fe.png">

**Comment by maxbrunsfeld** [comment]
I think one way to get into this state is to run a project search that rapidly opens buffers in several languages.

**Comment by cmnstmntmn** [comment]
I'm having the same issue

<img width="469" alt="Screenshot 2023-08-18 at 00 22 15" src="https://github.com/zed-industries/community/assets/2312755/9ff7614a-d641-443f-b447-f6a6554f76d0">

```Zed: v0.99.1 (stable)
OS: macOS 13.5.0
Memory: 8 GiB
Architecture: aarch64
```

**Comment by shlajin** [comment]
Happens with TypeScript on several latest zed versions up to Zed 0.100.1, mac M1, OS 13.4.1

**Comment by antoyne7** [comment]
I had this issue for a few weeks
I tried to install manually typescript-language-server and put it inside the language folder here ~/Library/Application\ Support/Zed
Now it works
