### ISSUE TITLE
Heex support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#725]
### Check for existing issues

- [X] Completed

### Language

[Heex](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#sigil_H/2)

### Misc notes

Came from:

- https://github.com/zed-industries/feedback/discussions/713

**Comment by ssaunderss** [comment]
I can't speak for Surface UI, but I'm pretty sure there's support for `.heex`, `.eex`, `.leex` file extensions out of the box on ElixirLS - there was a discussion about it towards the end of the closed ElixirLS ticket (#235) I think at least for those file extensions there might be a LS config value that was overwritten to not watch those file extension types.

**Comment by noozo** [comment]
+1

![image](https://user-images.githubusercontent.com/3353/218452059-d10e3870-1583-41fb-b910-52aaf9dc8736.png)

**Comment by ssaunderss** [comment]
Dived a bit deeper into this because I _really_ want to be able to do front end work in Zed 😀 

Here's the default file extensions from ElxiirLS - https://github.com/elixir-lsp/elixir-ls/blob/7ed5cdd86f102c232c824ceec37937270f2e87e2/apps/language_server/lib/language_server/server.ex#L79-L90 and it looks like this should be supported using default LS settings.

Is there a way we can access a languages default LSP config in Zed so we can make appropriate overrides @JosephTLyons ? I looked through the docs on the website and it doesn't seem like there's a way to see which config values are available for a given language's LSP.

**Comment by jrasanen** [comment]
Here's the HEEx grammar source,

https://github.com/phoenixframework/tree-sitter-heex

**Comment by noozo** [comment]
No joy since Nov? Might have to go back to VSCode since looking at non-highlighted sigils is starting to drive me crazy :(

**Comment by ssaunderss** [comment]
@petros https://github.com/firezone/firezone/tree/master/apps/fz_http/lib/fz_http_web/templates/auth is an example that uses `.heex` files 🙌

**Comment by petros** [comment]
When I check a `.ex` file both on Zed and VSCode this is what I see:

| Zed | VSCode |
|--------|--------|
| <img width="810" alt="CleanShot 2023-03-24 at 11 06 15" src="https://user-images.githubusercontent.com/28818/227474757-91c2c22a-a167-408a-a652-85af6b683bc0.png"> | <img width="777" alt="CleanShot 2023-03-24 at 11 05 54" src="https://user-images.githubusercontent.com/28818/227474767-b8e4263d-ead2-4f47-984d-733202252de9.png"> | 

Is it expected to see the part within sigils highlighted? If there is, why isn't this happening on VSCode?

For `.heex` files here's the point I reached:

<img width="836" alt="CleanShot 2023-03-24 at 11 11 08" src="https://user-images.githubusercontent.com/28818/227475982-5b7d9be4-f918-4f0c-9888-9bad92635aa5.png">

I am not entirely happy though cause you will notice a few inconsistencies. I am trying to figure out what I need to tweak.

**Comment by jrasanen** [comment]
> Is it expected to see the part within sigils highlighted? If there is, why isn't this happening on VSCode?

I don't use VSCode, but afaik it doesn't use tree-sitter.

With the proper tree-sitter parser like [Phoenix' heex](https://github.com/phoenixframework/tree-sitter-heex) the sigils should be highlighted.

## Helix editor has tree-sitter built in like Zed
![CleanShot 2023-03-24 at 11 16 34@2x](https://user-images.githubusercontent.com/13303/227477134-b582c8e4-d097-4c52-b49b-ff81d4c24b86.png)

**Comment by petros** [comment]
Thank you @jrasanen. I have added https://github.com/phoenixframework/tree-sitter-heex which gave us the file level highlight, but I guess I need to add something to also get it to highlight sigils. 🤔

**Comment by jrasanen** [comment]
Nice to hear, perhaps Elixir-LS is also required, https://github.com/elixir-lsp/elixir-ls

**Comment by ArthurMmn** [comment]
Here is Helix config for HEEX : 

> [[language]]
name = "heex"
scope = "source.heex"
injection-regex = "heex"
file-types = ["heex"]
roots = ["mix.exs", "mix.lock"]
indent = { tab-width = 2, unit = "  " }
language-server = { command = "elixir-ls" }
config = { elixirLS.dialyzerEnabled = false }

> [[grammar]]
name = "heex"
source = { git = "https://github.com/phoenixframework/tree-sitter-heex", rev = "2e1348c3cf2c9323e87c2744796cf3f3868aa82a" }

I guess you need to configure the injection of HEEX grammer in ex file ?

**Comment by jrasanen** [comment]
Here's what stuff looks like without and with the tree-sitter mode in Emacs using [elixir-ts-mode](https://github.com/wkirschbaum/elixir-ts-mode).

| Off | On |
|--------|--------|
| ![CleanShot 2023-03-24 at 21 52 46@2x](https://user-images.githubusercontent.com/13303/227626158-5b961191-0f11-4f5e-a539-e2391e15c0c6.png) | ![CleanShot 2023-03-24 at 21 53 00@2x](https://user-images.githubusercontent.com/13303/227626240-4ebe4883-63f5-48d2-b4c3-1c0fc855d67f.png) |

**Comment by ArthurMmn** [comment]
"Ironically", [Zed Blog](https://zed.dev/blog/syntax-aware-editing) mentionned how the Tree Sitter language injection works last week (Multi-language Documents paragraph) 😄 

Hope we can see this implemented in the near future 🙏

**Comment by petros** [comment]
Just a quick update on this. I spent some time trying to figure out the moving parts, and I reached a generally good point, but I am struggling with a formatting related error message I am getting from the language server. I know there are many folks eager to see better Elixir support (myself included 😄), but I will have to pause this for a bit. I will focus again on this soon though.

**Comment by noozo** [comment]
Ohh, i hope you get to focus on it soon again. This is a real source of pain for me, ATM :(

**Comment by JosephTLyons** [comment]
HEEX support should be landing in v0.90.0 - going to close this out.
