### ISSUE TITLE
Elixir `Go To Definition` is broken for external definitions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#731]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A user reported that `Go To Definition` seemed to be broken for definitions outside of the current file.  I haven't been able to reproduce this because I can't seem to get the Elixir language server running myself.

### Expected behavior

-

### Environment

v0.65.2

**Comment by ssaunderss** [comment]
@JosephTLyons I believe I was the one who reported this on Discord and it's working again now

**Comment by JosephTLyons** [comment]
Hmm, interesting.  Do you know if it has been broken the entire time since the issue was created?

**Comment by ssaunderss** [comment]
I noticed that it was broken for a few weeks following reporting this, I got used to not using it for a while and tried again a few weeks ago and noticed it started working again.

**Comment by JosephTLyons** [comment]
Ill close this for now - we can reopen if it comes up again.
