### ISSUE TITLE
`Go to Definition` sometimes opens up multiple tabs in TypeScript projects

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#734]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

A user said

> If I "Go to definition" of a React component, it sometimes takes me to both the component (one of my own in the same codebase) and the definition in typescript of React.  So, it opens 2 tabs in Zed: One with the local component, and one for FunctionComponent in node_modules/react/index.d.ts

I've ran into this as well.  Is this intentional with the TS server?

### Expected behavior

-

### Environment

v0.65.2

**Comment by as-cii** [comment]
I think this will open a multi-buffer containing both definitions in the newest Zed version. I am going to close this given that we handle it better now, but feel free to re-open if the behavior still feel surprising.

**Comment by sebkolind** [comment]
@as-cii I think the new solution is much better, however, I am not sure if it's worth opening up the `.d.ts` files at all. This is not happening in any other editor I've used. Instead they just go directly to the local component and not the `.d.ts` file.

This might be personal preference though.

**Comment by Kethku** [comment]
Would you be up for making a new issue with a repro steps for this and the expected behavior? Thats a pretty different problem that is specific to typescript.
