### ISSUE TITLE
Tailwind CSS support

### ISSUE THREAD

**Issue by chloerei** [zed-industries/community#746]
### Check for existing issues

- [X] Completed

### Language

Tailwind CSS

### Language server link

https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server

### Misc notes

Hope to be like Tailwind's VS Code plugin: https://github.com/tailwindlabs/tailwindcss-intellisense

Feature:

- Autocomplete ( with color preview and properties details)
- Linting
- Hover Preview

**Comment by bytemtek** [comment]
Is there TailwindCSS support?

**Comment by hovsater** [comment]
There's no Tailwind CSS support yet.

**Comment by rolanday** [comment]
+1. Buzz kill. Started using Zed, loved it. Then hit landmine -- no Tailwind intellisense. Stops me dead in my tracks. I'll stay subscribed and switch over after Tailwinds support added. Otherwise fantastic editor!!

**Comment by jesseb34r** [comment]
Would love to see this come to Zed. Definitely would make the switch easier

**Comment by aexvir** [comment]
please be considerate and only write a comment if there's something meaningful to add
for showing interest is enough to react with a 👍🏻 to this issue, writing +1 comments won't make this development go faster
these comments don't add any value to the issue, and we don't want to have to lock the issue to avoid the noise

with that said, it is on our radar and it will be tackled when priorities allow it

**Comment by widersky** [comment]
It would be good if Zed supported other locations of the `tailwind.config` file than project root - at the moment I have this file "buried" in several folders and autocomplete does not work at all 🤷‍♂️

**Comment by jezikk** [comment]
Or you can have a monorepo project with more different tailwind.config files.

**Comment by ForLoveOfCats** [comment]
@widersky Our experimental Tailwind autocomplete support has not shipped yet, you can try it out in our next preview build this Wednesday or on stable next week 😄

**Comment by patrikengborg** [comment]
Just tried it, it works in .html files and in css selectors when using it with @apply. But not in svelte/vue files.

Can I fix this with a setting somehow?

**Comment by matthewmorek** [comment]
> @widersky Our experimental Tailwind autocomplete support has not shipped yet, you can try it out in our next preview build this Wednesday or on stable next week 😄

I'm wondering if this will also work in JSX/TSX files, as opposed to just HTML/CSS?

**Comment by piyanggoon** [comment]
> > @widersky Our experimental Tailwind autocomplete support has not shipped yet, you can try it out in our next preview build this Wednesday or on stable next week 😄
> 
> I'm wondering if this will also work in JSX/TSX files, as opposed to just HTML/CSS?

I try on tsx it work fine.

**Comment by widersky** [comment]
@ForLoveOfCats tried and didn't work when config file was inside another folder 🤷‍♂️

**Comment by JosephTLyons** [comment]
Hey all, I'm going to close this issue since initial support is now in preview now.  We're bound to have some bugs.  If you're running into anything, please open new issues so we can track those separately.

**Comment by jeppech** [comment]
@patrikengborg I've created a separate issue for Tailwind in Svelte components here #2029, so it can be tracked there.

**Comment by nikitavoloboev** [comment]
<img width="766" alt="image" src="https://github.com/zed-industries/community/assets/6391776/6b7c277a-ad72-4bd0-a6af-e5ba50452860">

Updated to 0.103.1 which supposedly has this feature but as seen above it does not work with https://www.solidjs.com

Can it be made to work there too please? Solid uses `class=` syntax, maybe thats why it does not work?

The file/line I am editing above is [this](https://github.com/learn-anything/learn-anything.xyz/blob/main/website/src/routes/%5Btopic%5D/index.tsx#L82).

**Comment by eiiot** [comment]
I've been using the preview for a few weeks now, and I still can't get the language server working. It simply doesn't appear in the list of language servers.

Using the default NextJS project config.

**Comment by tmns** [comment]
Do we need to do something to enable the TW language server? So far in TSX files I'm not getting any completion / suggestions. Further, `Library/Application Support/zed/languages/tailwindcss-language-server` is empty. I tried manually building it from source and adding the binary in that dir but it seems to get overwritten / emptied out on start up.
