### ISSUE TITLE
New shortcut to select all matching text

### ISSUE THREAD

**Issue by exalted** [zed-industries/community#75]
VSCode calls this "select all occurrences of find match", and the gist is that I'd like to be able to select a piece of text (usually a word, a function name, a variable name, etc.) hit the keyboard combo (e.g., `Cmd-Ctrl-g`) and have all occurrences being selected.

Right now the workaround I am using is to select the text and keep `Cmd-d` pressed until it selects all matching text.

**Comment by iamnbutler** [comment]
Want

**Comment by JosephTLyons** [comment]
This would be a really nice way to do replaces in a single buffer - just grab all text and change it all at once.

**Comment by SomeoneToIgnore** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/2690773/214786760-cd436199-2894-4447-948f-395a509f2b9e.png">

Intellij provides somewhat enhanced functionality that allows to not only do "select all matches" thing, but also to add/remove such selections one by one, while searching.

**Comment by porsager** [comment]
This is the only thing keeping me with Sublime. Is there any way to know if this is considered and if there's a plan to add it?

**Comment by ryanwinchester** [comment]
Was just about to main Zed with some fixes I've been waiting for in v0.90.

However, I'm 10 minutes in and I don't know if I can live without this. I use it quite a bit.

**Comment by probablykasper** [comment]
I think VSCode's `Cmd-Shift-L` shortcut would be nice, instead of involving `Ctrl`

**Comment by SomeoneToIgnore** [comment]
This comes with the 0.96.0 version.

**Comment by ryanwinchester** [comment]
@SomeoneToIgnore And works in the `Editor` context, not just the `BufferSearchBar` one, as mentioned in #1749, since I see they were referenced to each other and closed in the same version? 🙏

**Comment by porsager** [comment]
Wooo.. awesome.. Can't wait to try it out.. Is there a date for 0.96?

**Comment by ryanwinchester** [comment]
> as long as the buffer search input is open

@SomeoneToIgnore  that is not `cmd-shift-L` (or `ctrl-cmd-g` in Sublime)

It should be like `cmd-d` except instead of `Next` it's `All`. There is no search buffer when doing this.

**Comment by SomeoneToIgnore** [comment]
That is all very confusing, looks I was wrong indeed.
Let's reopen this issue

**Comment by ryanwinchester** [comment]
@SomeoneToIgnore 

https://github.com/zed-industries/community/assets/2897340/6125532c-0af8-48b0-a268-7b6ff8738a06

**Comment by ryanwinchester** [comment]
@JosephTLyons this was re-opened but it's not in #52 anymore (just sayin 😅)

**Comment by JosephTLyons** [comment]
> @JosephTLyons this was re-opened but it's not in #52 anymore (just sayin 😅)

Was it in #52 recently? It looks like the issue at the end of the list has 40 upvotes and this one has 25, so I dont think it has had enough votes to be there, at least not for a long time.

**Comment by ryanwinchester** [comment]
I could be wrong, I just saw this on this issue's timeline and assumed it used to be in there.

<img width="656" alt="Screenshot 2023-07-15 at 12 32 47 AM" src="https://github.com/zed-industries/community/assets/2897340/57d22631-e69b-4c03-8b0a-529a1022c8a9">

**Comment by JosephTLyons** [comment]
> Wooo.. awesome.. Can't wait to try it out.. Is there a date for 0.96?

We ship a new minor version every Wednesday (unless its a crazy holiday time).  Right now, stable is at v0.94.  So v0.96 should go out the Wednesday after next (July 26th).

**Comment by JosephTLyons** [comment]
> I could be wrong, I just saw this on this issue's timeline and assumed it used to be in there.
> 
> 
> 
> <img width="656" alt="Screenshot 2023-07-15 at 12 32 47 AM" src="https://github.com/zed-industries/community/assets/2897340/57d22631-e69b-4c03-8b0a-529a1022c8a9">
> 
> 
> 
> Maybe it had been grouped with other issue(s)... Sorry about the ping
> 
> 

Yeah you're right, I think it was on there a long time ago, when we first started getting upvotes and all issues were kind of in the top. It got booted off sometime after that as other issues were upvoted past it.

**Comment by ryanwinchester** [comment]
Every Wednesday I open up Zed and check the update and every Wednesday I sad. 

![](https://media.tenor.com/yGA3JVg9nDoAAAAd/lonely-sad-walk.gif)

**Comment by JosephTLyons** [comment]
> Every Wednesday I open up Zed and check the update and every Wednesday I sad.
> 
> ![](https://camo.githubusercontent.com/6f0834b4b05c4379c248311fcc973871680499139a253527666dbbd80b6f1f98/68747470733a2f2f6d656469612e74656e6f722e636f6d2f794741334a5667396e446f41414141642f6c6f6e656c792d7361642d77616c6b2e676966)

No reason to be sad this Wednesday @ryanwinchester, it will be going out today :)

**Comment by JosephTLyons** [comment]
Ok, so this is officially released, but we made a mistake and put in the wrong binding.  We used `cmd-shift-d`, which by default is duplicate line, so we're going to put out a patch to make it `cmd-shift-l`. Hang tight.

**Comment by JosephTLyons** [comment]
We also have a crash when the selection is empty - this will be fixed in the same patch.
