### ISSUE TITLE
Highlight search matches in scrollbar

### ISSUE THREAD

**Issue by smbkr** [zed-industries/community#763]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

when searching for references to a particular string in a buffer, it can be useful to get a quick overview of where there are other matches.

### Describe the solution you'd like

highlight the location of matches in the scrollbar

### If applicable, add mockups / screenshots to help present your vision of the feature

Examples from vscode and intellij:

![vscode](https://user-images.githubusercontent.com/933535/206206858-ee35f7d4-99f8-47f8-b85b-06088fc7574b.png)
![intellij](https://user-images.githubusercontent.com/933535/206206905-ccd1457b-0758-4d8b-97a6-dce1cf9c8e71.png)

**Comment by JosephTLyons** [comment]
This is a nice suggestion.  I know others on the team want to do more with the sidebar; this fits in with those plans.

**Comment by aexvir** [comment]
this will go out this week (v0.95) thanks to @osiewicz 🙂
