### ISSUE TITLE
Add `NewlineAbove` command

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#791]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

-

### Describe the solution you'd like

We have a `NewlineBelow`, we should add a `NewlineAbove`

**Comment by handlebauer** [comment]
I use `NewlineAbove` A LOT in other editors

**Comment by dangdennis** [comment]
Looked for this. Would love this feature too. I'm always typing `shift-cmd-enter` in vscode.

**Comment by petros** [comment]
We are working on this. It's almost ready, minus a couple of integration tests.

**Comment by petros** [comment]
This is merged and should ship soon.
