### ISSUE TITLE
Workspace serialization additions

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#825]
### Check for existing issues

- [X] Completed

### Describe the feature

- [ ] #824
- [x] #414 
- [ ] #1005
- [ ] #1102
- [ ] #1189
- [ ] #1655

**Comment by rkusa** [comment]
I was happy to see basic workspace restoration land in the latest version! IMHO, with the basic restoration in place, the following issues got more important to be able to get back to a clean slate:
- #158
- #236

**Comment by JosephTLyons** [comment]
Version 0.68.x will introduce a few new tab-closing options:

- close all tabs
- close clean tabs (saved editors)

**Comment by JosephTLyons** [comment]
Going to close this meta issue, as the `serialization` tag tracks these requests nicely.
