### ISSUE TITLE
A bug appears when press the delete key while inputting Chinese

### ISSUE THREAD

**Issue by Shenchuanhuan** [zed-industries/community#877]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

 1. Switch to Chinese input method(I use the Wubi input method that comes with macOS)
 2. Type s then press the delete key
 3. The result shows `s}`

### Environment

 Zed 0.68.2 
 macOS 12.6

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![pic1](https://user-images.githubusercontent.com/24203427/213528437-3d0a0a27-23c6-4d92-a6a4-cfbd456c84b5.jpg)
![pic2](https://user-images.githubusercontent.com/24203427/213528459-019f3b38-bb30-4b3a-bda5-4c8fdab7988d.jpg)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by petros** [comment]
I can reproduce this currently:

### Actual
![chinese-zed](https://user-images.githubusercontent.com/28818/213670246-7d8e4c82-e1fa-46fb-9b35-b21313415307.gif)

### Expected
![chinese-code](https://user-images.githubusercontent.com/28818/213670173-57c0e3f4-2e1f-4b6a-b15a-1b77b9cd036d.gif)

**Comment by petros** [comment]
@Shenchuanhuan thank you for the feedback. Just to be sure. Is the expected behavior the deletion of the typed character? I am asking cause after researching this a bit, I have found mixed results about how this should behave.

**Comment by ForLoveOfCats** [comment]
My understanding of backspace in more complex scripts is that it ideally should be somewhat special cased where in cases like this it deletes the entire grapheme but in cases like composite emoji it should delete just the codepoint so that the emoji decomposes step by step with each backspace. That however is much easier said than done and we have quite a few areas where we lack complex script handling awareness

**Comment by hujunil** [comment]
@JosephTLyons 

This bug still exists in version 0.102.1

**Comment by JosephTLyons** [comment]
Sorry @hujunil, it never got resolved.  I'll bring this up with the team again next all-hands meeting.  We have a handful of internationalization issues that we really need to spend some time on.

**Comment by osiewicz** [comment]
Yup, confirmed that it's still reproducible in 0.102.1 and 0.103.1. This does not happen if the language is not set (e.g. in new unnamed buffer). Maybe it has to do with the automatic ending brace insertion?

**Comment by osiewicz** [comment]
The fix for this issue is getting released to today's Preview. :) Let us know if it works for you.

**Comment by weizhliu** [comment]
Zed Preview 0.105.0 solved this issue for me, thanks.
(using MacOS build-in Zhuyin input for Traditional Chinese)

**Comment by JosephTLyons** [comment]
I'm going to close this issue.  If the issue still exists in some form, please feel free to reopen!
