### ISSUE TITLE
Nix support

### ISSUE THREAD

**Issue by cmoog** [zed-industries/community#878]
### Check for existing issues

- [X] Completed

### Describe the feature

Language
Nix

Tree Sitter parser link
https://github.com/cstrahan/tree-sitter-nix

Language server link
N/A

Misc notes
[Nix](https://nixos.org/) the language.

**Comment by zetashift** [comment]
I think a lot of people don't use LSP for their Nix stuff, but just in case:

- https://github.com/oxalica/nil
- https://github.com/nix-community/rnix-lsp

**Comment by cmoog** [comment]
Happy to see that this was released in `Zed 0.98.2`!!

**Comment by JosephTLyons** [comment]
I believe we only have language server support and nothing powered by a lanugage server - a new issue is probably in order for that.
