### ISSUE TITLE
Show warnings in diagnostics

### ISSUE THREAD

**Issue by EvHaus** [zed-industries/community#895]
### Check for existing issues

- [X] Completed

### Describe the feature

When writing code, I prefer my editor not to clutter the main code content with warning icons, red underlines or other distracting UI elements when there are linter or compiler errors. Instead I prefer those errors to be shown in a list view as a separate panel. At the moment (I think), this isn't possible with Zed. Logging this ticket as a feature request to add this ability.

Ideally this panel would aggregate errors from all the various formatters/linters that are currently activated on that file. In my case I do a lot of Javascript/Typescript development, and use a combination of `prettier`, `eslint`, `rome`, and `typescript`. The panel should show a list of all relevant errors across all the tools I have enabled for that project/file-type, sorted by line number.

Here's an example of how such a feature looks like in VS Code:

<img width="1282" alt="Screenshot 2023-01-27 at 12 37 42 PM" src="https://user-images.githubusercontent.com/226640/215192512-552314d7-505d-4e74-9193-33d580732f84.png">

**Comment by Kethku** [comment]
The diagnostics tab can be opened with `cmd-shift-m` and shows a list of all of the active errors in the workspace that any running lsps currently report.

Along with more detailed information about the error, the diagnostics tab has live editors so you can fix them right there.

**Comment by Kethku** [comment]
This is different from the diagnostics sidebars many other editors have, but covers much of the same usecases and a few more

**Comment by EvHaus** [comment]
Ah ok. It's called "Diagnostics" in Zed. Didn't realize!

Unfortunately it doesn't seem to work for me. Here's an example where the code editor is highlighting an error in the code: "'a' is declared but its value is never read." But this error doesn't appear in the Diagnostics panel:

<img width="639" alt="Screenshot 2023-01-27 at 12 50 57 PM" src="https://user-images.githubusercontent.com/226640/215194728-ca3dff5f-278d-4132-af8a-fd9446464f55.png">

**Comment by Kethku** [comment]
That diagnostic is a hint level and doesn't show up in the diagnostics tab currently. Often times this can be configured in your project to raise the severity to at least a warning.

We may add configuration for this in the future.

**Comment by iamnbutler** [comment]
I'm going to change the title of this task to "Show warnings in diagnostics" as that is the root of this feedback I believe.

**Comment by EvHaus** [comment]
Looks like this is working in Zed 0.86 now? 🎉 

<img width="1043" alt="Screenshot 2023-05-18 at 12 56 40 PM" src="https://github.com/zed-industries/community/assets/226640/ab1d4572-30f1-4301-a49c-571d3058d2ea">

I'll close the issue.
