### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by rkusa** [zed-industries/community#931]
### Check for existing issues

- [X] Completed

### Describe the feature

Both VSCode and Sublime Text have a very convenient search history. Simply use arrow up and down to traverse the history (works both in local as well as global search). It'd be great if Zed would have something similar.

### If applicable, add mockups / screenshots to help present your vision of the feature

https://user-images.githubusercontent.com/409021/217078898-0854571e-361b-4f02-9286-464fc14590eb.mov

**Comment by SomeoneToIgnore** [comment]
Zed actually has this for a while already, the only thing that is not done is persistence: the history does not preserve between Zed restarts or panel reopens.

Let's close this and have a different issue for the persistence.
