### ISSUE TITLE
Serendipity Theme Family Support

### ISSUE THREAD

**Issue by covt** [zed-industries/community#933]
### Check for existing issues

- [X] Completed

### Describe the feature

Support for Serendipity family of themes, with the color palettes for each being provided here.  https://serendipitytheme.com/serendipity-color-palette/

The theme family supports 3 versions:

Morning (Mid Light)
Sunset (Low Contrast Dark)
Midnight (Mid Contrast Dark)

Morning
<img width="926" alt="image" src="https://user-images.githubusercontent.com/4238771/217338344-cb68f6ad-07e9-42ba-a1aa-3add9244716b.png">

Sunset
<img width="926" alt="image" src="https://user-images.githubusercontent.com/4238771/217339195-ffd0b4f1-622e-43fc-8570-73c88e1bf29c.png">

Midnight
<img width="926" alt="image" src="https://user-images.githubusercontent.com/4238771/217339374-3d974645-1a4d-49f2-a5d6-06c91b213742.png">

**Comment by iamnbutler** [comment]
FYI I did start on a Serendipity port, however it looks like until we land theme overrides (which Mikayla is working on right now luckily!) it won't really look at all correct:

<img width="1728" alt="CleanShot - 2023-02-08 at 22 37 27@2x" src="https://user-images.githubusercontent.com/1714999/217712012-24d81dab-2b0f-4098-b83f-3d36130be46a.png">

I'll get it set up but wait until we ship overrides before we ship the theme family.

**Comment by iamnbutler** [comment]
Most of the way there on this :) It's coming!

<img width="1840" alt="CleanShot 2023-02-26 at 22 41 54@2x" src="https://user-images.githubusercontent.com/1714999/221467827-2200dc78-41ec-4b1c-ae27-f39ae63cbf4a.png">

**Comment by iamnbutler** [comment]
Closed in favor of https://github.com/zed-industries/community/discussions/1780

A extra little note on this one - Sorry for getting it partially done and cancelling it. We are hitting an upper limit of what we can reasonably compile locally since our current theme implementation generates 10k+ lines of json per theme. We are working on changing this system, and I'll make sure we get this in when we can!

**Comment by covt** [comment]
> 

No worries, I've been using Zed daily even without this. Excited to see the future theme implementation!
