### ISSUE TITLE
Typos on the Python page

### ISSUE THREAD

**Issue by MultisampledNight** [zed-industries/community#944]
### Check for existing issues

- [X] Completed

### Page link

https://zed.dev/docs/languages/python

### Description

```diff
- A python virtual environment allows you store all
+ A python virtual environment allows you to store all
```

```diff
- any directory that contains one or more a virtual environment directories
+ any directory that contains one or more virtual environment directories
```

```diff
- you can use it format Python files
+ you can use it to format Python files
```

...not really a typo, but the first half of the page uses the word `directory`, when suddenly the `For example, [...]` section uses `folder`. Slightly confusing to me, given that the "magic phrase" `virtual environment directory` appears very often in the theoretical explanation, and that pattern is broken in the example.

<3

**Comment by JosephTLyons** [comment]
Hey @MultisampledNight - thanks for catching these typos.  Also, I had no idea you could just mark a block as a diff in GitHub-flavored Markdown, that's pretty useful!

**Comment by JosephTLyons** [comment]
Hey @MultisampledNight, just wanted to let you know that we open-sourced our [`docs`](https://github.com/zed-industries/docs) repo.  Just wanted to let you know since you seem to have a great eye for details.
