### ISSUE TITLE
Vim mode repeat last command (`.`)

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#946]
### Check for existing issues

- [X] Completed

### Describe the feature

-

**Comment by kconner** [comment]
In many vim modes this command makes the difference to me between an OK experience and a great one. I will often move to a word, `*N` to load it into search and then focus it again, `ce` to replace the word, type, finish the edit, then `n.n.n.n.` to make the same edit wherever else I found it, sometimes skipping the `.` case by case.

**Comment by ConradIrwin** [comment]
This shipped in v0.104.x, please test it out and let me know anything else that is needed.
