### ISSUE TITLE
Clicking on the tab of a panel doesn't focus it.

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/community#953]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. Have two (split) panels or one normal panel and the side panel open.
2. Select the editor in panel 1.
3. Try to click the `+` icon to create a new file or terminal in panel 2. -> Doesn't work, even after clicking on the tab bar of panel 2. Workaround: Focus an editor/terminal in that panel first.

It would be optimal if the `+` and split buttons would appear on hover even if the panel is not in focus imo.

### Environment

Zed: v0.72.5 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

https://user-images.githubusercontent.com/19362696/218683307-92f59783-0f03-4077-93b3-bda8681cbae2.mov

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ForLoveOfCats** [comment]
Good catch! Thanks for letting us know :)
