### ISSUE TITLE
Rust-analyzer timing out / failing

### ISSUE THREAD

**Issue by stjepangolemac** [zed-industries/community#971]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm working on a fairly complex project and LSP crashes everytime I open a (very large ~10k lines) specific file. I've checked the Zed log but I only see this:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/15632814/219694159-8f7147e6-283c-4703-971d-cb9099fa02c7.png">

Are there any better ways to debug this?

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.1.0
Memory: 64 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by stjepangolemac** [comment]
To give you a bit more context, here's the project that always breaks down Zed's LSP.

https://github.com/stacks-network/stacks-blockchain/tree/master/testnet/stacks-node

If you open the file below, and make a change anywhere, the LSP stops working.

https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/tests/neon_integrations.rs

I can do a "editor: restart language server" and it will work until the next change.

Let me know if I can help you in any way. Unfortunately, this forces me to move to a different editor until it's resolved.

NOTE: VSCode with the rust-analyzer plugin works without issues.

**Comment by stjepangolemac** [comment]
I get a bunch of those, not sure if this is normal

```
Diagnostic { code: DiagnosticCode("macro-error"), message: "reached recursion limit during macro expansion", range: 3254..3277, severity: Error, unused: false, experimental: true, fixes: None }
```

**Comment by igorsyl** [comment]
> `Diagnostic { code: DiagnosticCode("macro-error"), message: "reached recursion limit during macro expansion", range: 3254..3277, severity: Error, unused: false, experimental: true, fixes: None }`

Is the LSP part of Zed, or a plug-in? Looks like the stack depth limit needs to be raised.

**Comment by stjepangolemac** [comment]
Not sure what happened in the meantime but I'm not experiencing this anymore.
