### ISSUE TITLE
CPU usage: One core is at constant 100% without doing anything

### ISSUE THREAD

**Issue by N8th8n8el** [zed-industries/community#981]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I just noticed my laptop getting warm and it turns out Zed was using 100% cpu without doing anything.
I closed all terminals (just in case), but it didn't go away.
Nothing interesting in the logs.
This happened in a typescript project.

Due to the limited information this is probably not very helpful, but maybe someone else encounters something similar in the future.
![Screenshot 2023-02-20 at 13 20 11](https://user-images.githubusercontent.com/19362696/220106449-69d178cb-1e43-413e-b8a8-d4bafba09731.png)
Ram usage was at 1,44GB

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.1.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by darkoceans** [comment]
I've encountered this issue too. 

I've noticed it during the last 2-3 months - but that has coincided with my using Zed as a daily driver for Python development whereas previously I was only using Zed for infrequent Rust and Markdown editing. 

* Zed: v0.110.2 (stable)
* OS: macOS 12.6.0
* Memory: 16 GiB
* MacBook Pro (14-inch, 2021)

The main noticeable issues from this high CPU usage is the long lag in opening and saving files - between a minute or two. 

This might have related issues I've noticed around interaction between Terminal file activity (deleting/creating files, git-commits/pushes) and the project file structure in the left-dock.

Restarting Zed reduces CPU usage to an expected idle level of around 0-5%. 

Opening a Terminal in Zed pushes the CPU to 100% from which it doesn't slow down for a minute or two. Some activities in the terminal window pushes CPU usage up to 100% (eg `cd some-directory` - my command line prompt is set up to check git status at 20 min intervals) where as some commands do not push CPU usage up (eg `top`). Running `cd` or `top` in the Terminal.app has the CPU only spike to 6-7% in both cases.

Another thing of note is that this is on a company-provided laptop and the company uses ZScaler as a man-in-the-middle 'service'. ZScaler can mangle things with certificates if they are not known. However my install of Zed is able to check for, and download, updates so I don't expect there to be an issue between Zed and ZScaler here.

**Comment by darkoceans** [comment]
Just an update... 
After either the 0.117.0 or 0.116.1 update I'm no longer seeing the CPU maxing out after file operations such as saving/opening

**Comment by N8th8n8el** [comment]
I haven't encountered this in a long time either.

**Comment by JosephTLyons** [comment]
Let's close this for now - we can reopen if it comes up again.
