### ISSUE TITLE
Vim-mode Enter should not make a new line

### ISSUE THREAD

**Issue by TENX-S** [zed-industries/community#987]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

https://user-images.githubusercontent.com/40336192/220617525-55b795f0-b287-4355-b150-c23b4b13f273.mov

VS Code:

https://user-images.githubusercontent.com/40336192/220617636-68577b8f-cb24-47f8-993d-fe5cd18d6e20.mov

Idea:

https://user-images.githubusercontent.com/40336192/220617844-904350b3-cfbc-45c6-908a-6c5aa5a1be4e.mov

### Environment

Zed: v0.73.3 (stable)
OS: macOS 13.2.1
Memory: 8 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by clo4** [comment]
This is fixed as of the update published today!

**Comment by TENX-S** [comment]
Not really, I experienced the same issue with 0.74.2. @clo4 

https://user-images.githubusercontent.com/40336192/220805429-d4b13b75-39de-46b5-a786-d1390bca93f2.mov

**Comment by clo4** [comment]
That is so weird, I couldn't repro but I tried again and now I can. So still definitely an issue :(

**Comment by Kethku** [comment]
Reopened as this hasn't been addressed. Im working on a fix soon

**Comment by Kethku** [comment]
This is fixed in current main and should be released soon.
