### ISSUE TITLE
rust-analyzer is not working

### ISSUE THREAD

**Issue by igor-yusupov** [zed-industries/community#996]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

rust-analyzer and autocomplete suddenly stopped working. what should I do?

### Environment

rust with cargo

_No response_

**Comment by JosephTLyons** [comment]
Hey @igor-yusupov, it's hard to tell what might be going on.

Do you see any errors that might be related in your Zed log? 

- `~/Library/Logs/Zed/Zed.log`

Does performing any of the following resolve the issue?

- Running `editor: restart language server` in the command palette
- Closing and reopening Zed
- Running `cargo clean && cargo build` on your Rust project

**Comment by igor-yusupov** [comment]
I have removed rust-analyzer, reopened Zed and now it works.

**Comment by JosephTLyons** [comment]
Huh, yeah, once in awhile, something gets corrupted with RA and deleting and allowing Zed to reinstall it corrects it.  I didn't think to mention it here because it's been awhile since I've had to do that.  We probably need to improve this experience in some way, but I'm not quite sure how yet.
