### ISSUE TITLE
Relative Line Numbers

### ISSUE THREAD

**Issue by nayaabkhan** [zed-industries/community#998]
### Check for existing issues

- [X] Completed

### Describe the feature

Show the line number relative to the current line (where the cursor is). It is usually helpful in combination with Vim mode, to jump to a specific line using motion keys (e.g., h-j-k-l).

Vim has it built-in (https://vimhelp.org/options.txt.html#%27relativenumber%27). Visual Studio Code also has it built-in using `editor.lineNumbers`.

### If applicable, add mockups / screenshots to help present your vision of the feature

![](https://brianschmitt.gallerycdn.vsassets.io/extensions/brianschmitt/relativenumber/1.6.0/1544196949159/151285/1/Screenshot.PNG)

**Comment by jschuur** [comment]
This was the first thing I looked for after installing Zed an enabling `vim_mode`.

**Comment by ruiconti** [comment]
+1 this is key to fast code navigation.

**Comment by WindSoilder** [comment]
It'd be really useful in vim mode

**Comment by 0x2CA** [comment]
Is it possible to display both

**Comment by dsosby** [comment]
Vim mode without relative line numbers is like pizza without cheese.

**Comment by JosephTLyons** [comment]
This feature has been merged into main and v0.102.0.
